[package]
name = "fragmentcolor"
version = "0.1.0"
homepage = "https://fragmentcolor.org"
repository = "https://github.com/vista-art/fragmentcolor"
description = "Easy GPU Rendering for Javascript, Python, Swift and Kotlin."
authors = ["Vista Tech & Art GmbH"]
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = [
    "graphics",
    "gpu",
    "rendering",
    "webgl",
    "wgpu",
    "vulkan",
    "metal",
    "opengl",
    "directx",
    "python",
    "javascript",
    "swift",
    "kotlin",
    "ios",
    "android",
    "macos",
    "windows",
    "linux",
    "web",
]
categories = ["graphics", "rendering", "gpu", "wgpu", "python", "javascript"]
edition = "2021"

[lib]
name = "fragmentcolor"
crate-type = ["cdylib", "rlib"]

[dependencies]
# Rendering

wgpu = { version = "24", features = ["glsl", "wgsl", "webgl", "naga-ir"] }
uuid = { version = "1.13", features = ["v4", "serde", "fast-rng"] }
thiserror = { version = "2" }
glam = { version = "0.29" }
encase = { version = "0.10" }
bytemuck = { version = "1" }
flume = { version = "0.11" }
indoc = { version = "2" }
log = { version = "0.4" }
sha2 = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
parking_lot = { version = "0.12" }

# Windowing and input
raw-window-handle = { version = "0.6" }
winit = { version = "0.30.9", features = ["serde"] }

# Shader composition
naga = { version = "24" }
naga_oil = { version = "0.17" }

# Serialization
csscolorparser = "0.7"
fxhash = "0.2"

# Async
pollster = "0.4"

# Text rendering
wgpu_text = "0.9"

# Time
instant = "0.1"

# Logging
env_logger = "0.11"

# Asset loading
image = { version = "0.25", default-features = false, features = [
    "jpeg",
    "png",
    "bmp",
    "hdr",
    "dds",
] }
gltf = { version = "1", features = [
    "names",
    "utils",
    "KHR_lights_punctual",
], optional = true }
obj = { version = "0.10", optional = true }
ddsfile = "0.5"

# Sync
futures-intrusive = "0.5"

# Android & iOS FFI
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
uniffi = { version = "0.29" }

# iOS Specific
[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2"
core-graphics = "0.24"

# WASM-Specific
[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde-wasm-bindgen = "0.6"
console_log = "1.0"
console_error_panic_hook = { version = "0.1" }
reqwest = { version = "0.12" }
gloo-utils = { version = "0.2", features = ["serde"] }
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    'Document',
    'Element',
    'HtmlCanvasElement',
    'Window',
    'EventTarget',
    'Location',
] }

[build-dependencies]
cfg_aliases = "0.2"
