[workspace]

members = [
    "crates/core",
    "crates/plrender",
    "plrender-wasm",
    "plrender-py",
    # "examples/rust",
    "xtask"
]

resolver = "2"

[profile.release]
opt-level = "s" # Optimize for small binary size
