[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
phf = { version = "0.11", features = ["macros"] }
phf_codegen = "0.11"

[dev-dependencies]
tempfile = "3.2"
