# Autogenerated by build.rs — do not edit manually.
from __future__ import annotations

from typing import Any, Mapping, Sequence, overload
import numpy
import numpy.typing as npt

PySize = tuple[int, int] | tuple[int, int, int] | Sequence[int] | Mapping[str, int]
NDArrayU8 = npt.NDArray[numpy.uint8]
Renderable = 'Shader' | 'Pass' | 'Frame' | Sequence['Shader' | 'Pass']

class FragmentColorError(Exception): ...

class Size:
    width: int
    height: int
    depth: int | None

    def __init__(self, width: int, height: int, depth: int | None = None) -> None: ...

class Region:
    def __init__(self, origin: tuple[int, int], size: tuple[int, int]) -> None: ...
    @classmethod
    def from_region(cls, x: int, y: int, width: int, height: int) -> 'Region': ...
    @classmethod
    def from_tuple(cls, size: tuple[int, int]) -> 'Region': ...

class TextureFormat:
    ...

class Texture:
    """
    # Texture
    
    A GPU texture resource. Public API wrapper that holds a shareable reference to the internal TextureObject and a numeric handle used by uniforms.
    
    - Construct via [Renderer](https://fragmentcolor.org/api/core/renderer)::create_texture_* helpers (no direct constructors)
    - Set on shaders with shader.set("key", &[Texture](https://fragmentcolor.org/api/core/texture))
    - [Texture](https://fragmentcolor.org/api/core/texture) owns its sampler; you can tweak filtering and wrapping via set_sampler_options.
    
    ## How to use
    
    Create a [Texture](https://fragmentcolor.org/api/core/texture) and set it on a [Shader](https://fragmentcolor.org/api/core/shader)
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer, Shader
    renderer = Renderer()
    shader = Shader('''
    @group(0) @binding(0) var my_texture: texture_2d<f32>;
    @group(0) @binding(1) var my_sampler: sampler;
    @vertex fn vs_main(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
      let p = array<vec2<f32>,3>(vec2f(-1.,-1.), vec2f(3.,-1.), vec2f(-1.,3.));
      return vec4f(p[i], 0., 1.);
    }
    @fragment fn main() -> @location(0) vec4<f32> { return vec4f(1.,1.,1.,1.); }
    
    ''')
    
    # 1x1 RGBA (white) raw pixel bytes
    pixels = [255,255,255,255]
    texture = renderer.create_texture_with_size(pixels, [1,1])
    
    # insert  the texture in the shader matching the name in the shader
    shader.set("my_texture", texture)
    ```
    """
    @property
    def size(self) -> Size: ...
    """
    # Texture::size
    
    Returns the texture size (w, h[, d]).
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Renderer
    renderer = Renderer()
    pixels = [255,255,255,255]
    tex = renderer.create_texture_with_size(pixels, [1,1])
    sz = tex.size
    ```
    """
    def aspect(self) -> float: ...
    """
    # Texture::aspect
    
    Returns width/height as f32.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer
    
    renderer = Renderer()
    # 1x1 RGBA (white) raw pixel bytes
    pixels = [255,255,255,255]
    tex = renderer.create_texture_with_size(pixels, [1, 1])
    a = tex.aspect()
    ```
    """
    def set_sampler_options(self, options: Mapping[str, Any]) -> None: ...
    """
    # Texture::set_sampler_options
    
    Update the texture sampler options (filtering, wrapping, etc.).
    
    Note: changes take effect on next bind; the renderer recreates the sampler as needed.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Renderer
    renderer = Renderer()
    # 1x1 RGBA (white) raw pixel bytes
    pixels = [255,255,255,255]
    
    texture = renderer.create_texture_with_size(pixels, [1,1])
    opts = {"repeat_x": True, "repeat_y": True, "smooth": True, "compare": None}
    texture.set_sampler_options(opts)
    ```
    """

class Vertex:
    """
    # Vertex
    
    A single vertex with a required position (2D or 3D) and optional properties like uv and color.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Vertex
    v = Vertex([0.0, 0.0, 0.0]).set("uv", [0.5, 0.5])
    ```
    """
    def __init__(self, position: Any) -> None: ...
    def set(self, key: str, value: Any) -> 'Vertex': ...
    def create_instance(self) -> 'Instance': ...

class Instance:
    def __init__(self) -> None: ...

class VertexValue:
    @staticmethod
    def f32(x: float) -> Any: ...
    @staticmethod
    def f32x2(x: tuple[float, float] | Sequence[float]) -> Any: ...
    @staticmethod
    def f32x3(x: Sequence[float]) -> Any: ...
    @staticmethod
    def f32x4(x: Sequence[float]) -> Any: ...
    @staticmethod
    def u32(x: int) -> Any: ...

class Mesh:
    """
    # Mesh
    
    High-level geometry container. A Mesh owns a list of vertices and optional instances.
    Internally it deduplicates vertices and always draws indexed and instanced
    (instance_count defaults to 1 when none are provided).
    
    Vertex layouts are managed by the Shader. At render time, inputs declared in your
    shader's vertex function (annotated with @location(N)) are derived from the source
    and matched by name and type to Mesh properties across both streams (instance first,
    then vertex).
    
    Mapping is driven by shader reflection; there are no special-case names or reserved locations.
    The renderer matches attributes by explicit location if provided (instance first, then vertex),
    and otherwise by name.
    
    If a required input cannot be found or its type does not match, rendering returns an error
    indicating the missing attribute or mismatch.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Mesh, Vertex
    
    mesh = Mesh()
    mesh.add_vertex([0.0, 0.5, 0.0])
    mesh.add_vertex([-0.5, -0.5, 0.0])
    mesh.add_vertex([0.5, -0.5, 0.0])
    ```
    """
    def __init__(self) -> None: ...
    """
    # Mesh.new_py
    
    Platform-specific Python constructor wrapper for Mesh.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    @staticmethod
    def from_vertices(vertices: Sequence[Any]) -> 'Mesh': ...
    """
    # Mesh.from_vertices_py
    
    Python static helper that mirrors Mesh::from_vertices.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    def add_vertex(self, vertex: Any) -> None: ...
    """
    # Mesh.add_vertex_py
    
    Python wrapper for Mesh::add_vertex.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    def add_vertices(self, vertices: Sequence[Any]) -> None: ...
    """
    # Mesh.add_vertices_py
    
    Python wrapper for Mesh::add_vertices.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    def add_instance(self, item: Any) -> None: ...
    """
    # Mesh.add_instance_py
    
    Python wrapper for Mesh::add_instance.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    def add_instances(self, items: Sequence[Any]) -> None: ...
    """
    # Mesh.add_instances_py
    
    Python wrapper for Mesh::add_instances.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    def clear_instances(self) -> None: ...
    """
    # Mesh.clear_instances_py
    
    Python wrapper for Mesh::clear_instances.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    def set_instance_count(self, n: int) -> None: ...
    """
    # Mesh.set_instance_count_py
    
    Hidden Python wrapper for Mesh::set_instance_count.
    
    Used for IDE hover via lsp_doc; not exported on the website.
    
    ```rust
    // hidden wrapper doc; no public example
    ```
    """
    def clear_instance_count(self) -> None: ...
    """
    # Mesh.clear_instance_count_py
    
    Hidden Python wrapper for Mesh::clear_instance_count.
    
    Used for IDE hover via lsp_doc; not exported on the website.
    
    ```rust
    // hidden wrapper doc; no public example
    ```
    """

class Quad:
    """
    # Quad
    
    A simple rectangle (quad) builder for 2D rendering.
    Produces a Mesh with position (vec2) and uv (vec2) per-vertex.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Quad
    
    quad = Quad([-0.5, -0.5], [0.5, 0.5])
    ```
    """
    def __init__(self, min: tuple[float, float], max: tuple[float, float]) -> None: ...
    def get_mesh(self) -> Mesh: ...

class Pass:
    """
    # Pass
    
    The [Pass](https://fragmentcolor.org/api/core/pass) object is a collection of [Shader](https://fragmentcolor.org/api/core/shader) objects that are rendered to a [Target](https://fragmentcolor.org/api/core/target) by the [Renderer](https://fragmentcolor.org/api/core/renderer).
    
    While the [Shader](https://fragmentcolor.org/api/core/shader) represents a single **Render Pipeline** or a **Compute Pipeline**,
    the [Pass](https://fragmentcolor.org/api/core/pass) can be used to draw multiple Shaders in sequence,
    for example when you have multiple objects in a scene with different materials.
    
    The [Pass](https://fragmentcolor.org/api/core/pass) represents a single RenderPass or a ComputePass in the WebGPU API.
    
    The constructor creates a RenderPass by default. To create a ComputePass, call [Pass](https://fragmentcolor.org/api/core/pass)::compute().
    
    After creation, it will only accept a compatible [Shader](https://fragmentcolor.org/api/core/shader) object. If you try to add a Compute [Shader](https://fragmentcolor.org/api/core/shader) to a Render [Pass](https://fragmentcolor.org/api/core/pass) or vice-versa,
    it won't add the shader to its internal list and log a warning message in the console.
    
    
    
    Example (Python):
    
    ```python
    from rendercanvas.auto import RenderCanvas, loop
    
    from fragmentcolor import Shader, Pass, Renderer, Frame
    
    renderer = Renderer()
    canvas = RenderCanvas(size=(100, 100))
    target = renderer.create_target(canvas)
    shader = Shader.default()
    
    rpass = Pass("First Pass")
    rpass.add_shader(shader)
    
    pass2 = Pass("Second Pass")
    pass2.add_shader(shader)
    
    # standalone
    renderer.render(rpass, target)
    
    # using a Frame
    frame = Frame()
    frame.add_pass(rpass)
    frame.add_pass(pass2)
    renderer.render(frame, target)
    
    # vector of passes (consume them)
    renderer.render([rpass, pass2], target)
    ```
    """
    def __init__(self, name: str) -> None: ...
    """
    # Pass::new(name: &str) -> Self
    
    ## Creates a new Pass
    
    The name property is optional and is used for debugging purposes.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Pass
    
    rpass = Pass("first rpass")
    ```
    """
    @staticmethod
    def compute(name: str) -> 'Pass': ...
    """
    # Pass::compute(name: &str) -> Pass
    
    Creates a new [Pass](https://fragmentcolor.org/api/core/pass) configured for compute workloads.
    
    Only [Shader](https://fragmentcolor.org/api/core/shader) objects that compile to compute pipelines can be added.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Pass, Shader
    
    cs = Shader("@compute @workgroup_size(8,8,1) fn cs_main() {}")
    rpass = Pass("compute"); rpass.add_shader(cs)
    ```
    """
    @staticmethod
    def from_shader(name: str, shader: 'Shader') -> 'Pass': ...
    """
    # Pass::from_shader(name: &str, shader: Shader) -> Pass
    
    Creates a new [Pass](https://fragmentcolor.org/api/core/pass) from a single [Shader](https://fragmentcolor.org/api/core/shader).
    
    The created [Pass](https://fragmentcolor.org/api/core/pass) inherits the render/compute type from the provided [Shader](https://fragmentcolor.org/api/core/shader).
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Pass, Shader
    
    shader = Shader.default()
    rpass = Pass("single"); rpass.add_shader(shader)
    ```
    """
    def passes(self) -> Sequence['Pass']: ...
    def load_previous(self) -> None: ...
    """
    # Pass::load_previous()
    
    Configures this [Pass](https://fragmentcolor.org/api/core/pass) to load the previous contents of the [Target](https://fragmentcolor.org/api/core/target) instead of clearing it.
    
    This is useful when layering multiple passes where the next pass should blend with the prior results.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer, Pass, Shader
    
    renderer = Renderer()
    target = renderer.create_texture_target([64, 64])
    
    shader = Shader.default()
    rpass = Pass("blend with previous")
    rpass.add_shader(shader)
    rpass.load_previous()
    
    renderer.render(rpass, target)
    ```
    """
    def get_input(self) -> Any: ...
    """
    # Pass::get_input() -> PassInput
    
    Returns a copy of the current input configuration for this [Pass](https://fragmentcolor.org/api/core/pass).
    
    It includes the clear/load behavior and clear color.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Pass
    
    rpass = Pass("example")
    input = rpass.get_input()
    ```
    """
    def add_shader(self, shader: 'Shader') -> None: ...
    """
    # Pass::add_shader(shader: Shader)
    
    Adds a [Shader](https://fragmentcolor.org/api/core/shader) object to the [Pass](https://fragmentcolor.org/api/core/pass).
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Pass, Shader
    
    shader = Shader.default()
    rpass = Pass("p")
    rpass.add_shader(shader)
    ```
    """
    def add_mesh(self, mesh: 'Mesh') -> None: ...
    """
    # Pass::add_mesh
    
    Attach a Mesh to this Pass.
    
    - The mesh is attached to the last shader previously added to this Pass.
    - Validates compatibility with that shader's vertex inputs.
    - Returns Result<(), ShaderError>; on error, the mesh is not attached.
    
    If a Shader wasn't provided earlier, FragmentColor will create a default one.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Pass, Shader, Mesh
    
    mesh = Mesh()
    mesh.add_vertex([0.0, 0.0])
    
    shader = Shader('''
      struct VOut { @builtin(position) pos: vec4<f32> };
      @vertex
      fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
        var out: VOut;
        out.pos = vec4<f32>(pos, 0.0, 1.0);
        return out;
      }
      @fragment
      fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }
    
    ''')
    
    rpass = Pass("rpass"); rpass.add_shader(shader)
    
    rpass.add_mesh(mesh)
    ```
    """
    def add_mesh_to_shader(self, mesh: 'Mesh', shader: 'Shader') -> None: ...
    """
    # Pass::add_mesh_to_shader
    
    Attach a Mesh to a specific Shader in this Pass. This forwards to `shader.add_mesh(mesh)` and returns the same Result.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader, Mesh, Vertex, Pass
    
    mesh = Mesh()
    mesh.add_vertex(Vertex([0.0, 0.0]))
    shader = Shader('''
      struct VOut { @builtin(position) pos: vec4<f32> };
      @vertex
      fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
        var out: VOut;
        out.pos = vec4<f32>(pos, 0.0, 1.0);
        return out;
      }
      @fragment
      fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }
    
    ''')
    
    rpass = Pass("rpass"); rpass.add_shader(shader)
    rpass.add_mesh_to_shader(mesh, shader)
    ```
    """
    def set_clear_color(self, color: Sequence[float]) -> None: ...
    """
    # Pass::set_clear_color(color: [f32; 4])
    
    Sets the clear color for this [Pass](https://fragmentcolor.org/api/core/pass).
    
    When the pass is configured to clear, the render target is cleared to the given RGBA color before drawing.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer, Pass, Shader
    
    renderer = Renderer()
    target = renderer.create_texture_target([64, 64])
    
    shader = Shader.default()
    rpass = Pass("solid background")
    rpass.add_shader(shader)
    
    rpass.set_clear_color([0.1, 0.2, 0.3, 1.0])
    
    renderer.render(rpass, target)
    ```
    """
    def set_viewport(self, viewport: 'Region') -> None: ...
    """
    # Pass::set_viewport(viewport: Region)
    
    Sets the viewport region for this [Pass](https://fragmentcolor.org/api/core/pass).
    
    The viewport restricts drawing to a rectangular area of the [Target](https://fragmentcolor.org/api/core/target).
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer, Pass, Shader, Region
    
    renderer = Renderer()
    target = renderer.create_texture_target([64, 64])
    
    shader = Shader.default()
    rpass = Pass("clipped")
    rpass.add_shader(shader)
    
    rpass.set_viewport(Region((0, 0), (32, 32)))
    
    renderer.render(rpass, target)
    ```
    """
    def set_compute_dispatch(self, x: int, y: int, z: int) -> None: ...
    """
    # Pass.set_compute_dispatch_py
    
    Hidden Python wrapper for Pass::set_compute_dispatch.
    
    Used for IDE hover via lsp_doc; not exported on the website.
    
    ```rust
    // hidden wrapper doc; no public example
    ```
    """
    def add_target(self, target: 'TextureTarget' | 'Texture') -> None: ...
    """
    # Pass::add_target(target)
    
    Attach a per-pass color render target. When set, this pass renders into the provided texture instead of the final Target.
    
    Use this to render intermediate results (e.g., a shadow map) that later passes can sample.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Renderer, Pass, TextureFormat
    
    r = Renderer()
    tex_target = r.create_texture_target([512, 512])
    
    p = Pass("shadow")
    p.add_target(tex_target)
    ```
    """
    def add_depth_target(self, target: 'TextureTarget' | 'Texture') -> None: ...
    """
    # Pass::add_depth_target
    
    Select a depth attachment for this pass.
    
    The target must be a stable texture created by the same Renderer with create_depth_texture().
    
    When a depth target is attached, the renderer will create a render pipeline with a depth-stencil
    matching the texture format (e.g., `Depth32Float`) of the created texture.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Renderer, Pass, Shader, Mesh
    
    renderer = Renderer()
    target = renderer.create_texture_target([64, 64])
    
    # Create a depth texture usable as a per-pass attachment
    depth = renderer.create_depth_texture([64, 64])
    
    mesh = Mesh()
    mesh.add_vertex([0.0, 0.0, 0.0])
    mesh.add_vertex([1.0, 0.0, 0.0])
    mesh.add_vertex([0.0, 1.0, 0.0])
    mesh.add_vertex([1.0, 1.0, 0.0])
    shader = Shader.from_mesh(mesh)
    rpass = Pass("scene"); rpass.add_shader(shader)
    
    # Attach depth texture to enable depth testing.
    # Pipeline will include a matching depth-stencil state
    rpass.add_depth_target(depth)
    
    # Render as usual
    renderer.render(rpass, target)
    ```
    """
    def is_compute(self) -> bool: ...
    """
    # Pass::is_compute
    
    Returns true if this Pass is a compute pass (has only compute shaders).
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader, Pass
    
    shader = Shader('''
    @compute @workgroup_size(1)
    fn cs_main() { }
    
    ''')
    rpass = Pass("p"); rpass.add_shader(shader)
    
    # Call the method
    is_compute = rpass.is_compute()
    ```
    """
    def require(self, deps: Renderable) -> None: ...
    """
    # Pass::require(deps)
    
    Declare that this pass depends on one or more other renderables (Pass, Shader, Frame, Mesh).
    All dependencies will render before this Pass.
    
    ## Return value
    
    - Ok(()) on success
    - Err(PassError::SelfDependency) if a pass requires itself
    - Err(PassError::DuplicateDependency(name)) if the dependency is already present
    - Err(PassError::DependencyCycle { via }) if adding the dependency would create a cycle
    
    ## Description
    
    `require` establishes a dependency: the given `dependencies` must render before `self`.
    
    This allows you to build DAG render graphs directly from passes.
    The graph is validated at build time and does not perform cycle checks at render time.
    
    - Dependencies are stored in insertion order.
    - Traversal is dependencies-first, then the current pass, with deduplication.
    - Creation order of passes does not matter.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Pass, Renderer
    renderer = Renderer()
    target = renderer.create_texture_target([100,100])
    color = Pass("color")
    blurx = Pass("blur_x")
    blurx.require(color); # color before blur_x
    blury = Pass("blur_y")
    blury.require(blurx); # blur_x before blur_y
    compose = Pass("compose")
    compose.require(color)
    compose.require(blury); # fan-in; color and blur_y before compose
    renderer.render(compose, target); # compose renders last
    ```
    """

class Frame:
    """
    # Frame
    
    The [Frame](https://fragmentcolor.org/api/core/frame) object is a collection of [Pass](https://fragmentcolor.org/api/core/pass) objects that are rendered to a [Target](https://fragmentcolor.org/api/core/target) by the [Renderer](https://fragmentcolor.org/api/core/renderer).
    
    It is used to render multiple passes to a single target, such as an opaque pass followed by a transparent pass.
    
    You need to inject the [Frame](https://fragmentcolor.org/api/core/frame) object into the [Renderer](https://fragmentcolor.org/api/core/renderer) to render it.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Shader, Pass, Renderer, Frame
    
    renderer = Renderer()
    target = renderer.create_texture_target([100, 100])
    
    pass1 = Pass("first")
    pass2 = Pass("second")
    
    frame = Frame()
    frame.add_pass(pass1)
    frame.add_pass(pass2)
    ```
    """
    def __init__(self) -> None: ...
    """
    # Frame::new()
    
    Creates a new [Frame](https://fragmentcolor.org/api/core/frame) object.
    
    A [Frame](https://fragmentcolor.org/api/core/frame) is an ordered collection of [Pass](https://fragmentcolor.org/api/core/pass) objects that will be rendered by the [Renderer](https://fragmentcolor.org/api/core/renderer) in sequence.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Frame
    
    frame = Frame()
    ```
    """
    def passes(self) -> Sequence['Pass']: ...
    def add_pass(self, pass_: 'Pass') -> None: ...
    """
    # Frame::add_pass(pass: Pass)
    
    Adds a [Pass](https://fragmentcolor.org/api/core/pass) to this [Frame](https://fragmentcolor.org/api/core/frame).
    
    Passes are rendered in the order they are added.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Frame, Pass
    
    pass1 = Pass("first")
    pass2 = Pass("second")
    
    frame = Frame()
    frame.add_pass(pass1)
    frame.add_pass(pass2)
    ```
    """

class Shader:
    """
    # Shader
    
    The [Shader](https://fragmentcolor.org/api/core/shader) object is the main building block in [FragmentColor](https://fragmentcolor.org).
    
    It takes a WGSL or GLSL shader source as input, parses it, validates it, and exposes the uniforms as keys.
    
    To draw your shader, you must use your [Shader](https://fragmentcolor.org/api/core/shader) instance as input to a [Renderer](https://fragmentcolor.org/api/core/renderer).
    
    You can compose [Shader](https://fragmentcolor.org/api/core/shader) instances into a [Pass](https://fragmentcolor.org/api/core/pass) object to create more complex rendering pipelines.
    
    You can also create renderings with multiple Render Passes by using multiple [Pass](https://fragmentcolor.org/api/core/pass) instances to a [Frame](https://fragmentcolor.org/api/core/frame) object.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Shader, Renderer
    
    shader = Shader('''
        @vertex
        fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
            var pos = array<vec2<f32>, 3>(
                vec2<f32>(-1.0, -1.0),
                vec2<f32>( 3.0, -1.0),
                vec2<f32>(-1.0,  3.0)
            );
            return vec4<f32>(pos[index], 0.0, 1.0);
        }
    
        @group(0) @binding(0)
        var<uniform> resolution: vec2<f32>;
    
        @fragment
        fn fs_main() -> @location(0) vec4<f32> {
            return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
        }
    
    ''')
    
    # Set the "resolution" uniform
    shader.set("resolution", [800.0, 600.0])
    res = shader.get("resolution")
    
    renderer = Renderer()
    target = renderer.create_texture_target([16, 16])
    renderer.render(shader, target)
    ```
    """
    def __init__(self, source: str) -> None: ...
    """
    # Shader::new(source: string)
    
    Creates a new [Shader](https://fragmentcolor.org/api/core/shader) instance from the given WGSL source string, file path, or URL.
    
    GLSL is also supported if you enable the `glsl` feature.
    Shadertoy-flavored GLSL is supported if the `shadertoy` feature is enabled.
    
    If the optional features are enabled, the constructor will try to automatically
    detect the shader type and parse it accordingly.
    
    If an exception occurs during parsing, the error message will indicate the location of the error.
    
    If the initial source validation passes, the shader is guaranteed to work on the GPU. All uniforms are initialized to their default zero values.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Shader
    
    shader = Shader('''
        @vertex
        fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
            var pos = array<vec2<f32>, 3>(
                vec2<f32>(-1.0, -1.0),
                vec2<f32>( 3.0, -1.0),
                vec2<f32>(-1.0,  3.0)
            );
            return vec4<f32>(pos[index], 0.0, 1.0);
        }
    
        @group(0) @binding(0)
        var<uniform> resolution: vec2<f32>;
    
        @fragment
        fn fs_main() -> @location(0) vec4<f32> {
            return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
        }
    
    ''')
    ```
    """
    def set(self, key: str, value: Any) -> None: ...
    """
    # Shader::set(key: string, value: any)
    
    Sets the value of the uniform identified by the given key.
    
    If the key does not exist or the value format is incorrect, the `set` method throws an exception. The shader remains valid, and if the exception is caught, the shader can still be used with the renderer.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Renderer, Shader
    r = Renderer()
    shader = Shader('''
    @group(0) @binding(0) var<uniform> resolution: vec2<f32>;
    
    struct VOut { @builtin(position) pos: vec4<f32> };
    @vertex fn vs_main(@builtin(vertex_index) i: u32) -> VOut {
      var p = array<vec2<f32>, 3>(vec2<f32>(-1.,-1.), vec2<f32>(3.,-1.), vec2<f32>(-1.,3.));
      var out: VOut;
      out.pos = vec4<f32>(p[i], 0., 1.);
      return out;
    }
    @fragment fn main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }
    
    ''')
    
    # Set scalars/vectors on declared uniforms
    shader.set("resolution", [800.0, 600.0])
    ```
    """
    def get(self, key: str) -> Any: ...
    """
    # Shader::get(key: string) -> any
    
    Returns the current value of the uniform identified by the given key.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader
    
    shader = Shader.default()
    shader.set("resolution", [800.0, 600.0])
    res = shader.get("resolution")
    ```
    """
    def list_uniforms(self) -> list[str]: ...
    """
    # Shader::list_uniforms() -> [string]
    
    Returns a list of all uniform names in the [Shader](https://fragmentcolor.org/api/core/shader) (excluding struct fields).
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader
    
    shader = Shader.default()
    list = shader.list_uniforms()
    ```
    """
    def list_keys(self) -> list[str]: ...
    """
    # Shader::list_keys() -> [string]
    
    Returns a list of all keys in the [Shader](https://fragmentcolor.org/api/core/shader), including uniform names and struct fields using the dot notation.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Shader
    
    shader = Shader.default()
    keys = shader.list_keys()
    ```
    """
    def add_mesh(self, mesh: 'Mesh') -> None: ...
    """
    # Shader::add_mesh
    
    Attach a Mesh to this Shader. The Renderer will draw all meshes attached to it (one draw call per mesh, same pipeline).
    
    This method now validates that the mesh's vertex/instance layout is compatible with the shader's @location inputs and returns Result<(), ShaderError>.
    
    - On success, the mesh is attached and will be drawn when this shader is rendered.
    - On mismatch (missing attribute or type mismatch), returns an error and does not attach.
    
    ## See also
    
    Use Shader::validate_mesh for performing a compatibility check without attaching.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader, Mesh
    
    shader = Shader('''
      @vertex fn vs_main(@location(0) pos: vec3<f32>) -> @builtin(position) vec4<f32> {
        return vec4<f32>(pos, 1.0);
      }
      @fragment fn fs_main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }
    
    ''')
    
    mesh = Mesh()
    mesh.add_vertex([0.0, 0.0, 0.0])
    
    # Attach mesh to this shader (errors if incompatible)
    shader.add_mesh(mesh)
    
    # Renderer will draw the mesh when rendering this pass.
    # Each Shader represents a RenderPipeline or ComputePipeline
    # in the GPU. Adding multiple meshes to it will draw all meshes
    # and all its instances in the same Pipeline.
    ```
    """
    def remove_mesh(self, mesh: 'Mesh') -> None: ...
    """
    # Shader::remove_mesh
    
    Remove a single Mesh previously attached to this Shader.
    If the Mesh is attached multiple times, removes the first match.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader, Mesh
    
    shader = Shader('''
      struct VOut { @builtin(position) pos: vec4<f32> };
      @vertex
      fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
        var out: VOut;
        out.pos = vec4<f32>(pos, 0.0, 1.0);
        return out;
      }
      @fragment
      fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }
    
    ''')
    
    mesh = Mesh()
    mesh.add_vertex([0.0, 0.0])
    shader.add_mesh(mesh)
    
    # Detach the mesh
    shader.remove_mesh(mesh)
    ```
    """
    def remove_meshes(self, list_: Sequence['Mesh']) -> None: ...
    """
    # Shader::remove_meshes
    
    Remove multiple meshes from this Shader.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader, Mesh
    
    shader = Shader('''
      struct VOut { @builtin(position) pos: vec4<f32> };
      @vertex
      fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
        var out: VOut;
        out.pos = vec4<f32>(pos, 0.0, 1.0);
        return out;
      }
      @fragment
      fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }
    
    ''')
    
    m1 = Mesh()
    m1.add_vertex([0.0, 0.0])
    m2 = Mesh()
    m2.add_vertex([0.5, 0.0])
    
    shader.add_mesh(m1)
    shader.add_mesh(m2)
    
    shader.remove_meshes([m1, m2])
    ```
    """
    def clear_meshes(self) -> None: ...
    """
    # Shader::clear_meshes
    
    Remove all meshes attached to this Shader.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader, Mesh
    
    shader = Shader('''
      struct VOut { @builtin(position) pos: vec4<f32> };
      @vertex
      fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
        var out: VOut;
        out.pos = vec4<f32>(pos, 0.0, 1.0);
        return out;
      }
      @fragment
      fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }
    
    ''')
    
    mesh = Mesh()
    mesh.add_vertex([0.0, 0.0])
    shader.add_mesh(mesh)
    
    # Clear all
    shader.clear_meshes()
    ```
    """
    def validate_mesh(self, mesh: 'Mesh') -> None: ...
    """
    # Shader::validate_mesh
    
    Validate that a Mesh is compatible with this Shader's vertex inputs.
    
    - Checks presence and type for all @location(...) inputs of the vertex entry point.
    - Matches attributes in the following order:
      1) Instance attributes by explicit @location index (if the mesh has instances)
      2) Vertex attributes by explicit @location index (position is assumed at @location(0))
      3) Fallback by name (tries instance first, then vertex)
    - Returns Ok(()) when all inputs are matched with a compatible wgpu::VertexFormat; returns an error otherwise.
    
    ## Notes
    
    - This method is called automatically when adding a Mesh to a Shader or Pass, so you usually don't need to call it manually.
    - If the Shader has no @location inputs (fullscreen/builtin-only), attaching a Mesh is rejected.
    - This method does not allocate GPU buffers; it inspects CPU-side vertex/instance data only.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader, Pass, Mesh
    
    shader = Shader('''
    struct VOut { @builtin(position) pos: vec4<f32> };
    @vertex fn vs_main(@location(0) pos: vec3<f32>) -> VOut {
      var out: VOut;
      out.pos = vec4<f32>(pos, 1.0);
      return out;
    }
    @fragment fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }
    
    ''')
    rpass = Pass("p"); rpass.add_shader(shader)
    
    mesh = Mesh()
    mesh.add_vertices([
      [-0.5, -0.5, 0.0],
      [ 0.5, -0.5, 0.0],
      [ 0.0,  0.5, 0.0],
    ])
    
    shader.validate_mesh(mesh); # Ok
    rpass.add_mesh(mesh)
    ```
    """
    def is_compute(self) -> bool: ...
    """
    # Shader::is_compute
    
    Returns true if this Shader is a compute shader (has a compute entry point).
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader
    
    shader = Shader('''
    @compute @workgroup_size(1)
    fn cs_main() { }
    
    ''')
    
    # Call the method
    is_compute = shader.is_compute()
    ```
    """
    def passes(self) -> Sequence['Pass']: ...
    @staticmethod
    def default() -> 'Shader': ...
    """
    # Shader::default()
    
    Creates a new [Shader](https://fragmentcolor.org/api/core/shader) from the default shader source.
    
    Useful for examples and quick demos. Includes a "**resolution**" uniform.
    
    ```wgsl
    struct VertexOutput {
        @builtin(position) coords: vec4<f32>,
    }
    
    @group(0) @binding(0)
    var<uniform> resolution: vec2<f32>;
    
    @vertex
    fn vs_main(@builtin(vertex_index) in_vertex_index: u32) -> VertexOutput {
        let x = f32(i32(in_vertex_index) - 1);
        let y = f32(i32(in_vertex_index & 1u) * 2 - 1);
        return VertexOutput(vec4<f32>(x, y, 0.0, 1.0));
    }
    
    @fragment
    fn fs_main(pixel: VertexOutput) -> @location(0) vec4<f32> {
        let _dummy = resolution.x + resolution.y * 0.0;
        return vec4<f32>(1.0, 0.0, 0.0, 1.0);
    }
    ```
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Shader
    
    shader = Shader.default()
    
    # The default shader includes a "resolution" uniform
    shader.set("resolution", [800.0, 600.0])
    res = shader.get("resolution")
    ```
    """
    @staticmethod
    def from_vertex(v: 'Vertex') -> 'Shader': ...
    """
    # Shader::from_vertex
    
    Build a basic WGSL shader source from a single Vertex layout.
    
    This inspects the vertex position dimensionality (2D or 3D) and optional properties.
    It generates a minimal vertex shader that consumes `@location(0)` position and a fragment shader that returns a flat color by default.
    If a `color: vec4<f32>` property exists, it is passed through to the fragment stage and used as output.
    
    This is intended as a fallback and for quick debugging. Canonical usage is the opposite: write your own shader and then build Meshes that match it.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Shader, Vertex
    
    vertex = Vertex([0.0, 0.0, 0.0])
    shader = Shader.from_vertex(vertex)
    ```
    """
    @staticmethod
    def from_mesh(mesh: 'Mesh') -> 'Shader': ...
    """
    # Shader::from_mesh
    
    Build a basic WGSL shader source from the first vertex in a Mesh.
    
    The resulting shader automatically adds the provided Mesh to its internal list of Meshes to render,
    so the user doesn't need to call `Shader::add_mesh` manually.
    
    This function uses the **first Vertex** to infer position dimensionality and optional properties.
    
    It generates a minimal vertex shader that consumes `@location(0)` position and a fragment shader that returns a flat color by default. If a `color: vec4<f32>` property exists, it is passed through to the fragment stage and used as output.
    
    ## Empty Mesh Handling
    
    If the Mesh has no vertices, a default shader is returned and a warning is logged.
    Because the default shader does not take any vertex inputs, it is compatible with any Mesh.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Mesh, Shader
    
    mesh = Mesh()
    mesh.add_vertex([0.0, 0.0, 0.0])
    shader = Shader.from_mesh(mesh)
    ```
    """

class TextureTarget:
    """
    # TextureTarget
    
    The [TextureTarget](https://fragmentcolor.org/api/targets/texturetarget) is an offscreen [Target](https://fragmentcolor.org/api/core/target) backed by a GPU texture.
    
    Use it for headless rendering, tests, server-side image generation, or CI.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer, Shader
    
    renderer = Renderer()
    target = renderer.create_texture_target([64, 64])
    
    shader = Shader.default()
    renderer.render(shader, target)
    
    image = target.get_image()
    ```
    """
    @property
    def size(self) -> Size: ...
    """
    # TextureTarget::size() -> Size { width: u32, height: u32, depth: u32 }
    
    Returns the size of the [TextureTarget](https://fragmentcolor.org/api/targets/texturetarget) in pixels.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer
    
    renderer = Renderer()
    target = renderer.create_texture_target([64, 64])
    size = target.size
    width = size.width
    height = size.height
    depth = size.depth
    ```
    """
    def resize(self, size: PySize) -> None: ...
    """
    # TextureTarget::resize(size: [u32; 2] | (u32, u32))
    
    Resizes the [TextureTarget](https://fragmentcolor.org/api/targets/texturetarget) to the given width and height.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer
    
    renderer = Renderer()
    target = renderer.create_texture_target([64, 64])
    
    target.resize([128, 32])
    ```
    """
    def get_current_frame(self) -> 'TargetFrame': ...
    def get_image(self) -> 'npt.NDArray[numpy.uint8]': ...
    """
    # TextureTarget::get_image()
    
    Returns the current contents of the target as a byte array in RGBA8 format.
    
    
    
    Example (Python):
    
    ```python
    from rendercanvas.auto import RenderCanvas, loop
    from fragmentcolor import Renderer, Shader
    
    
    renderer = Renderer()
    target = renderer.create_texture_target([16, 16])
    renderer.render(Shader(""), target)
    
    image = target.get_image()
    ```
    """

class TargetFrame:
    """
    # Target::get_current_frame() -> TargetFrame
    
    Returns a frame wrapper containing the texture view to render and the target format.
    
    Most users do not need to call this directly; the [Renderer](https://fragmentcolor.org/api/core/renderer) uses it internally.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer
    
    renderer = Renderer()
    target = renderer.create_texture_target([16, 16])
    frame = target.get_current_frame()
    format = frame.format()
    ```
    """
    def format(self) -> str: ...
    """
    # Target::get_current_frame() -> TargetFrame
    
    Returns a frame wrapper containing the texture view to render and the target format.
    
    Most users do not need to call this directly; the [Renderer](https://fragmentcolor.org/api/core/renderer) uses it internally.
    
    
    
    Example (Python):
    
    ```python
    
    from fragmentcolor import Renderer
    
    renderer = Renderer()
    target = renderer.create_texture_target([16, 16])
    frame = target.get_current_frame()
    format = frame.format()
    ```
    """
    def present(self) -> None: ...

class RenderCanvasTarget:
    """
    # RenderCanvasTarget
    
    [RenderCanvasTarget](https://fragmentcolor.org/api/hidden/platforms/python/rendercanvastarget) is a Python-specific wrapper around [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget).
    
    It adapts [FragmentColor](https://fragmentcolor.org) to work with the RenderCanvas Python project, forwarding all rendering to an internal [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget). See [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget) for the full [Target](https://fragmentcolor.org/api/core/target) behavior and semantics.
    
    - Canonical object: [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget)
    - [Target](https://fragmentcolor.org/api/core/target) trait docs: [Target](https://fragmentcolor.org/api/core/target)
    
    
    
    Example (Python):
    
    ```python
    # Python-only wrapper around WindowTarget.
    # No direct Rust example is applicable here.
    ```
    """
    def __init__(self, canvas: Any, present_methods: Any) -> None: ...
    """
    # RenderCanvasTarget::new()
    
    Creates a new [RenderCanvasTarget](https://fragmentcolor.org/api/hidden/platforms/python/rendercanvastarget) wrapper, typically invoked by RenderCanvas when requesting a "fragmentcolor" context.
    
    The object wraps a platform [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget) internally and exposes the [Target](https://fragmentcolor.org/api/core/target) interface in Python.
    
    
    
    Example (Python):
    
    ```python
    # Python-only wrapper around WindowTarget.
    # No direct Rust example is applicable here.
    ```
    """
    def is_ready(self) -> bool: ...
    """
    # RenderCanvasTarget::is_ready() -> bool
    
    Returns True if the underlying [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget) has been initialized.
    
    This becomes True after the renderer creates and binds a platform surface to the wrapper.
    
    
    
    Example (Python):
    
    ```python
    # Python-only wrapper API.
    # No direct Rust example is applicable here.
    ```
    """
    @property
    def canvas(self) -> Any: ...
    """
    # RenderCanvasTarget::canvas() -> RenderCanvas
    
    Returns the underlying RenderCanvas object used to integrate with the windowing system.
    
    
    
    Example (Python):
    
    ```python
    # Python-only wrapper API.
    # No direct Rust example is applicable here.
    ```
    """
    def present(self) -> dict[str, Any]: ...
    """
    # RenderCanvasTarget::present() -> dict
    
    Presents the current frame to the screen via the underlying [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget).
    
    Returns a dict containing a presentation method (e.g., "screen") and optional error information on failure.
    
    
    
    Example (Python):
    
    ```python
    # Python-only wrapper API.
    # No direct Rust example is applicable here.
    ```
    """
    def size(self) -> Size: ...
    """
    # RenderCanvasTarget::size() -> [u32, u32]
    
    Returns the current size in pixels of the backing [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget).
    
    
    
    Example (Python):
    
    ```python
    # Python-only wrapper API.
    # No direct Rust example is applicable here.
    ```
    """
    def resize(self, size: PySize) -> None: ...
    """
    # RenderCanvasTarget::resize(size: [u32, u32] | (u32, u32) | { width, height })
    
    Resizes the underlying [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget) to the given dimensions.
    
    
    
    Example (Python):
    
    ```python
    # Python-only wrapper API.
    # No direct Rust example is applicable here.
    ```
    """

class RenderCanvasFrame:
    """
    # RenderCanvasTarget::present() -> dict
    
    Presents the current frame to the screen via the underlying [WindowTarget](https://fragmentcolor.org/api/targets/windowtarget).
    
    Returns a dict containing a presentation method (e.g., "screen") and optional error information on failure.
    
    
    
    Example (Python):
    
    ```python
    # Python-only wrapper API.
    # No direct Rust example is applicable here.
    ```
    """
    def format(self) -> str: ...
    def present(self) -> None: ...

class Renderer:
    """
    # Renderer
    
    The [Renderer](https://fragmentcolor.org/api/core/renderer) is the main entry point for
    [FragmentColor](https://fragmentcolor.org) and normally the first object you create.
    
    It is used to render
    [Shaders](https://fragmentcolor.org/api/core/shader),
    [Passes](https://fragmentcolor.org/api/core/pass), and
    [Frames](https://fragmentcolor.org/api/core/frame)
    to a [Target](https://fragmentcolor.org/api/core/target) (canvas, window, or texture).
    
    The [Renderer](https://fragmentcolor.org/api/core/renderer) internals are lazily initialized
    when the user creates a [Target](https://fragmentcolor.org/api/core/target).
    
    See the constructor [Renderer::new()](https://fragmentcolor.org/api/core/renderer/#renderernew)
    description below for details.
    
    
    
    Example (Python):
    
    ```python
    from rendercanvas.auto import RenderCanvas, loop
    
    from fragmentcolor import Shader, Renderer
    
    renderer = Renderer()
    
    # Use your platform's windowing system to create a window
    canvas = RenderCanvas(size=(800, 600))
    
    # Create a Target from it
    target = renderer.create_target(canvas)
    texture_target = renderer.create_texture_target([16, 16])
    
    # RENDERING
    renderer.render(Shader(""), texture_target)
    
    # That's it. Welcome to FragmentColor!
    ```
    """
    def __init__(self) -> None: ...
    """
    # Renderer.new_py
    
    Platform-specific constructor for Python.
    Hidden from public website, available for IDE hover via lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    def create_target(self, rendercanvas: Any) -> RenderCanvasTarget: ...
    """
    # Renderer.create_target_py
    
    Platform-specific method for Python.
    Hidden from public website, available for IDE hover via lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    def create_texture_target(self, size: PySize) -> TextureTarget: ...
    """
    # Renderer.create_texture_target_py
    
    Platform-specific method for Python.
    Hidden from public website, available for IDE hover via lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """

    @overload
    def create_texture(self, input: bytes | bytearray | Sequence[int]) -> Texture: ...
    @overload
    def create_texture(self, input: str) -> Texture: ...
    @overload
    def create_texture(self, input: NDArrayU8) -> Texture: ...
    """
    # Renderer::create_texture (Python)
    
    Hidden helper for Python binding documentation coverage.
    
    
    
    Example (Python):
    
    ```python
    from fragmentcolor import Renderer
    # Python binding: renderer.create_texture(input)
    # See main create_texture docs for examples.
    ```
    """
    @overload
    def create_texture_with_size(self, input: bytes | bytearray | Sequence[int], size: PySize) -> Texture: ...
    @overload
    def create_texture_with_size(self, input: str, size: PySize) -> Texture: ...
    @overload
    def create_texture_with_size(self, input: NDArrayU8, size: PySize) -> Texture: ...
    """
    # Renderer.create_depth_texture_py
    
    Python wrapper for Renderer::create_depth_texture.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden draft; no public example
    ```
    """
    @overload
    def create_texture_with_format(self, input: bytes | bytearray | Sequence[int], format: TextureFormat) -> Texture: ...
    @overload
    def create_texture_with_format(self, input: str, format: TextureFormat) -> Texture: ...
    @overload
    def create_texture_with_format(self, input: NDArrayU8, format: TextureFormat) -> Texture: ...
    """
    # Renderer.create_depth_texture_py
    
    Python wrapper for Renderer::create_depth_texture.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden draft; no public example
    ```
    """
    def create_texture_with(self, input: bytes | bytearray | Sequence[int] | str | NDArrayU8, size: PySize | None = None) -> Texture: ...
    """
    # Renderer.create_depth_texture_py
    
    Python wrapper for Renderer::create_depth_texture.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden draft; no public example
    ```
    """
    def render(self, renderable: Renderable, target: RenderCanvasTarget | TextureTarget) -> None: ...
    """
    # Renderer.render_py
    
    Platform-specific method for Python.
    Hidden from public website, available for IDE hover via lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden file; no public example
    ```
    """
    def create_depth_texture(self, size: PySize) -> Texture: ...
    """
    # Renderer.create_depth_texture_py
    
    Python wrapper for Renderer::create_depth_texture.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden draft; no public example
    ```
    """
    def create_storage_texture(self, size: PySize, format: TextureFormat, usage_bits: int | None = None) -> Texture: ...
    """
    # Renderer.create_depth_texture_py
    
    Python wrapper for Renderer::create_depth_texture.
    Hidden from public website; used for IDE hover with lsp_doc.
    
    
    
    Example (Python):
    
    ```python
    # hidden draft; no public example
    ```
    """

def rendercanvas_context_hook(canvas: Any, present_methods: Any) -> RenderCanvasTarget: ...

