//! Embedded shader registry — a feature-gated lookup from registry slugs
//! (e.g. `"postfx/vignette"`) to the shader source compiled into the binary.
//!
//! The `lookup` function below is auto-generated by `scripts/embedded_shaders.rs`
//! from the contents of `docs/website/public/shaders/`. Each match arm is
//! gated on `shaders-<category>`, so only the categories the consumer opts
//! into are baked into the binary; everything else falls through to the
//! URL-fetch path in `input::fetch_url`.

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/embedded_shaders.rs"
));
