[package]
name = "plrender-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
plrender = { path = "../plrender" }
plrender-macros = { path = "../plrender-macros" }
