// AUTO-GENERATED by build.rs (scripts/website.rs). DO NOT EDIT.
//
// Compile-only aggregator for every transpiled Swift example under
// `platforms/swift/examples/`. Each function below embeds the body
// of one example so the compiler type-checks it. Functions are
// never invoked at runtime — wiring up GPU-backed runtime
// execution is a follow-up task.
//
// A failure here means either:
//  (a) the source `docs/api/**.md` example uses a Rust API that
//      `scripts/convert.rs::to_swift` cannot map, or
//  (b) the example references an item that uniffi does not
//      export to Swift.
// Fix the source — this file is regenerated on every cargo build.

import Foundation
import FragmentColor

@available(iOS 16.0, *)
private enum _GeneratedExamples {
    static func _example_core_pass_Pass() async throws {


        let renderer = Renderer()
        // iOS: window/canvas provided by CAMetalLayer at runtime
        let target = try await renderer.createTextureTarget([800, 600])
        let shader = Shader.default()

        let pass = Pass("First Pass")
        pass.addShader(shader)

        let pass2 = Pass("Second Pass")
        pass2.addShader(shader)

        // standalone
        try renderer.render(pass, target)

        // vector of passes rendered in order (any iterable of Pass is renderable)
        try renderer.render([pass, pass2], target)
    }

    static func _example_core_pass_add_depth_target() async throws {

        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        // Create a depth texture usable as a per-pass attachment
        let depth = try await renderer.createDepthTexture([64, 64])

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0, 0.0])
        try mesh.addVertex([1.0, 0.0, 0.0])
        try mesh.addVertex([0.0, 1.0, 0.0])
        try mesh.addVertex([1.0, 1.0, 0.0])
        let shader = Shader.fromMesh(mesh)
        let pass = Pass("scene"); pass.addShader(shader)

        // Attach depth texture to enable depth testing.
        // Pipeline will include a matching depth-stencil state
        try pass.addDepthTarget(depth)

        // Render as usual
        try renderer.render(pass, target)
    }

    static func _example_core_pass_add_mesh() async throws {

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0])

        let shader = try Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        let pass = Pass("pass"); pass.addShader(shader)

        try pass.addMesh(mesh)
    }

    static func _example_core_pass_add_mesh_to_shader() async throws {

        let mesh = Mesh()
        try mesh.addVertex(try Vertex([0.0, 0.0]))
        let shader = try Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        let pass = Pass("pass"); pass.addShader(shader)
        try pass.addMeshToShader(mesh, shader)
    }

    static func _example_core_pass_add_shader() async throws {

        let shader = Shader.default()
        let pass = Pass("p")
        pass.addShader(shader)
    }

    static func _example_core_pass_add_target() async throws {

        let r = Renderer()
        let tex_target = try await r.createTextureTarget([512, 512])

        let p = Pass("shadow")
        try p.addTarget(tex_target)
    }

    static func _example_core_pass_compute() async throws {

        let cs = try! Shader("@compute @workgroup_size(8,8,1) fn cs_main() {}")
        let pass = Pass("compute"); pass.addShader(cs)
    }

    static func _example_core_pass_from_shader() async throws {

        let shader = Shader.default()
        let pass = Pass("single"); pass.addShader(shader)
    }

    static func _example_core_pass_get_input() async throws {

        let pass = Pass("example")
        let input = pass.getInput()
    }

    static func _example_core_pass_is_compute() async throws {

        let shader = try Shader("""
        @compute @workgroup_size(1)
        fn cs_main() { }

        """)
        let pass = Pass("p"); pass.addShader(shader)

        // Call the method
        let is_compute = pass.isCompute()
    }

    static func _example_core_pass_load_previous() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let shader = Shader.default()
        let pass = Pass("blend with previous")
        pass.addShader(shader)
        pass.loadPrevious()

        try renderer.render(pass, target)
    }

    static func _example_core_pass_new() async throws {

        let pass = Pass("first pass")
    }

    static func _example_core_pass_require() async throws {
        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([100,100])
        let color = Pass("color")
        let blurx = Pass("blur_x")
        try blurx.require(color); // color before blur_x
        let blury = Pass("blur_y")
        try blury.require(blurx); // blur_x before blur_y
        let compose = Pass("compose")
        try compose.require(color)
        try compose.require(blury); // fan-in; color and blur_y before compose
        try renderer.render(compose, target); // compose renders last
    }

    static func _example_core_pass_set_clear_color() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let shader = Shader.default()
        let pass = Pass("solid background")
        pass.addShader(shader)

        try pass.setClearColor([0.1, 0.2, 0.3, 1.0])

        try renderer.render(pass, target)
    }

    static func _example_core_pass_set_compute_dispatch() async throws {
        let cs = try! Shader("@compute @workgroup_size(8,8,1) fn cs_main() {}")
        let pass = Pass("compute"); pass.addShader(cs)
        pass.setComputeDispatch(64, 64, 1)
    }

    static func _example_core_pass_set_viewport() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let shader = Shader.default()
        let pass = Pass("clipped")
        pass.addShader(shader)

        pass.setViewport([(0, 0), (32, 32)])

        try renderer.render(pass, target)
    }

    static func _example_core_renderer_Renderer() async throws {


        let renderer = Renderer()

        // Use your platform's windowing system to create a window
        // iOS: window/canvas provided by CAMetalLayer at runtime

        // Create a Target from it
        let target = try await renderer.createTextureTarget([800, 600])
        let texture_target = try await renderer.createTextureTarget([16, 16])

        // RENDERING
        try renderer.render(Shader(""), texture_target)

        // That's it. Welcome to FragmentColor!
    }

    static func _example_core_renderer_create_depth_texture() async throws {
        let r = Renderer()
        let depth = try await r.createDepthTexture([800, 600])
    }

    static func _example_core_renderer_create_external_texture() async throws {
        // Once supported:
        //   let renderer = Renderer()
        //   let pixelBuffer: CVPixelBuffer = /* from AVPlayerItemVideoOutput */
        //   let ptr = UInt64(UInt(bitPattern: Unmanaged.passUnretained(pixelBuffer).toOpaque()))
        //   let handle = try renderer.createExternalTexture(sourcePtr: ptr)
    }

    static func _example_core_renderer_create_storage_texture() async throws {

        let r = Renderer()
        // Empty storage texture â same single create_storage_texture entry.
        let tex = try await r.createStorageTexture(([64, 64], TextureFormat.rgba))

        // Pre-seeded with bytes â same method, three-tuple form.
        let pixels = Array(repeating: 0, count: 64 * 64 * 4)
        let tex2 = try await r.createStorageTexture(([64, 64], TextureFormat.rgba, pixels))
    }

    static func _example_core_renderer_create_target() async throws {


        let renderer = Renderer()

        // Use your platform's windowing system to create a window.
        // iOS: window/canvas provided by CAMetalLayer at runtime

        let target = try await renderer.createTextureTarget([800, 600])
    }

    static func _example_core_renderer_create_texture() async throws {
        let renderer = Renderer()
        // Encoded image bytes (PNG / JPEG / etc.) â single tuple, no extra method.
        let image = "/healthcheck/public/favicon.png"
        let tex = try await renderer.createTexture(image)
    }

    static func _example_core_renderer_create_texture_target() async throws {

        let renderer = Renderer()

        // Create an offscreen texture target with a size of 64x64 pixels.
        let target = try await renderer.createTextureTarget([64, 64])

        try renderer.render(Shader(""), target)

        // get the rendered image
        let image = target.getImage()
    }

    static func _example_core_renderer_new() async throws {


        let renderer = Renderer()
        let texture_target = try await renderer.createTextureTarget([16, 16])
    }

    static func _example_core_renderer_read_texture() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 64], TextureFormat.rgba))
        try texture.write(Array(repeating: 0, count: 64 * 64 * 4))

        let bytes = try renderer.readTexture(texture.id())
    }

    static func _example_core_renderer_read_texture_async() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 64], TextureFormat.rgba))
        try texture.write(Array(repeating: 0, count: 64 * 64 * 4))

        let bytes = try await renderer.readTextureAsync(texture.id())
    }

    static func _example_core_renderer_render() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([10, 10])
        let shader = Shader.default()

        try renderer.render(shader, target)
    }

    static func _example_core_renderer_unregister_texture() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([16, 16], TextureFormat.rgba))
        let id = texture.id()

        try renderer.unregisterTexture(id)
    }

    static func _example_core_renderer_wait_idle() async throws {

        let r = Renderer()
        let target = try await r.createTextureTarget([8, 8])
        let shader = Shader.default()
        try r.render(shader, target)
        try r.waitIdle()
        let _bytes = target.getImage()
    }

    static func _example_core_shader_Shader() async throws {


        let shader = try Shader("""
            @vertex
            fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
                var pos = array<vec2<f32>, 3>(
                    vec2<f32>(-1.0, -1.0),
                    vec2<f32>( 3.0, -1.0),
                    vec2<f32>(-1.0,  3.0)
                )
                return vec4<f32>(pos[index], 0.0, 1.0)
            }

            @group(0) @binding(0)
            var<uniform> resolution: vec2<f32>

            @fragment
            fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
            }

        """)

        // Set the "resolution" uniform
        try shader.set("resolution", [800.0, 600.0])
        let res = try shader.get("resolution")

        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([16, 16])
        try renderer.render(shader, target)
    }

    static func _example_core_shader_add_mesh() async throws {

        let shader = try Shader("""
          @vertex fn vs_main(@location(0) pos: vec3<f32>) -> @builtin(position) vec4<f32> {
            return vec4<f32>(pos, 1.0)
          }
          @fragment fn fs_main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0, 0.0])

        // Attach mesh to this shader (errors if incompatible)
        try shader.addMesh(mesh)

        // Renderer will draw the mesh when rendering this pass.
        // Each Shader represents a RenderPipeline or ComputePipeline
        // in the GPU. Adding multiple meshes to it will draw all meshes
        // and all its instances in the same Pipeline.
    }

    static func _example_core_shader_clear_meshes() async throws {

        let shader = try Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0])
        try shader.addMesh(mesh)

        // Clear all
        shader.clearMeshes()
    }

    static func _example_core_shader_from_mesh() async throws {

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0, 0.0])
        let shader = Shader.fromMesh(mesh)
    }

    static func _example_core_shader_from_vertex() async throws {

        let vertex = try Vertex([0.0, 0.0, 0.0])
        let shader = Shader.fromVertex(vertex)
    }

    static func _example_core_shader_get() async throws {

        let shader = Shader.default()
        try shader.set("resolution", [800.0, 600.0])
        let res = try shader.get("resolution")
    }

    static func _example_core_shader_is_compute() async throws {

        let shader = try Shader("""
        @compute @workgroup_size(1)
        fn cs_main() { }

        """)

        // Call the method
        let is_compute = shader.isCompute()
    }

    static func _example_core_shader_list_keys() async throws {


        let shader = Shader.default()
        let keys = shader.listKeys()
    }

    static func _example_core_shader_list_uniforms() async throws {

        let shader = Shader.default()
        let list = shader.listUniforms()
    }

    static func _example_core_shader_new() async throws {

        let shader = try Shader("""
            @vertex
            fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
                var pos = array<vec2<f32>, 3>(
                    vec2<f32>(-1.0, -1.0),
                    vec2<f32>( 3.0, -1.0),
                    vec2<f32>(-1.0,  3.0)
                )
                return vec4<f32>(pos[index], 0.0, 1.0)
            }

            @group(0) @binding(0)
            var<uniform> resolution: vec2<f32>

            @fragment
            fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
            }

        """)


        let main = """
            @vertex fn vs(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
                let p = array<vec2<f32>,3>(vec2f(-1.,-1.), vec2f(3.,-1.), vec2f(-1.,3.))
                return vec4<f32>(p[i], 0.0, 1.0)
            }

            @fragment fn fs(@builtin(position) pos: vec4<f32>) -> @location(0) vec4<f32> {
                let d = circle(pos.xy - vec2<f32>(400.0, 300.0), 100.0)
                let n = simplex2(pos.xy * 0.01)
                return vec4<f32>(vec3<f32>(step(0.0, d) + n * 0.1), 1.0)
            }

        """

        let shader2 = try Shader.new([
            "sdf2d/circle",      // pure function: fn circle(p: vec2<f32>, r: f32) -> f32
            "noise/simplex2",    // pure function: fn simplex2(v: vec2<f32>) -> f32
            main,
        ])
    }

    static func _example_core_shader_remove_mesh() async throws {

        let shader = try Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0])
        try shader.addMesh(mesh)

        // Detach the mesh
        try shader.removeMesh(mesh)
    }

    static func _example_core_shader_remove_meshes() async throws {

        let shader = try Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        let m1 = Mesh()
        try m1.addVertex([0.0, 0.0])
        let m2 = Mesh()
        try m2.addVertex([0.5, 0.0])

        try shader.addMesh(m1)
        try shader.addMesh(m2)

        shader.removeMeshes([m1, m2])
    }

    static func _example_core_shader_set() async throws {
        let r = Renderer()
        let shader = try Shader("""
        @group(0) @binding(0) var<uniform> resolution: vec2<f32>

        struct VOut { @builtin(position) pos: vec4<f32> }
        @vertex fn vs_main(@builtin(vertex_index) i: u32) -> VOut {
          var p = array<vec2<f32>, 3>(vec2<f32>(-1.,-1.), vec2<f32>(3.,-1.), vec2<f32>(-1.,3.))
          var out: VOut
          out.pos = vec4<f32>(p[i], 0., 1.)
          return out
        }
        @fragment fn main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        // Set scalars/vectors on declared uniforms
        try shader.set("resolution", [800.0, 600.0])
    }

    static func _example_core_shader_set_registry() async throws {


        // Point at your own mirror of the registry
        Shader.setRegistry("https://cdn.example.com/shaders/")

        // Now the slug "sdf2d/circle" resolves to https://cdn.example.com/shaders/sdf2d/circle.wgsl
        // (Skipping the actual fetch in this doctest)
    }

    static func _example_core_shader_validate_mesh() async throws {

        let shader = try Shader("""
        struct VOut { @builtin(position) pos: vec4<f32> }
        @vertex fn vs_main(@location(0) pos: vec3<f32>) -> VOut {
          var out: VOut
          out.pos = vec4<f32>(pos, 1.0)
          return out
        }
        @fragment fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)
        let pass = Pass("p"); pass.addShader(shader)

        let mesh = Mesh()
        try mesh.addVertices([
          [-0.5, -0.5, 0.0],
          [ 0.5, -0.5, 0.0],
          [ 0.0,  0.5, 0.0],
        ])

        try shader.validateMesh(mesh); // Ok
        try pass.addMesh(mesh)
    }

    static func _example_core_texture_Texture() async throws {

        let renderer = Renderer()
        let shader = try Shader("""
        @group(0) @binding(0) var my_texture: texture_2d<f32>
        @group(0) @binding(1) var my_sampler: sampler
        @vertex fn vs_main(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
          let p = array<vec2<f32>,3>(vec2f(-1.,-1.), vec2f(3.,-1.), vec2f(-1.,3.))
          return vec4f(p[i], 0., 1.)
        }
        @fragment fn main() -> @location(0) vec4<f32> { return vec4f(1.,1.,1.,1.); }

        """)

        // 1x1 RGBA (white) raw pixel bytes - single create_texture entry, tuple
        // form (bytes, format, size) selects the raw-pixel path. Format is
        // the placeholder Rgba (sRGB-aware) by default.
        let pixels = [255,255,255,255]
        let texture = try await renderer.createTexture((pixels, [1, 1]))

        // insert  the texture in the shader matching the name in the shader
        try shader.set("my_texture", texture)
    }

    static func _example_core_texture_aspect() async throws {


        let renderer = Renderer()
        // 1x1 RGBA (white) raw pixel bytes
        let pixels = [255,255,255,255]
        let tex = try await renderer.createTexture((pixels, [1, 1]))
        let a = tex.aspect()
    }

    static func _example_core_texture_get_image() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 64], TextureFormat.rgba))
        try texture.write(Array(repeating: 0, count: 64 * 64 * 4))

        let bytes = try await texture.getImage()
    }

    static func _example_core_texture_id() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 64], TextureFormat.rgba))
        let id = texture.id()
    }

    static func _example_core_texture_set_sampler_options() async throws {

        let renderer = Renderer()
        let pixels: [UInt8] = [255, 255, 255, 255]
        let options = TextureOptions(
            size: Size(width: 1, height: 1, depth: nil),
            format: .rgba8UnormSrgb,
            sampler: SamplerOptions(repeatX: false, repeatY: false, smooth: true, compare: nil),
            mipmaps: false,
            usage: nil
        )
        let texture = try await renderer.createTexture(input: .bytes(Data(pixels)), options: options)

        let opts = SamplerOptions(repeatX: true, repeatY: true, smooth: true, compare: nil)
        texture.setSamplerOptions(opts: opts)
    }

    static func _example_core_texture_size() async throws {
        let renderer = Renderer()
        let pixels = [255,255,255,255]
        let tex = try await renderer.createTexture((pixels, [1, 1]))
        let sz = tex.size()
    }

    static func _example_core_texture_write() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 64], TextureFormat.rgba))
        let frame_bytes = Array(repeating: 0, count: 64 * 64 * 4)

        try texture.write(frame_bytes)
    }

    static func _example_core_texture_write_region() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 32], TextureFormat.rgba))
        let bytes = Array(repeating: 0, count: 64 * 32 * 4)

        // Simple sub-rectangle update.
        try texture.writeRegion(bytes, [0, 0, 64, 32])

        // Explicit data layout (advanced â when source rows are padded).
        let region = TextureRegionMobile.from([0, 0, 64, 32]).withStride(256).withRows(32)
        try texture.writeRegion(bytes, region)
    }

    static func _example_core_texture_mip_chain_TextureMipChain() async throws {

        let renderer = Renderer()
        // Encoded image bytes the caller has on hand (could come off a worker).
        let png = [
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A,
            // ... full PNG body ...
        ]
        let chain = try TextureMipChain.prepare((png, TextureFormat.rgba8UnormSrgb))

        // Hand the chain to the unified create_texture entry - same vocabulary as
        // every other texture path; From<TextureMipChain> selects the GPU-only
        // upload internally.
        let texture = try await renderer.createTexture(chain)
    }

    static func _example_core_texture_mip_chain_base_size() async throws {

        let pixels = Array(repeating: 0, count: 16 * 16 * 4)
        let chain = try TextureMipChain.prepare((
            pixels,
            TextureFormat.rgba8UnormSrgb,
            [16, 16],
        ))
        let size = chain.baseSize()
        let _ = size
    }

    static func _example_core_texture_mip_chain_format() async throws {

        let pixels = Array(repeating: 200, count: 4 * 4 * 4)
        let chain = try TextureMipChain.prepare((
            pixels,
            TextureFormat.rgba8UnormSrgb,
            [4, 4],
        ))
        let _ = chain.format()
    }

    static func _example_core_texture_mip_chain_level_count() async throws {

        let pixels = Array(repeating: 0, count: 8 * 8 * 4)
        let chain = try TextureMipChain.prepare((
            pixels,
            TextureFormat.rgba8UnormSrgb,
            [8, 8],
        ))
        let count = chain.levelCount()
        let _ = count
    }

    static func _example_core_texture_mip_chain_levels() async throws {

        let pixels = Array(repeating: UInt8(0), count: 8 * 8 * 4)
        let chain = try TextureMipChain.prepare((pixels, TextureFormat.rgba8UnormSrgb, [8, 8]))
        let level_zero_bytes = try chain.level(index: 0)
        let _ = level_zero_bytes
    }

    static func _example_core_texture_mip_chain_prepare() async throws {

        // Encoded path -- single tuple, no extra method.
        let encoded_png_bytes: [UInt8] = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]
        let chain = try TextureMipChain.prepare((encoded_png_bytes, TextureFormat.rgba8UnormSrgb))

        // Raw pixel path -- same method, just include the size in the tuple.
        let raw_rgba = Array(repeating: UInt8(200), count: 8 * 8 * 4)
        let chain_raw = try TextureMipChain.prepare((raw_rgba, TextureFormat.rgba8UnormSrgb, [8, 8]))

        // Hand the chain to the unified create_texture entry -- same vocabulary.
        let renderer = Renderer()
        let texture = try await renderer.createTexture(chain)
    }

    static func _example_geometry_mesh_Mesh() async throws {

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.5, 0.0])
        try mesh.addVertex([-0.5, -0.5, 0.0])
        try mesh.addVertex([0.5, -0.5, 0.0])
    }

    static func _example_geometry_mesh_add_instance() async throws {

        let m = Mesh()
        let offset = [0.25, 0.10]
        let tint = [1.0, 0.0, 0.0, 1.0]
        try m.addInstance(Instance().set("offset", offset).set("tint", tint))
    }

    static func _example_geometry_mesh_add_instances() async throws {

        let m = Mesh()
        let red = [1.0, 0.0, 0.0, 1.0]
        let green = [0.0, 1.0, 0.0, 1.0]
        let blue = [0.0, 0.0, 1.0, 1.0]
        m.addInstances([
            try Instance().set("tint", red),
            try Instance().set("tint", green),
            try Instance().set("tint", blue),
        ])
    }

    static func _example_geometry_mesh_add_vertex() async throws {
        let m = Mesh()
        try m.addVertex([0.0, 0.0])
    }

    static func _example_geometry_mesh_add_vertices() async throws {
        let m = Mesh()
        try m.addVertices([
          [0.0, 0.0],
          [1.0, 0.0],
        ])
    }

    static func _example_geometry_mesh_clear_instances() async throws {

        let m = Mesh()
        let red = [1.0, 0.0, 0.0, 1.0]
        try m.addInstance(Instance().set("tint", red))
        m.clearInstances(); // back to a single uninstanced draw
    }

    static func _example_geometry_mesh_from_vertices() async throws {

        let mesh = try Mesh.fromVertices([
            [0.0, 0.0],
            [1.0, 0.0],
            [0.0, 1.0],
        ])
    }

    static func _example_geometry_mesh_new() async throws {
        let m = Mesh()
    }

    static func _example_geometry_mesh_set_instance_count() async throws {
        let m = Mesh()
        try m.addVertices([
            [-0.01, -0.01],
            [ 0.01, -0.01],
            [ 0.00,  0.01],
        ])
        // Draw one million instances, fetching per-particle data from a storage buffer.
        m.setInstanceCount(1_000_000)
    }

    static func _example_geometry_quad_Quad() async throws {

        let quad = try Quad([-0.5, -0.5], [0.5, 0.5])
    }

    static func _example_geometry_quad_get_mesh() async throws {

        let quad = try Quad([-0.5, -0.5], [0.5, 0.5])
        let mesh = quad.getMesh()
    }

    static func _example_geometry_quad_new() async throws {

        let quad = try Quad([-0.5, -0.5], [0.5, 0.5])
    }

    static func _example_geometry_vertex_Vertex() async throws {
        let v = try Vertex([0.0, 0.0, 0.0]).set("uv", [0.5, 0.5])
    }

    static func _example_geometry_vertex_create_instance() async throws {
        let v = try Vertex([0.0, 0.0])
        let inst = v.createInstance()
    }

    static func _example_geometry_vertex_new() async throws {
        let v = try Vertex([0.0, 0.0])
    }

    static func _example_geometry_vertex_set() async throws {
        let v = try Vertex([0.0, 0.0, 0.0]).set("weight", 1.0).set("color",[1.0, 0.0, 0.0])
    }

    static func _example_targets_target_Target() async throws {


        let renderer = Renderer()

        // Use your platform's windowing system to create a window.
        // iOS: window/canvas provided by CAMetalLayer at runtime

        let target = try await renderer.createTextureTarget([800, 600])

        // To animate, render again in your event loop...
        try renderer.render(Shader(""), target)
        try renderer.render(Shader(""), target)
    }

    static func _example_targets_target_get_image() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([16, 16])
        try renderer.render(Shader(""), target)

        let image = target.getImage()
    }

    static func _example_targets_target_resize() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 32])

        target.resize([128, 64])
    }

    static func _example_targets_target_size() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 32])
        let size = target.size()
        let width = size.width
        let height = size.height
        let depth = size.depth
    }

    static func _example_targets_texture_target_TextureTarget() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let shader = Shader.default()
        try renderer.render(shader, target)

        let image = target.getImage()
    }

    static func _example_targets_texture_target_get_image() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([16, 16])
        try renderer.render(Shader(""), target)

        let image = target.getImage()
    }

    static func _example_targets_texture_target_resize() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        target.resize([128, 32])
    }

    static func _example_targets_texture_target_size() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])
        let size = target.size()
        let width = size.width
        let height = size.height
        let depth = size.depth
    }

    static func _example_targets_window_target_WindowTarget() async throws {


        // Use your platform's windowing system to create a window.
        // iOS: window/canvas provided by CAMetalLayer at runtime

        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([800, 600])

        try renderer.render(Shader(""), target)
    }

    static func _example_targets_window_target_get_image() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([16, 16])
        try renderer.render(Shader(""), target)

        let image = target.getImage()
    }

    static func _example_targets_window_target_resize() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 32])

        target.resize([128, 64])
    }

    static func _example_targets_window_target_size() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 32])
    }

}
