// AUTO-GENERATED by build.rs (scripts/website.rs). DO NOT EDIT.
//
// Compile-only aggregator for every transpiled Swift example under
// `platforms/swift/examples/`. Each function below embeds the body
// of one example so the compiler type-checks it. Functions are
// never invoked at runtime — wiring up GPU-backed runtime
// execution is a follow-up task.
//
// A failure here means either:
//  (a) the source `docs/api/**.md` example uses a Rust API that
//      `scripts/convert.rs::to_swift` cannot map, or
//  (b) the example references an item that uniffi does not
//      export to Swift.
// Fix the source — this file is regenerated on every cargo build.

import FragmentColor

@available(iOS 16.0, *)
private enum _GeneratedExamples {
    static func _example_core_pass_Pass() async throws {


        let renderer = Renderer()
        // iOS: window/canvas provided by CAMetalLayer at runtime
        let target = try await renderer.createTextureTarget([800, 600])
        let shader = Shader.default()

        let pass = Pass("First Pass")
        pass.addShader(shader)

        let pass2 = Pass("Second Pass")
        pass2.addShader(shader)

        // standalone
        try renderer.render(pass, target)

        // vector of passes rendered in order (any iterable of Pass is renderable)
        try renderer.render([pass, pass2], target)
    }

    static func _example_core_pass_add() async throws {

        let renderer = Renderer()

        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex.pbr([0.0, 0.5, 0.0]).set(Vertex.uV0, [0.5, 1.0]),
        )
        let model = Model(mesh, Material.pbr()?)

        let camera = Camera.perspective(60.0.toRadians(), 1.0, 0.1, 100.0).lookAt([0.0, 0.0, 2.0], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0])
        let sun = Light.directional([0.3, -1.0, -0.4], [1.0, 0.95, 0.9])

        let pass = Pass("scene")
        pass.add(model)?.add(camera)?.add(sun)

        // Updating the camera later is enough — every Model already on the pass
        // picks the view_proj up at the next render.
        camera.lookAt([3.0, 1.0, 5.0], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0])
    }

    static func _example_core_pass_add_depth_target() async throws {

        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        // One depth attachment shared across the 3D-content pass.
        let depth = try await renderer.createDepthTexture([64, 64])

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0, 0.0])
        try mesh.addVertex([1.0, 0.0, 0.0])
        try mesh.addVertex([0.0, 1.0, 0.0])
        try mesh.addVertex([1.0, 1.0, 0.0])
        let shader = Shader.fromMesh(mesh)
        let pass = Pass("blobs"); pass.addShader(shader)

        // Depth-test on — closer fragments win, the pass writes to the depth
        // buffer so subsequent draws within the same pass see the depth.
        try pass.addDepthTarget(depth)

        try renderer.render(pass, target)
    }

    static func _example_core_pass_add_mesh() async throws {

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0])

        let shader = try Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        let pass = Pass("pass"); pass.addShader(shader)

        try pass.addMesh(mesh)
    }

    static func _example_core_pass_add_shader() async throws {

        let shader = Shader.default()
        let pass = Pass("p")
        pass.addShader(shader)
    }

    static func _example_core_pass_add_target() async throws {

        let r = Renderer()
        let tex_target = try await r.createTextureTarget([512, 512])

        let p = Pass("shadow")
        try p.addTarget(tex_target)
    }

    static func _example_core_pass_compute() async throws {

        let cs = try! Shader("@compute @workgroup_size(8,8,1) fn cs_main() {}")
        let pass = Pass("compute"); pass.addShader(cs)
    }

    static func _example_core_pass_from_shader() async throws {

        let shader = Shader.default()
        let pass = Pass("single"); pass.addShader(shader)
    }

    static func _example_core_pass_get_input() async throws {

        let pass = Pass("example")
        let input = pass.getInput()
    }

    static func _example_core_pass_is_compute() async throws {

        let shader = try Shader("""
        @compute @workgroup_size(1)
        fn cs_main() { }

        """)
        let pass = Pass("p"); pass.addShader(shader)

        // Call the method
        let is_compute = pass.isCompute()
    }

    static func _example_core_pass_load_previous() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let shader = Shader.default()
        let pass = Pass("blend with previous")
        pass.addShader(shader)
        pass.loadPrevious()

        try renderer.render(pass, target)
    }

    static func _example_core_pass_new() async throws {

        let pass = Pass("first pass")
    }

    static func _example_core_pass_require() async throws {
        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([100,100])
        let color = Pass("color")
        let blurx = Pass("blur_x")
        try blurx.require(color); // color before blur_x
        let blury = Pass("blur_y")
        try blury.require(blurx); // blur_x before blur_y
        let compose = Pass("compose")
        try compose.require(color)
        try compose.require(blury); // fan-in; color and blur_y before compose
        try renderer.render(compose, target); // compose renders last
    }

    static func _example_core_pass_set_clear_color() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let shader = Shader.default()
        let pass = Pass("solid background")
        pass.addShader(shader)

        try pass.setClearColor([0.1, 0.2, 0.3, 1.0])

        try renderer.render(pass, target)
    }

    static func _example_core_pass_set_compute_dispatch() async throws {
        let cs = try! Shader("@compute @workgroup_size(8,8,1) fn cs_main() {}")
        let pass = Pass("compute"); pass.addShader(cs)
        pass.setComputeDispatch(64, 64, 1)
    }

    static func _example_core_pass_set_viewport() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let shader = Shader.default()
        let pass = Pass("clipped")
        pass.addShader(shader)

        pass.setViewport([(0, 0), (32, 32)])

        try renderer.render(pass, target)
    }

    static func _example_core_renderer_Renderer() async throws {


        let renderer = Renderer()

        // Use your platform's windowing system to create a window
        // iOS: window/canvas provided by CAMetalLayer at runtime

        // Create a Target from it
        let target = try await renderer.createTextureTarget([800, 600])
        let texture_target = try await renderer.createTextureTarget([16, 16])

        // RENDERING
        try renderer.render(Shader(""), texture_target)

        // That's it. Welcome to FragmentColor!
    }

    static func _example_core_renderer_create_depth_texture() async throws {
        let r = Renderer()
        let depth = try await r.createDepthTexture([800, 600])
    }

    static func _example_core_renderer_create_external_texture() async throws {
        // Once supported:
        //   let renderer = Renderer()
        //   let pixelBuffer: CVPixelBuffer = /* from AVPlayerItemVideoOutput */
        //   let ptr = UInt64(UInt(bitPattern: Unmanaged.passUnretained(pixelBuffer).toOpaque()))
        //   let handle = try renderer.createExternalTexture(sourcePtr: ptr)
    }

    static func _example_core_renderer_create_storage_texture() async throws {

        let r = Renderer()

        // Empty storage texture.
        let tex = try await r.createStorageTexture(([64, 64], TextureFormat.rgba))

        // Pre-seeded with bytes.
        let pixels = Array(repeating: 0, count: 64 * 64 * 4)
        let tex2 = try await r.createStorageTexture(([64, 64], TextureFormat.rgba, pixels))
    }

    static func _example_core_renderer_create_target() async throws {


        let renderer = Renderer()

        // Use your platform's windowing system to create a window.
        // iOS: window/canvas provided by CAMetalLayer at runtime

        let target = try await renderer.createTextureTarget([800, 600])
    }

    static func _example_core_renderer_create_texture() async throws {
        let renderer = Renderer()
        let image = "/healthcheck/public/favicon.png"
        let tex = try await renderer.createTexture(image)
    }

    static func _example_core_renderer_create_texture_target() async throws {

        let renderer = Renderer()

        // Create an offscreen texture target with a size of 64x64 pixels.
        let target = try await renderer.createTextureTarget([64, 64])

        try renderer.render(Shader(""), target)

        // get the rendered image
        let image = try await target.getImage()
    }

    static func _example_core_renderer_load() async throws {

        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex.pbr([0.0, 0.5, 0.0]).set(Vertex.uV0, [0.5, 1.0]),
        )
        // Raw 2×2 RGBA pixel bytes — uploaded lazily by """Renderer.load""" below.
        // In practice the loader hands the setter encoded PNG/JPEG bytes (from a
        // BIN chunk) or a file path (from a URI); the same """Into<TextureInput>"""
        // vocabulary covers all of them.
        let red_pixels = [
            255,   0,   0, 255,    0, 255,   0, 255,
              0,   0, 255, 255,  255, 255, 255, 255,
        ]
        let material = Material.pbr()?.baseColorTexture((red_pixels, [2, 2]))
        let model = Model(mesh, material)
        let scene = Scene()
        scene.add(model)

        // Eager prewarm — uploads the pending texture(s) so the next render is
        // GPU-only.
        try await renderer.load(scene)
        try renderer.render(scene, target)
    }

    static func _example_core_renderer_new() async throws {


        let renderer = Renderer()
        let texture_target = try await renderer.createTextureTarget([16, 16])
    }

    static func _example_core_renderer_read_texture() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 64], TextureFormat.rgba))
        try texture.write(Array(repeating: 0, count: 64 * 64 * 4))

        let bytes = try await renderer.readTexture(texture.id())
    }

    static func _example_core_renderer_render() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([10, 10])
        let shader = Shader.default()

        try renderer.render(shader, target)
    }

    static func _example_core_renderer_unregister_texture() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([16, 16], TextureFormat.rgba))
        let id = texture.id()

        try renderer.unregisterTexture(id)
    }

    static func _example_core_shader_Shader() async throws {


        let shader = try Shader("""
            @vertex
            fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
                var pos = array<vec2<f32>, 3>(
                    vec2<f32>(-1.0, -1.0),
                    vec2<f32>( 3.0, -1.0),
                    vec2<f32>(-1.0,  3.0)
                )
                return vec4<f32>(pos[index], 0.0, 1.0)
            }

            @group(0) @binding(0)
            var<uniform> resolution: vec2<f32>

            @fragment
            fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
            }

        """)

        // Set the "resolution" uniform
        try shader.set("resolution", [800.0, 600.0])
        let res = try shader.get("resolution")

        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([16, 16])
        try renderer.render(shader, target)
    }

    static func _example_core_shader_add_mesh() async throws {

        let shader = try Shader("""
          @vertex fn vs_main(@location(0) pos: vec3<f32>) -> @builtin(position) vec4<f32> {
            return vec4<f32>(pos, 1.0)
          }
          @fragment fn fs_main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0, 0.0])

        // Attach mesh to this shader (errors if incompatible)
        try shader.addMesh(mesh)

        // Renderer will draw the mesh when rendering this pass.
        // Each Shader represents a RenderPipeline or ComputePipeline
        // in the GPU. Adding multiple meshes to it will draw all meshes
        // and all its instances in the same Pipeline.
    }

    static func _example_core_shader_clear_meshes() async throws {

        let shader = try Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0])
        try shader.addMesh(mesh)

        // Clear all
        shader.clearMeshes()
    }

    static func _example_core_shader_fetch() async throws {


        // Full registry URL.
        let shader = try await Shader.fetch("https://fragmentcolor.org/shaders/sdf2d/circle.wgsl")

        // Equivalent shorthand using the registry slug.
        let shader2 = try await Shader.fetch("sdf2d/circle")
    }

    static func _example_core_shader_from_mesh() async throws {

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0, 0.0])
        let shader = Shader.fromMesh(mesh)
    }

    static func _example_core_shader_from_vertex() async throws {

        let vertex = try Vertex([0.0, 0.0, 0.0])
        let shader = Shader.fromVertex(vertex)
    }

    static func _example_core_shader_get() async throws {

        let shader = Shader.default()
        try shader.set("resolution", [800.0, 600.0])
        let res = try shader.get("resolution")
    }

    static func _example_core_shader_is_compute() async throws {

        let shader = try Shader("""
        @compute @workgroup_size(1)
        fn cs_main() { }

        """)

        // Call the method
        let is_compute = shader.isCompute()
    }

    static func _example_core_shader_list_keys() async throws {


        let shader = Shader.default()
        let keys = shader.listKeys()
    }

    static func _example_core_shader_list_uniforms() async throws {

        let shader = Shader.default()
        let list = shader.listUniforms()
    }

    static func _example_core_shader_new() async throws {


        let shader = try Shader("""
            @vertex
            fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
                var pos = array<vec2<f32>, 3>(
                    vec2<f32>(-1.0, -1.0),
                    vec2<f32>( 3.0, -1.0),
                    vec2<f32>(-1.0,  3.0)
                )
                return vec4<f32>(pos[index], 0.0, 1.0)
            }

            @group(0) @binding(0)
            var<uniform> resolution: vec2<f32>

            @fragment
            fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
            }

        """)


        let main = """
            @vertex fn vs(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
                let p = array<vec2<f32>,3>(vec2f(-1.,-1.), vec2f(3.,-1.), vec2f(-1.,3.))
                return vec4<f32>(p[i], 0.0, 1.0)
            }

            @fragment fn fs(@builtin(position) pos: vec4<f32>) -> @location(0) vec4<f32> {
                let d = circle(pos.xy - vec2<f32>(400.0, 300.0), 100.0)
                let n = simplex2(pos.xy * 0.01)
                return vec4<f32>(vec3<f32>(step(0.0, d) + n * 0.1), 1.0)
            }

        """

        let shader = try Shader.new([
            "sdf2d/circle",      // pure function: fn circle(p: vec2<f32>, r: f32) -> f32
            "noise/simplex2",    // pure function: fn simplex2(v: vec2<f32>) -> f32
            main,
        ])
    }

    static func _example_core_shader_remove_mesh() async throws {

        let shader = try Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.0])
        try shader.addMesh(mesh)

        // Detach the mesh
        try shader.removeMesh(mesh)
    }

    static func _example_core_shader_remove_meshes() async throws {

        let shader = try Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        let m1 = Mesh()
        try m1.addVertex([0.0, 0.0])
        let m2 = Mesh()
        try m2.addVertex([0.5, 0.0])

        try shader.addMesh(m1)
        try shader.addMesh(m2)

        shader.removeMeshes([m1, m2])
    }

    static func _example_core_shader_set() async throws {
        let r = Renderer()
        let shader = try Shader("""
        @group(0) @binding(0) var<uniform> resolution: vec2<f32>

        struct VOut { @builtin(position) pos: vec4<f32> }
        @vertex fn vs_main(@builtin(vertex_index) i: u32) -> VOut {
          var p = array<vec2<f32>, 3>(vec2<f32>(-1.,-1.), vec2<f32>(3.,-1.), vec2<f32>(-1.,3.))
          var out: VOut
          out.pos = vec4<f32>(p[i], 0., 1.)
          return out
        }
        @fragment fn main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        // Set scalars/vectors on declared uniforms
        try shader.set("resolution", [800.0, 600.0])
    }

    static func _example_core_shader_set_registry() async throws {


        // Point at your own mirror of the registry
        Shader.setRegistry("https://cdn.example.com/shaders/")

        // Now the slug "sdf2d/circle" resolves to https://cdn.example.com/shaders/sdf2d/circle.wgsl
        // (Skipping the actual fetch in this doctest)
    }

    static func _example_core_shader_validate_mesh() async throws {

        let shader = try Shader("""
        struct VOut { @builtin(position) pos: vec4<f32> }
        @vertex fn vs_main(@location(0) pos: vec3<f32>) -> VOut {
          var out: VOut
          out.pos = vec4<f32>(pos, 1.0)
          return out
        }
        @fragment fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)
        let pass = Pass("p"); pass.addShader(shader)

        let mesh = Mesh()
        try mesh.addVertices([
          [-0.5, -0.5, 0.0],
          [ 0.5, -0.5, 0.0],
          [ 0.0,  0.5, 0.0],
        ])

        try shader.validateMesh(mesh); // Ok
        try pass.addMesh(mesh)
    }

    static func _example_geometry_mesh_Mesh() async throws {

        let mesh = Mesh()
        try mesh.addVertex([0.0, 0.5, 0.0])
        try mesh.addVertex([-0.5, -0.5, 0.0])
        try mesh.addVertex([0.5, -0.5, 0.0])
    }

    static func _example_geometry_mesh_add_instance() async throws {

        let m = Mesh()
        let offset = [0.25, 0.10]
        let tint = [1.0, 0.0, 0.0, 1.0]
        try m.addInstance(Instance().set("offset", offset).set("tint", tint))
    }

    static func _example_geometry_mesh_add_instances() async throws {

        let m = Mesh()
        let red = [1.0, 0.0, 0.0, 1.0]
        let green = [0.0, 1.0, 0.0, 1.0]
        let blue = [0.0, 0.0, 1.0, 1.0]
        m.addInstances([
            try Instance().set("tint", red),
            try Instance().set("tint", green),
            try Instance().set("tint", blue),
        ])
    }

    static func _example_geometry_mesh_add_vertex() async throws {
        let m = Mesh()
        try m.addVertex([0.0, 0.0])
    }

    static func _example_geometry_mesh_add_vertices() async throws {
        let m = Mesh()
        try m.addVertices([
          [0.0, 0.0],
          [1.0, 0.0],
        ])
    }

    static func _example_geometry_mesh_clear_indices() async throws {

        let mesh = Mesh()
        try mesh.addVertices([
            try Vertex([-0.5, -0.5]),
            try Vertex([ 0.5, -0.5]),
            try Vertex([ 0.0,  0.5]),
        ])
        mesh.setIndices([0, 1, 2])
        mesh.clearIndices(); // back to auto-derived dedup
    }

    static func _example_geometry_mesh_clear_instances() async throws {

        let m = Mesh()
        let red = [1.0, 0.0, 0.0, 1.0]
        try m.addInstance(Instance().set("tint", red))
        m.clearInstances(); // back to a single uninstanced draw
    }

    static func _example_geometry_mesh_from_vertices() async throws {

        let mesh = try Mesh.fromVertices([
            [0.0, 0.0],
            [1.0, 0.0],
            [0.0, 1.0],
        ])
    }

    static func _example_geometry_mesh_new() async throws {
        let m = Mesh()
    }

    static func _example_geometry_mesh_set_indices() async throws {

        // A quad split into two triangles via explicit indexing. The four corners
        // happen to carry distinct UVs (only positions repeat), so we keep them
        // all and reference each by index.
        let mesh = Mesh()
        let uv00 = [0.0, 0.0]
        let uv10 = [1.0, 0.0]
        let uv11 = [1.0, 1.0]
        let uv01 = [0.0, 1.0]
        try mesh.addVertices([
            try Vertex([-0.5, -0.5]).set("uv", uv00),
            try Vertex([ 0.5, -0.5]).set("uv", uv10),
            try Vertex([ 0.5,  0.5]).set("uv", uv11),
            try Vertex([-0.5,  0.5]).set("uv", uv01),
        ])
        mesh.setIndices([0, 1, 2, 0, 2, 3])
    }

    static func _example_geometry_mesh_set_instance_count() async throws {
        let m = Mesh()
        try m.addVertices([
            [-0.01, -0.01],
            [ 0.01, -0.01],
            [ 0.00,  0.01],
        ])
        // Draw one million instances, fetching per-particle data from a storage buffer.
        m.setInstanceCount(1_000_000)
    }

    static func _example_geometry_quad_Quad() async throws {

        let quad = try Quad([-0.5, -0.5], [0.5, 0.5])
    }

    static func _example_geometry_quad_get_mesh() async throws {

        let quad = try Quad([-0.5, -0.5], [0.5, 0.5])
        let mesh = quad.getMesh()
    }

    static func _example_geometry_quad_new() async throws {

        let quad = try Quad([-0.5, -0.5], [0.5, 0.5])
    }

    static func _example_geometry_vertex_Vertex() async throws {
        let v = try Vertex([0.0, 0.0, 0.0]).set(Vertex.uV0, [0.5, 0.5]).set(Vertex.nORMAL, [0.0, 1.0, 0.0])
    }

    static func _example_geometry_vertex_create_instance() async throws {
        let v = try Vertex([0.0, 0.0])
        let inst = v.createInstance()
    }

    static func _example_geometry_vertex_new() async throws {
        let v = try Vertex([0.0, 0.0])
    }

    static func _example_geometry_vertex_pbr() async throws {

        let mesh = Mesh()
        for (pos, uv) in [
            ([0.0, 0.5, 0.0], [0.5, 1.0]),
            ([-0.5, -0.5, 0.0], [0.0, 0.0]),
            ([0.5, -0.5, 0.0], [1.0, 0.0]),
        ] {
            // Override only what the mesh actually carries; NORMAL / COLOR0 / UV1 /
            // TANGENT use their identity defaults.
            try mesh.addVertex(Vertex.pbr(pos).set(Vertex.uV0, uv))
        }
    }

    static func _example_geometry_vertex_set() async throws {
        let v = try Vertex([0.0, 0.0, 0.0]).set("weight", 1.0).set("color",[1.0, 0.0, 0.0])
    }

    static func _example_scene_camera_look_at() async throws {

        let camera = Camera.perspective(60.0.toRadians(), 16.0 / 9.0, 0.1, 100.0).lookAt([0.0, 1.0, 5.0], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0])
    }

    static func _example_scene_camera_orthographic() async throws {

        // A 16:9 viewport, 10 world units tall, depth range 0.1...100.
        let camera = Camera.orthographic(-8.0, 8.0, -4.5, 4.5, 0.1, 100.0)
    }

    static func _example_scene_camera_perspective() async throws {

        let camera = Camera.perspective(60.0.toRadians(), 16.0 / 9.0, 0.1, 100.0)
    }

    static func _example_scene_camera_position() async throws {

        let camera = Camera.perspective(60.0.toRadians(), 16.0 / 9.0, 0.1, 100.0).lookAt([3.0, 2.0, 8.0], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0])

        let eye = camera.position()
    }

    static func _example_scene_camera_set_aspect() async throws {

        let camera = Camera.perspective(60.0.toRadians(), 1.0, 0.1, 100.0)

        // Window resize: 1920×1080 → wide-screen aspect.
        camera.setAspect(1920.0 / 1080.0)
    }

    static func _example_scene_camera_view_proj() async throws {

        let camera = Camera.perspective(60.0.toRadians(), 16.0 / 9.0, 0.1, 100.0).lookAt([0.0, 0.0, 5.0], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0])

        let m = camera.viewProj()
        let _ = m
    }

    static func _example_scene_light_color() async throws {

        let warm = Light.directional([0.0, -1.0, 0.0], [1.0, 0.85, 0.7])
        let color = warm.color()
    }

    static func _example_scene_light_direction() async throws {

        let sun = Light.directional([0.3, -1.0, -0.4], [1.0, 1.0, 1.0])
        let dir = sun.direction()
    }

    static func _example_scene_light_directional() async throws {

        let sun = Light.directional([0.3, -1.0, -0.4], [1.0, 0.95, 0.9])
    }

    static func _example_scene_light_inner_cone_angle() async throws {

        let torch = Light.spot([0.0, 1.0, 0.0], [0.0, -1.0, 0.0], [1.0, 1.0, 1.0]).setConeAngles(0.2, 0.5)
        let inner = torch.innerConeAngle()
    }

    static func _example_scene_light_intensity() async throws {

        let lamp = Light.point([0.0, 1.0, 0.0], [1.0, 0.95, 0.8]).setIntensity(12.0)
        let scale = lamp.intensity()
    }

    static func _example_scene_light_outer_cone_angle() async throws {

        let torch = Light.spot([0.0, 1.0, 0.0], [0.0, -1.0, 0.0], [1.0, 1.0, 1.0]).setConeAngles(0.2, 0.5)
        let outer = torch.outerConeAngle()
    }

    static func _example_scene_light_point() async throws {

        let bulb = Light.point([0.0, 2.5, 0.0], [1.0, 0.95, 0.8]).setIntensity(15.0)
    }

    static func _example_scene_light_position() async throws {

        let bulb = Light.point([3.0, 2.5, -1.0], [1.0, 1.0, 1.0])
        let pos = bulb.position()
    }

    static func _example_scene_light_range() async throws {

        let bulb = Light.point([0.0, 0.0, 0.0], [1.0, 1.0, 1.0]).setRange(8.0)
        let cutoff = bulb.range()
    }

    static func _example_scene_light_set_color() async throws {

        let lamp = Light.directional([0.0, -1.0, 0.0], [1.0, 1.0, 1.0])
        // Warm-tinted bulb after the user toggles the warm-light switch.
        lamp.setColor([1.0, 0.85, 0.7])
    }

    static func _example_scene_light_set_cone_angles() async throws {

        let torch = Light.spot([0.0, 1.0, 0.0], [0.0, -1.0, 0.0], [1.0, 1.0, 1.0])
        torch.setConeAngles(0.15, 0.5)
    }

    static func _example_scene_light_set_direction() async throws {

        let sun = Light.directional([0.0, -1.0, 0.0], [1.0, 1.0, 1.0])
        // Reorient to a late-afternoon angle.
        sun.setDirection([0.7, -0.5, -0.5])
    }

    static func _example_scene_light_set_intensity() async throws {

        let lamp = Light.point([0.0, 1.0, 0.0], [1.0, 0.95, 0.8])
        lamp.setIntensity(15.0)
    }

    static func _example_scene_light_set_position() async throws {

        let bulb = Light.point([0.0, 0.0, 0.0], [1.0, 1.0, 1.0])
        bulb.setPosition([2.0, 3.0, -1.0])
    }

    static func _example_scene_light_set_range() async throws {

        let bulb = Light.point([0.0, 0.0, 0.0], [1.0, 1.0, 1.0])
        bulb.setRange(8.0)
    }

    static func _example_scene_light_spot() async throws {

        let torch = Light.spot([0.0, 1.8, 1.0], [0.0, -0.3, -1.0], [1.0, 0.9, 0.7]).setIntensity(5.0).setConeAngles(0.15, 0.4)
    }

    static func _example_scene_material_Material() async throws {

        let renderer = Renderer()
        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex.pbr([0.0, 0.5, 0.0]).set(Vertex.uV0, [0.5, 1.0]),
        )

        let material = Material.pbr()?.baseColor([0.85, 0.2, 0.2, 1.0]).metallic(0.0).roughness(0.4).emissive([0.0, 0.0, 0.05])

        let model = Model(mesh, material)
    }

    static func _example_scene_material_alpha_cutoff() async throws {

        let renderer = Renderer()
        let foliage = Material.pbr()?.alphaCutoff(0.3)
    }

    static func _example_scene_material_alpha_mode() async throws {

        let renderer = Renderer()
        let foliage = Material.pbr()?.alphaMode(AlphaMode.mask).alphaCutoff(0.3)

        let glass = Material.pbr()?.baseColor([0.9, 0.95, 1.0, 0.25]).alphaMode(AlphaMode.blend)

        let solid = Material.pbr()?.alphaMode(AlphaMode.opaque)
    }

    static func _example_scene_material_base_color() async throws {

        let renderer = Renderer()
        let red = Material.pbr()?.baseColor([1.0, 0.2, 0.2, 1.0])
    }

    static func _example_scene_material_base_color_texture() async throws {

        let renderer = Renderer()
        let texture = renderer.createTexture([
            255, 200, 120, 255,
            255,  240, 180, 255,
            230,  180, 100, 255,
            255,  220, 150, 255,
        try await ])
        let mat = Material.pbr()?.baseColorTexture(texture)
    }

    static func _example_scene_material_custom() async throws {

        let wireframe = try Shader("""
            struct MeshTransform { model: mat4x4<f32> }
            struct Camera { view_proj: mat4x4<f32>, position: vec3<f32> }
            @group(0) @binding(0) var<uniform> camera: Camera
            @group(1) @binding(0) var<uniform> mesh: MeshTransform

            @vertex
            fn vs_main(@location(0) p: vec3<f32>) -> @builtin(position) vec4<f32> {
                return camera.view_proj * mesh.model * vec4<f32>(p, 1.0)
            }
            @fragment fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(0.0, 1.0, 0.4, 1.0)
            }

        """)

        let wire_mat = Material.custom(wireframe)
    }

    static func _example_scene_material_double_sided() async throws {

        let renderer = Renderer()
        // Leaf cards: thin, single-quad geometry; needs both sides + alpha cut-out.
        let leaf = Material.pbr()?.doubleSided(true).alphaMode(AlphaMode.mask).alphaCutoff(0.5)

        // Default is single-sided — back-face culling on.
        let solid_mesh = Material.pbr()?.doubleSided(false)
    }

    static func _example_scene_material_emissive() async throws {

        let renderer = Renderer()
        let lava = Material.pbr()?.baseColor([0.1, 0.05, 0.0, 1.0]).emissive([1.5, 0.4, 0.1])
    }

    static func _example_scene_material_emissive_texture() async throws {

        let renderer = Renderer()
        let glow = renderer.createTexture([
            255, 0, 0, 255,
            255,   0, 0, 255,
            255,   0, 0, 255,
            255,   0, 0, 255,
        try await ])
        let mat = Material.pbr()?.emissive([0.8, 0.0, 0.0]).emissiveTexture(glow)
    }

    static func _example_scene_material_metallic() async throws {

        let renderer = Renderer()
        let chrome = Material.pbr()?.metallic(1.0).roughness(0.05)
    }

    static func _example_scene_material_metallic_roughness_texture() async throws {

        let renderer = Renderer()
        let mr_map = renderer.createTexture([
            0, 200, 50, 255,
            0,   240, 80, 255,
            0,   180, 30, 255,
            0,   220, 60, 255,
        try await ])
        let mat = Material.pbr()?.metallicRoughnessTexture(mr_map)
    }

    static func _example_scene_material_normal_scale() async throws {

        let renderer = Renderer()
        let detailed = Material.pbr()?.normalScale(1.5)
    }

    static func _example_scene_material_normal_texture() async throws {

        let renderer = Renderer()
        let normal_map = renderer.createTexture([
            128, 128, 255, 255,
            128,   128, 255, 255,
            128,   128, 255, 255,
            128,   128, 255, 255,
        try await ])
        let mat = Material.pbr()?.normalTexture(normal_map).normalScale(1.2)
    }

    static func _example_scene_material_occlusion_strength() async throws {

        let renderer = Renderer()
        let crevices = Material.pbr()?.occlusionStrength(0.8)
    }

    static func _example_scene_material_occlusion_texture() async throws {

        let renderer = Renderer()
        let ao = renderer.createTexture([
            220, 0, 0, 255,
            180,   0, 0, 255,
            200,   0, 0, 255,
            160,   0, 0, 255,
        try await ])
        let mat = Material.pbr()?.occlusionTexture(ao)
    }

    static func _example_scene_material_pbr() async throws {

        let renderer = Renderer()
        let bronze = Material.pbr()?.baseColor([0.8, 0.5, 0.2, 1.0]).metallic(1.0).roughness(0.3)
    }

    static func _example_scene_material_roughness() async throws {

        let renderer = Renderer()
        let satin = Material.pbr()?.roughness(0.35)
    }

    static func _example_scene_material_shader() async throws {

        // Direct uniform access for a custom field that isn't covered by the
        // Material setters or by Camera / Light.
        let renderer = Renderer()
        let material = Material.pbr()
        try material.shader().set("material.alphaCutoff", 0.25)
    }

    static func _example_scene_material_uv_transform() async throws {

        // Tile the texture 4× in both directions, rotate 45°, shift by half a tile.
        let brick = Material.pbr()?.uvTransform([0.5, 0.0], [4.0, 4.0], std.f32.consts.fRACPI4)
    }

    static func _example_scene_model_material() async throws {

        let renderer = Renderer()
        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex([0.0, 0.0, 0.0]).set(Vertex.nORMAL, [0.0, 1.0, 0.0]).set(Vertex.uV0, [0.0, 0.0]),
        )

        let model = Model(mesh, Material.pbr()?)
        try model.material().shader().set("camera.position", [0.0, 0.0, 5.0])
    }

    static func _example_scene_model_mesh() async throws {

        let renderer = Renderer()
        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex.pbr([0.0, 0.5, 0.0]).set(Vertex.uV0, [0.5, 1.0]),
        )

        let model = Model(mesh, Material.pbr()?)
        try model.mesh().addVertex(
            try Vertex([-0.5, -0.5, 0.0]).set(Vertex.nORMAL, [0.0, 0.0, 1.0]).set(Vertex.uV0, [0.0, 0.0]),
        )
    }

    static func _example_scene_model_new() async throws {

        let renderer = Renderer()
        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex([0.0, 0.0, 0.0]).set(Vertex.nORMAL, [0.0, 1.0, 0.0]).set(Vertex.uV0, [0.0, 0.0]),
        )

        let model = Model(mesh, Material.pbr()?)
    }

    static func _example_scene_model_rotate() async throws {

        let renderer = Renderer()
        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex([0.0, 0.0, 0.0]).set(Vertex.nORMAL, [0.0, 1.0, 0.0]).set(Vertex.uV0, [0.0, 0.0]),
        )

        let model = Model(mesh, Material.pbr()?)
        model.rotate([0.0, 1.0, 0.0], std.f32.consts.fRACPI2)
    }

    static func _example_scene_model_scale() async throws {

        let renderer = Renderer()
        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex([0.0, 0.0, 0.0]).set(Vertex.nORMAL, [0.0, 1.0, 0.0]).set(Vertex.uV0, [0.0, 0.0]),
        )

        let model = Model(mesh, Material.pbr()?)
        model.scale([2.0, 2.0, 2.0])
    }

    static func _example_scene_model_set_transform() async throws {

        let renderer = Renderer()
        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex([0.0, 0.0, 0.0]).set(Vertex.nORMAL, [0.0, 1.0, 0.0]).set(Vertex.uV0, [0.0, 0.0]),
        )

        let model = Model(mesh, Material.pbr()?)
        model.setTransform([
            [2.0, 0.0, 0.0, 0.0],
            [0.0, 2.0, 0.0, 0.0],
            [0.0, 0.0, 2.0, 0.0],
            [3.0, 0.0, 0.0, 1.0],
        ])
    }

    static func _example_scene_model_transform() async throws {

        let renderer = Renderer()
        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex([0.0, 0.0, 0.0]).set(Vertex.nORMAL, [0.0, 1.0, 0.0]).set(Vertex.uV0, [0.0, 0.0]),
        )

        let model = Model(mesh, Material.pbr()?)
        let identity = model.transform()
    }

    static func _example_scene_model_translate() async throws {

        let renderer = Renderer()
        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex([0.0, 0.0, 0.0]).set(Vertex.nORMAL, [0.0, 1.0, 0.0]).set(Vertex.uV0, [0.0, 0.0]),
        )

        let model = Model(mesh, Material.pbr()?)
        model.translate([5.0, 0.0, -2.0])
    }

    static func _example_scene_scene_add() async throws {

        let renderer = Renderer()

        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex.pbr([0.0, 0.5, 0.0]).set(Vertex.uV0, [0.5, 1.0]),
        )
        let model = Model(mesh, Material.pbr()?)

        let camera = Camera.perspective(60.0.toRadians(), 1.0, 0.1, 100.0).lookAt([0.0, 0.0, 3.0], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0])
        let sun = Light.directional([0.3, -1.0, -0.4], [1.0, 0.95, 0.9])

        let scene = Scene()
        scene.add(model)?.add(camera)?.add(sun)

        // Updating the camera later is enough — every shader on the scene picks
        // the view_proj up at the next render.
        camera.lookAt([3.0, 1.0, 5.0], [0.0, 0.0, 0.0], [0.0, 1.0, 0.0])
    }

    static func _example_scene_scene_add_pass() async throws {

        let renderer = Renderer()

        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex.pbr([0.0, 0.5, 0.0]).set(Vertex.uV0, [0.5, 1.0]),
        )
        let model = Model(mesh, Material.pbr()?)

        // A backdrop pass that clears to a soft blue before the scene's main draw.
        let backdrop = Pass("backdrop")
        try backdrop.setClearColor([0.05, 0.08, 0.12, 1.0])

        let scene = Scene()
        scene.addPass(backdrop)
        scene.add(model)
    }

    static func _example_scene_scene_ambient() async throws {

        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let mesh = Mesh()
        try mesh.addVertex(
            try Vertex.pbr([0.0, 0.5, 0.0]).set(Vertex.uV0, [0.5, 1.0]),
        )

        let scene = Scene()
        // Warm dusk ambient — applies to every Material added below.
        scene.ambient([0.06, 0.04, 0.03])
        scene.add(Model.new(mesh, Material.pbr()?))
        scene.add(Light.directional([0.3, -1.0, -0.4], [1.0, 0.95, 0.9]))

        try renderer.render(scene, target)
    }

    static func _example_scene_scene_load() async throws {

        // File path — covers both """.gltf""" JSON (with external buffers/images)
        // and """.glb""" binary containers.
        let scene = Scene.load(SceneSource.gltf("path/to/model.gltf"))

        // In-memory """.glb""" bytes — fetched from disk, network, or a BIN chunk
        // in another format.
        let glb_bytes = [/* … */]
        let scene2 = Scene.load(SceneSource.gltf(glb_bytes))
    }

    static func _example_scene_scene_new() async throws {

        let scene = Scene()
        // scene is empty; add Models / Cameras / Lights with """scene.add(...)""".
    }

    static func _example_targets_target_Target() async throws {


        let renderer = Renderer()

        // Use your platform's windowing system to create a window.
        // iOS: window/canvas provided by CAMetalLayer at runtime

        let target = try await renderer.createTextureTarget([800, 600])

        // To animate, render again in your event loop...
        try renderer.render(Shader(""), target)
        try renderer.render(Shader(""), target)
    }

    static func _example_targets_target_get_image() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([16, 16])
        try renderer.render(Shader(""), target)

        let image = try await target.getImage()
    }

    static func _example_targets_target_resize() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 32])

        target.resize([128, 64])
    }

    static func _example_targets_target_size() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 32])
        let size = target.size()
        let width = size.width
        let height = size.height
        let depth = size.depth
    }

    static func _example_targets_texture_target_TextureTarget() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 64])

        let shader = Shader.default()
        try renderer.render(shader, target)

        let image = try await target.getImage()
    }

    static func _example_targets_texture_target_texture() async throws {

        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([256, 256])

        // Bind the offscreen target's contents as a uniform on a downstream
        // post-processing shader.
        let post = try Shader("""
            @group(0) @binding(0) var input_image : texture_2d<f32>
            @group(0) @binding(1) var input_sampler : sampler

            @vertex fn vs_main(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
                let p = array<vec2<f32>, 3>(vec2f(-1.0,-1.0), vec2f(3.0,-1.0), vec2f(-1.0,3.0))
                return vec4<f32>(p[i], 0.0, 1.0)
            }
            @fragment fn fs_main(@builtin(position) pos: vec4<f32>) -> @location(0) vec4<f32> {
                return textureSample(input_image, input_sampler, vec2<f32>(0.5, 0.5))
            }

        """)
        try post.set("input_image", target.texture())
    }

    static func _example_targets_window_target_WindowTarget() async throws {


        // Use your platform's windowing system to create a window.
        // iOS: window/canvas provided by CAMetalLayer at runtime

        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([800, 600])

        try renderer.render(Shader(""), target)
    }

    static func _example_targets_window_target_get_image() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([16, 16])
        try renderer.render(Shader(""), target)

        let image = try await target.getImage()
    }

    static func _example_targets_window_target_resize() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 32])

        target.resize([128, 64])
    }

    static func _example_targets_window_target_size() async throws {


        let renderer = Renderer()
        let target = try await renderer.createTextureTarget([64, 32])
    }

    static func _example_texture_mipmap_Mipmap() async throws {

        let renderer = Renderer()

        // Minimal 1×1 RGBA raw pixel bytes.
        let pixels = Data([255, 0, 0, 255])
        let chain = try Mipmap.build(
            bytes: pixels,
            format: .rgba8UnormSrgb,
            size: Size(width: 1, height: 1, depth: nil)
        )

        // Hand the chain to the unified create_texture entry.
        let texture = try await renderer.createTexture(input: .prepared(chain))
        let _ = texture.size()
    }

    static func _example_texture_mipmap_build() async throws {

        // Raw RGBA path: include the size so build skips decoding.
        let rawRgba = Data(repeating: 200, count: 8 * 8 * 4)
        let chainRaw = try Mipmap.build(
            bytes: rawRgba,
            format: .rgba8UnormSrgb,
            size: Size(width: 8, height: 8, depth: nil)
        )

        // Upload the chain through the regular createTexture entry point.
        let renderer = Renderer()
        let texture = try await renderer.createTexture(input: .prepared(chainRaw))
        let _ = chainRaw.count()
        let __ = texture.size()
    }

    static func _example_texture_mipmap_count() async throws {

        let pixels = Data(repeating: 0, count: 8 * 8 * 4)
        let chain = try Mipmap.build(
            bytes: pixels,
            format: .rgba8UnormSrgb,
            size: Size(width: 8, height: 8, depth: nil)
        )
        let count = chain.count()
        let _ = count
    }

    static func _example_texture_mipmap_format() async throws {

        let pixels = Data(repeating: 200, count: 4 * 4 * 4)
        let chain = try Mipmap.build(
            bytes: pixels,
            format: .rgba8UnormSrgb,
            size: Size(width: 4, height: 4, depth: nil)
        )
        let _ = chain.format()
    }

    static func _example_texture_mipmap_levels() async throws {

        let pixels = Data(repeating: 0, count: 8 * 8 * 4)
        let chain = try Mipmap.build(
            bytes: pixels,
            format: .rgba8UnormSrgb,
            size: Size(width: 8, height: 8, depth: nil)
        )
        let levelZeroBytes = try chain.level(index: 0)
        let _ = levelZeroBytes
    }

    static func _example_texture_mipmap_size() async throws {

        let pixels = Data(repeating: 0, count: 16 * 16 * 4)
        let chain = try Mipmap.build(
            bytes: pixels,
            format: .rgba8UnormSrgb,
            size: Size(width: 16, height: 16, depth: nil)
        )
        let sz = chain.size()
        let width = sz.width
        let height = sz.height
        let _ = (width, height)
    }

    static func _example_texture_texture_Texture() async throws {

        let renderer = Renderer()
        let shader = try Shader("""
        @group(0) @binding(0) var my_texture: texture_2d<f32>
        @group(0) @binding(1) var my_sampler: sampler
        @vertex fn vs_main(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
          let p = array<vec2<f32>,3>(vec2f(-1.,-1.), vec2f(3.,-1.), vec2f(-1.,3.))
          return vec4f(p[i], 0., 1.)
        }
        @fragment fn main() -> @location(0) vec4<f32> { return vec4f(1.,1.,1.,1.); }

        """)

        // 1x1 white pixel. Passing a size tells create_texture to read the bytes
        // as raw pixels; the default format is Rgba (sRGB-aware).
        let pixels = [255, 255, 255, 255]
        let texture = try await renderer.createTexture((pixels, [1, 1]))

        // Bind the texture to the uniform name declared in WGSL.
        try shader.set("my_texture", texture)
    }

    static func _example_texture_texture_aspect() async throws {


        let renderer = Renderer()
        // 1x1 RGBA (white) raw pixel bytes
        let pixels = [255,255,255,255]
        let tex = try await renderer.createTexture((pixels, [1, 1]))
        let a = tex.aspect()
    }

    static func _example_texture_texture_get_image() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 64], TextureFormat.rgba))
        try texture.write(Array(repeating: 0, count: 64 * 64 * 4))

        let bytes = try await texture.getImage()
    }

    static func _example_texture_texture_id() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 64], TextureFormat.rgba))
        let id = texture.id()
    }

    static func _example_texture_texture_set_sampler_options() async throws {

        let renderer = Renderer()
        let pixels: [UInt8] = [255, 255, 255, 255]
        let options = TextureOptions(
            size: Size(width: 1, height: 1, depth: nil),
            format: .rgba8UnormSrgb,
            sampler: SamplerOptions(repeatX: false, repeatY: false, smooth: true, compare: nil),
            mipmaps: false,
            usage: nil
        )
        let texture = try await renderer.createTexture(input: .bytes(pixels), options: options)

        let opts = SamplerOptions(repeatX: true, repeatY: true, smooth: true, compare: nil)
        texture.setSamplerOptions(opts: opts)
    }

    static func _example_texture_texture_size() async throws {
        let renderer = Renderer()
        let pixels = [255,255,255,255]
        let tex = try await renderer.createTexture((pixels, [1, 1]))
        let sz = tex.size()
    }

    static func _example_texture_texture_write() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 64], TextureFormat.rgba))
        let frame_bytes = Array(repeating: 0, count: 64 * 64 * 4)

        try texture.write(frame_bytes)
    }

    static func _example_texture_texture_write_region() async throws {
        let renderer = Renderer()
        let texture = try await renderer.createStorageTexture(([64, 32], TextureFormat.rgba))
        let bytes = Array(repeating: 0, count: 64 * 32 * 4)

        // Simple sub-rectangle update.
        try texture.writeRegion(bytes, [0, 0, 64, 32])

        // Explicit data layout (advanced — when source rows are padded).
        let region = TextureRegionMobile.from([0, 0, 64, 32]).withStride(256).withRows(32)
        try texture.writeRegion(bytes, region)
    }

}
