package org.fragmentcolor

// AUTO-GENERATED by build.rs (scripts/website.rs). DO NOT EDIT.
//
// Compile-only aggregator for every transpiled Kotlin example under
// `platforms/kotlin/examples/`. Each function below embeds the body
// of one example so kotlinc type-checks it during
// `connectedAndroidTest`. Functions are never invoked at runtime —
// wiring up GPU-backed runtime execution is a follow-up task.
//
// A failure here means either:
//  (a) the source `docs/api/**.md` example uses a Rust API that
//      `scripts/convert.rs::to_kotlin` cannot map, or
//  (b) the example references an item that uniffi does not export
//      to Kotlin.
// Fix the source — this file is regenerated on every cargo build.

import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class GeneratedExamples {
    @Test
    fun compileGeneratedExamples() {
        // Empty body. The value of this test is that all wrappers
        // below are type-checked at compile time.
    }

    @Suppress("unused") private suspend fun _example_core_pass_Pass() {


        val renderer = Renderer()
        // HEADLESS: canvas creation not needed on Android
        val target = renderer.createTextureTarget(800u, 600u)
        val shader = Shader.default()

        val pass = Pass("First Pass")
        pass.addShader(shader)

        val pass2 = Pass("Second Pass")
        pass2.addShader(shader)

        // standalone
        renderer.render(pass, target)

        // vector of passes rendered in order (any iterable of Pass is renderable)
        renderer.render(listOf(pass, pass2), target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_add() {

        val renderer = Renderer()

        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.5f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 0.0f, 1.0f)).set(Vertex.UV0, listOf(0.5f, 1.0f)), )
        val model = Model(mesh, Material.pbr()?)

        val camera = Camera.perspective(60.0.toRadians(), 1.0, 0.1, 100.0).lookAt(listOf(0.0f, 0.0f, 2.0f), listOf(0.0f, 0.0f, 0.0f), listOf(0.0f, 1.0f, 0.0f))
        val sun = Light.directional(listOf(0.3f, -1.0f, -0.4f), listOf(1.0f, 0.95f, 0.9f))

        val pass = Pass("scene")
        pass.add(model)?.add(camera)?.add(sun)

        // Updating the camera later is enough — every Model already on the pass
        // picks the view_proj up at the next render.
        camera.lookAt(listOf(3.0f, 1.0f, 5.0f), listOf(0.0f, 0.0f, 0.0f), listOf(0.0f, 1.0f, 0.0f))
    }

    @Suppress("unused") private suspend fun _example_core_pass_add_depth_target() {

        val renderer = Renderer()
        val target = renderer.createTextureTarget(64u, 64u)

        // One depth attachment shared across the 3D-content pass.
        val depth = renderer.createDepthTexture(64u, 64u)

        val mesh = Mesh()
        mesh.addVertex(Vertex(listOf(0.0f, 0.0f, 0.0f)))
        mesh.addVertex(Vertex(listOf(1.0f, 0.0f, 0.0f)))
        mesh.addVertex(Vertex(listOf(0.0f, 1.0f, 0.0f)))
        mesh.addVertex(Vertex(listOf(1.0f, 1.0f, 0.0f)))
        val shader = Shader.fromMesh(mesh)
        val pass = Pass("blobs"); pass.addShader(shader)

        // Depth-test on — closer fragments win, the pass writes to the depth
        // buffer so subsequent draws within the same pass see the depth.
        pass.addDepthTarget(depth)

        renderer.render(pass, target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_add_mesh() {

        val mesh = Mesh()
        mesh.addVertex(Vertex(listOf(0.0f, 0.0f)))

        val shader = Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        val pass = Pass("pass"); pass.addShader(shader)

        pass.addMesh(mesh)
    }

    @Suppress("unused") private suspend fun _example_core_pass_add_shader() {

        val shader = Shader.default()
        val pass = Pass("p")
        pass.addShader(shader)
    }

    @Suppress("unused") private suspend fun _example_core_pass_add_target() {

        val r = Renderer()
        val tex_target = r.createTextureTarget(512u, 512u)

        val p = Pass("shadow")
        p.addTarget(tex_target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_compute() {

        val cs = Shader("@compute @workgroup_size(8,8,1) fn cs_main() {}")
        val pass = Pass("compute"); pass.addShader(cs)
    }

    @Suppress("unused") private suspend fun _example_core_pass_from_shader() {

        val shader = Shader.default()
        val pass = Pass("single"); pass.addShader(shader)
    }

    @Suppress("unused") private suspend fun _example_core_pass_get_input() {

        val pass = Pass("example")
        val input = pass.getInput()
    }

    @Suppress("unused") private suspend fun _example_core_pass_is_compute() {

        val shader = Shader("""
        @compute @workgroup_size(1)
        fn cs_main() { }

        """)
        val pass = Pass("p"); pass.addShader(shader)

        // Call the method
        val is_compute = pass.isCompute()
    }

    @Suppress("unused") private suspend fun _example_core_pass_load_previous() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(64u, 64u)

        val shader = Shader.default()
        val pass = Pass("blend with previous")
        pass.addShader(shader)
        pass.loadPrevious()

        renderer.render(pass, target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_new() {

        val pass = Pass("first pass")
    }

    @Suppress("unused") private suspend fun _example_core_pass_require() {
        val renderer = Renderer()
        val target = renderer.createTextureTarget(100u, 100u)
        val color = Pass("color")
        val blurx = Pass("blur_x")
        blurx.require(color); // color before blur_x
        val blury = Pass("blur_y")
        blury.require(blurx); // blur_x before blur_y
        val compose = Pass("compose")
        compose.require(color)
        compose.require(blury); // fan-in; color and blur_y before compose
        renderer.render(compose, target); // compose renders last
    }

    @Suppress("unused") private suspend fun _example_core_pass_set_clear_color() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(64u, 64u)

        val shader = Shader.default()
        val pass = Pass("solid background")
        pass.addShader(shader)

        pass.setClearColor(listOf(0.1f, 0.2f, 0.3f, 1.0f))

        renderer.render(pass, target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_set_compute_dispatch() {
        val cs = Shader("@compute @workgroup_size(8,8,1) fn cs_main() {}")
        val pass = Pass("compute"); pass.addShader(cs)
        pass.setComputeDispatch(64u,64u,1u)
    }

    @Suppress("unused") private suspend fun _example_core_pass_set_viewport() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(64u, 64u)

        val shader = Shader.default()
        val pass = Pass("clipped")
        pass.addShader(shader)

        pass.setViewport(ScreenRegion(minX=0u, minY=0u, maxX=32u, maxY=32u))

        renderer.render(pass, target)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_Renderer() {


        val renderer = Renderer()

        // Use your platform's windowing system to create a window
        // HEADLESS: canvas creation not needed on Android

        // Create a Target from it
        val target = renderer.createTextureTarget(800u, 600u)
        val texture_target = renderer.createTextureTarget(16u, 16u)

        // RENDERING
        renderer.render(Shader(""), texture_target)

        // That's it. Welcome to FragmentColor!
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_depth_texture() {
        val r = Renderer()
        val depth = r.createDepthTexture(800u, 600u)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_external_texture() {
        // Once supported:
        //   val renderer = Renderer()
        //   val surfaceTexture: SurfaceTexture = /* from MediaCodec / Camera2 */
        //   val ptr: ULong = surfaceTexture.nativeHandle()  // hypothetical helper
        //   val handle = renderer.createExternalTexture(ptr)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_storage_texture() {

        val r = Renderer()

        // Empty storage texture.
        val tex = r.createStorageTexture(Size(width=64u, height=64u, depth=null), TextureFormat.RGBA, null, null)

        // Pre-seeded with bytes.
        val pixels = ByteArray(64 * 64 * 4)
        val tex2 = r.createStorageTexture(Size(width=64u, height=64u, depth=null), TextureFormat.RGBA, pixels, null)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_target() {


        val renderer = Renderer()

        // Use your platform's windowing system to create a window.
        // HEADLESS: canvas creation not needed on Android

        val target = renderer.createTextureTarget(800u, 600u)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_texture() {
        val renderer = Renderer()
        val image = "/healthcheck/public/favicon.png"
        val tex = renderer.createTexture(TextureInputMobile.Path(image), null)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_texture_target() {

        val renderer = Renderer()

        // Create an offscreen texture target with a size of 64x64 pixels.
        val target = renderer.createTextureTarget(64u, 64u)

        renderer.render(Shader(""), target)

        // get the rendered image
        val image = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_core_renderer_new() {


        val renderer = Renderer()
        val texture_target = renderer.createTextureTarget(16u, 16u)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_read_texture() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture(Size(width=64u, height=64u, depth=null), TextureFormat.RGBA, null, null)
        texture.write(ByteArray(64 * 64 * 4))

        val bytes = renderer.readTexture(texture.id())
    }

    @Suppress("unused") private suspend fun _example_core_renderer_render() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(10u, 10u)
        val shader = Shader.default()

        renderer.render(shader, target)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_unregister_texture() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture(Size(width=16u, height=16u, depth=null), TextureFormat.RGBA, null, null)
        val id = texture.id()

        renderer.unregisterTexture(id)
    }

    @Suppress("unused") private suspend fun _example_core_shader_Shader() {


        val shader = Shader("""
            @vertex
            fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
                var pos = array<vec2<f32>, 3>(
                    vec2<f32>(-1.0, -1.0),
                    vec2<f32>( 3.0, -1.0),
                    vec2<f32>(-1.0,  3.0)
                )
                return vec4<f32>(pos[index], 0.0, 1.0)
            }

            @group(0) @binding(0)
            var<uniform> resolution: vec2<f32>

            @fragment
            fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
            }

        """)

        // Set the "resolution" uniform
        shader.set("resolution", floatArrayOf(800.0f, 600.0f))
        val res = shader.get("resolution")

        val renderer = Renderer()
        val target = renderer.createTextureTarget(16u, 16u)
        renderer.render(shader, target)
    }

    @Suppress("unused") private suspend fun _example_core_shader_add_mesh() {

        val shader = Shader("""
          @vertex fn vs_main(@location(0) pos: vec3<f32>) -> @builtin(position) vec4<f32> {
            return vec4<f32>(pos, 1.0)
          }
          @fragment fn fs_main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        val mesh = Mesh()
        mesh.addVertex(Vertex(listOf(0.0f, 0.0f, 0.0f)))

        // Attach mesh to this shader (errors if incompatible)
        shader.addMesh(mesh)

        // Renderer will draw the mesh when rendering this pass.
        // Each Shader represents a RenderPipeline or ComputePipeline
        // in the GPU. Adding multiple meshes to it will draw all meshes
        // and all its instances in the same Pipeline.
    }

    @Suppress("unused") private suspend fun _example_core_shader_clear_meshes() {

        val shader = Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        val mesh = Mesh()
        mesh.addVertex(Vertex(listOf(0.0f, 0.0f)))
        shader.addMesh(mesh)

        // Clear all
        shader.clearMeshes()
    }

    @Suppress("unused") private suspend fun _example_core_shader_fetch() {


        // Full registry URL.
        val shader = Shader.fetch("https://fragmentcolor.org/shaders/sdf2d/circle.wgsl")

        // Equivalent shorthand using the registry slug.
        val shader2 = Shader.fetch("sdf2d/circle")
    }

    @Suppress("unused") private suspend fun _example_core_shader_from_mesh() {

        val mesh = Mesh()
        mesh.addVertex(Vertex(listOf(0.0f, 0.0f, 0.0f)))
        val shader = Shader.fromMesh(mesh)
    }

    @Suppress("unused") private suspend fun _example_core_shader_from_vertex() {

        val vertex = Vertex(listOf(0.0f, 0.0f, 0.0f))
        val shader = Shader.fromVertex(vertex)
    }

    @Suppress("unused") private suspend fun _example_core_shader_get() {

        val shader = Shader.default()
        shader.set("resolution", floatArrayOf(800.0f, 600.0f))
        val res = shader.get("resolution")
    }

    @Suppress("unused") private suspend fun _example_core_shader_is_compute() {

        val shader = Shader("""
        @compute @workgroup_size(1)
        fn cs_main() { }

        """)

        // Call the method
        val is_compute = shader.isCompute()
    }

    @Suppress("unused") private suspend fun _example_core_shader_list_keys() {


        val shader = Shader.default()
        val keys = shader.listKeys()
    }

    @Suppress("unused") private suspend fun _example_core_shader_list_uniforms() {

        val shader = Shader.default()
        val list = shader.listUniforms()
    }

    @Suppress("unused") private suspend fun _example_core_shader_new() {


        val shader = Shader("""
            @vertex
            fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
                var pos = array<vec2<f32>, 3>(
                    vec2<f32>(-1.0, -1.0),
                    vec2<f32>( 3.0, -1.0),
                    vec2<f32>(-1.0,  3.0)
                )
                return vec4<f32>(pos[index], 0.0, 1.0)
            }

            @group(0) @binding(0)
            var<uniform> resolution: vec2<f32>

            @fragment
            fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
            }

        """)


        val main = """
            @vertex fn vs(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
                let p = array<vec2<f32>,3>(vec2f(-1.,-1.), vec2f(3.,-1.), vec2f(-1.,3.))
                return vec4<f32>(p[i], 0.0, 1.0)
            }

            @fragment fn fs(@builtin(position) pos: vec4<f32>) -> @location(0) vec4<f32> {
                let d = circle(pos.xy - vec2<f32>(400.0, 300.0), 100.0)
                let n = simplex2(pos.xy * 0.01)
                return vec4<f32>(vec3<f32>(step(0.0, d) + n * 0.1), 1.0)
            }

        """

        val shader2 = Shader.compose(listOf("sdf2d/circle", "noise/simplex2", main,))
    }

    @Suppress("unused") private suspend fun _example_core_shader_remove_mesh() {

        val shader = Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        val mesh = Mesh()
        mesh.addVertex(Vertex(listOf(0.0f, 0.0f)))
        shader.addMesh(mesh)

        // Detach the mesh
        shader.removeMesh(mesh)
    }

    @Suppress("unused") private suspend fun _example_core_shader_remove_meshes() {

        val shader = Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        val m1 = Mesh()
        m1.addVertex(Vertex(listOf(0.0f, 0.0f)))
        val m2 = Mesh()
        m2.addVertex(Vertex(listOf(0.5f, 0.0f)))

        shader.addMesh(m1)
        shader.addMesh(m2)

        shader.removeMeshes(listOf(m1, m2))
    }

    @Suppress("unused") private suspend fun _example_core_shader_set() {
        val r = Renderer()
        val shader = Shader("""
        @group(0) @binding(0) var<uniform> resolution: vec2<f32>

        struct VOut { @builtin(position) pos: vec4<f32> }
        @vertex fn vs_main(@builtin(vertex_index) i: u32) -> VOut {
          var p = array<vec2<f32>, 3>(vec2<f32>(-1.,-1.), vec2<f32>(3.,-1.), vec2<f32>(-1.,3.))
          var out: VOut
          out.pos = vec4<f32>(p[i], 0., 1.)
          return out
        }
        @fragment fn main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        // Set scalars/vectors on declared uniforms
        shader.set("resolution", floatArrayOf(800.0f, 600.0f))
    }

    @Suppress("unused") private suspend fun _example_core_shader_set_registry() {


        // Point at your own mirror of the registry
        Shader.setRegistry("https://cdn.example.com/shaders/")

        // Now the slug "sdf2d/circle" resolves to https://cdn.example.com/shaders/sdf2d/circle.wgsl
        // (Skipping the actual fetch in this doctest)
    }

    @Suppress("unused") private suspend fun _example_core_shader_validate_mesh() {

        val shader = Shader("""
        struct VOut { @builtin(position) pos: vec4<f32> }
        @vertex fn vs_main(@location(0) pos: vec3<f32>) -> VOut {
          var out: VOut
          out.pos = vec4<f32>(pos, 1.0)
          return out
        }
        @fragment fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)
        val pass = Pass("p"); pass.addShader(shader)

        val mesh = Mesh()
        mesh.addVertices(listOf(Vertex(listOf(-0.5f, -0.5f, 0.0f)), Vertex(listOf(0.5f, -0.5f, 0.0f)), Vertex(listOf(0.0f, 0.5f, 0.0f))))

        shader.validateMesh(mesh); // Ok
        pass.addMesh(mesh)
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_Mesh() {

        val mesh = Mesh()
        mesh.addVertex(Vertex(listOf(0.0f, 0.5f, 0.0f)))
        mesh.addVertex(Vertex(listOf(-0.5f, -0.5f, 0.0f)))
        mesh.addVertex(Vertex(listOf(0.5f, -0.5f, 0.0f)))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_add_instance() {

        val m = Mesh()
        val offset = listOf(0.25f, 0.10f)
        val tint = listOf(1.0f, 0.0f, 0.0f, 1.0f)
        m.addInstance(Instance().set("offset", offset).set("tint", tint))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_add_instances() {

        val m = Mesh()
        val red = listOf(1.0f, 0.0f, 0.0f, 1.0f)
        val green = listOf(0.0f, 1.0f, 0.0f, 1.0f)
        val blue = listOf(0.0f, 0.0f, 1.0f, 1.0f)
        m.addInstances(listOf(Instance().set("tint", red), Instance().set("tint", green), Instance().set("tint", blue),))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_add_vertex() {
        val m = Mesh()
        m.addVertex(Vertex(listOf(0.0f, 0.0f)))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_add_vertices() {
        val m = Mesh()
        m.addVertices(listOf(Vertex(listOf(0.0f, 0.0f)), Vertex(listOf(1.0f, 0.0f))))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_clear_indices() {

        val mesh = Mesh()
        mesh.addVertices(listOf(Vertex.new(listOf(-0.5f, -0.5f)), Vertex.new(listOf(0.5f, -0.5f)), Vertex.new(listOf(0.0f, 0.5f))))
        mesh.setIndices(listOf(0.0f, 1.0f, 2.0f))
        mesh.clearIndices(); // back to auto-derived dedup
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_clear_instances() {

        val m = Mesh()
        val red = listOf(1.0f, 0.0f, 0.0f, 1.0f)
        m.addInstance(Instance().set("tint", red))
        m.clearInstances(); // back to a single uninstanced draw
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_from_vertices() {

        val mesh = Mesh.fromVertices(listOf(Vertex(listOf(0.0f, 0.0f)), Vertex(listOf(1.0f, 0.0f)), Vertex(listOf(0.0f, 1.0f))))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_new() {
        val m = Mesh()
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_set_indices() {

        // A quad split into two triangles via explicit indexing. The four corners
        // happen to carry distinct UVs (only positions repeat), so we keep them
        // all and reference each by index.
        val mesh = Mesh()
        val uv00 = listOf(0.0f, 0.0f)
        val uv10 = listOf(1.0f, 0.0f)
        val uv11 = listOf(1.0f, 1.0f)
        val uv01 = listOf(0.0f, 1.0f)
        mesh.addVertices(listOf(Vertex.new(listOf(-0.5f, -0.5f)).set("uv", uv00), Vertex.new(listOf(0.5f, -0.5f)).set("uv", uv10), Vertex.new(listOf(0.5f, 0.5f)).set("uv", uv11), Vertex.new(listOf(-0.5f, 0.5f)).set("uv", uv01)))
        mesh.setIndices(listOf(0.0f, 1.0f, 2.0f, 0.0f, 2.0f, 3.0f))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_set_instance_count() {
        val m = Mesh()
        m.addVertices(listOf(Vertex(listOf(-0.01f, -0.01f)), Vertex(listOf(0.01f, -0.01f)), Vertex(listOf(0.00f, 0.01f))))
        // Draw one million instances, fetching per-particle data from a storage buffer.
        m.setInstanceCount(1_000_000u)
    }

    @Suppress("unused") private suspend fun _example_geometry_quad_Quad() {

        val quad = Quad(listOf(-0.5f, -0.5f), listOf(0.5f, 0.5f))
    }

    @Suppress("unused") private suspend fun _example_geometry_quad_get_mesh() {

        val quad = Quad(listOf(-0.5f, -0.5f), listOf(0.5f, 0.5f))
        val mesh = quad.getMesh()
    }

    @Suppress("unused") private suspend fun _example_geometry_quad_new() {

        val quad = Quad(listOf(-0.5f, -0.5f), listOf(0.5f, 0.5f))
    }

    @Suppress("unused") private suspend fun _example_geometry_vertex_Vertex() {
        val v = Vertex(listOf(0.0f, 0.0f, 0.0f)).set(Vertex.UV0, floatArrayOf(0.5f, 0.5f)).set(Vertex.NORMAL, listOf(0.0f, 1.0f, 0.0f))
    }

    @Suppress("unused") private suspend fun _example_geometry_vertex_create_instance() {
        val v = Vertex(listOf(0.0f, 0.0f))
        val inst = v.createInstance()
    }

    @Suppress("unused") private suspend fun _example_geometry_vertex_new() {
        val v = Vertex(listOf(0.0f, 0.0f))
    }

    @Suppress("unused") private suspend fun _example_geometry_vertex_set() {
        val v = Vertex(listOf(0.0f, 0.0f, 0.0f)).set("weight", 1.0).set("color", listOf(1.0f, 0.0f, 0.0f))
    }

    @Suppress("unused") private suspend fun _example_scene_camera_look_at() {

        val camera = Camera.perspective(60.0.toRadians(), 16.0 / 9.0, 0.1, 100.0).lookAt(listOf(0.0f, 1.0f, 5.0f), listOf(0.0f, 0.0f, 0.0f), listOf(0.0f, 1.0f, 0.0f))
    }

    @Suppress("unused") private suspend fun _example_scene_camera_orthographic() {

        // A 16:9 viewport, 10 world units tall, depth range 0.1..100.
        val camera = Camera.orthographic(-8.0, 8.0, -4.5, 4.5, 0.1, 100.0)
    }

    @Suppress("unused") private suspend fun _example_scene_camera_perspective() {

        val camera = Camera.perspective(60.0.toRadians(), 16.0 / 9.0, 0.1, 100.0)
    }

    @Suppress("unused") private suspend fun _example_scene_camera_position() {

        val camera = Camera.perspective(60.0.toRadians(), 16.0 / 9.0, 0.1, 100.0).lookAt(listOf(3.0f, 2.0f, 8.0f), listOf(0.0f, 0.0f, 0.0f), listOf(0.0f, 1.0f, 0.0f))

        val eye = camera.position()
    }

    @Suppress("unused") private suspend fun _example_scene_camera_view_proj() {

        val camera = Camera.perspective(60.0.toRadians(), 16.0 / 9.0, 0.1, 100.0).lookAt(listOf(0.0f, 0.0f, 5.0f), listOf(0.0f, 0.0f, 0.0f), listOf(0.0f, 1.0f, 0.0f))

        val m = camera.viewProj()
    }

    @Suppress("unused") private suspend fun _example_scene_light_color() {

        val warm = Light.directional(listOf(0.0f, -1.0f, 0.0f), listOf(1.0f, 0.85f, 0.7f))
        val color = warm.color()
    }

    @Suppress("unused") private suspend fun _example_scene_light_direction() {

        val sun = Light.directional(listOf(0.3f, -1.0f, -0.4f), listOf(1.0f, 1.0f, 1.0f))
        val dir = sun.direction()
    }

    @Suppress("unused") private suspend fun _example_scene_light_directional() {

        val sun = Light.directional(listOf(0.3f, -1.0f, -0.4f), listOf(1.0f, 0.95f, 0.9f))
    }

    @Suppress("unused") private suspend fun _example_scene_light_inner_cone_angle() {

        val torch = Light.spot(listOf(0.0f, 1.0f, 0.0f), listOf(0.0f, -1.0f, 0.0f), listOf(1.0f, 1.0f, 1.0f)).setConeAngles(0.2, 0.5)
        val inner = torch.innerConeAngle()
    }

    @Suppress("unused") private suspend fun _example_scene_light_intensity() {

        val lamp = Light.point(listOf(0.0f, 1.0f, 0.0f), listOf(1.0f, 0.95f, 0.8f)).setIntensity(12.0)
        val scale = lamp.intensity()
    }

    @Suppress("unused") private suspend fun _example_scene_light_outer_cone_angle() {

        val torch = Light.spot(listOf(0.0f, 1.0f, 0.0f), listOf(0.0f, -1.0f, 0.0f), listOf(1.0f, 1.0f, 1.0f)).setConeAngles(0.2, 0.5)
        val outer = torch.outerConeAngle()
    }

    @Suppress("unused") private suspend fun _example_scene_light_point() {

        val bulb = Light.point(listOf(0.0f, 2.5f, 0.0f), listOf(1.0f, 0.95f, 0.8f)).setIntensity(15.0)
    }

    @Suppress("unused") private suspend fun _example_scene_light_position() {

        val bulb = Light.point(listOf(3.0f, 2.5f, -1.0f), listOf(1.0f, 1.0f, 1.0f))
        val pos = bulb.position()
    }

    @Suppress("unused") private suspend fun _example_scene_light_range() {

        val bulb = Light.point(listOf(0.0f, 0.0f, 0.0f), listOf(1.0f, 1.0f, 1.0f)).setRange(8.0)
        val cutoff = bulb.range()
    }

    @Suppress("unused") private suspend fun _example_scene_light_set_color() {

        val lamp = Light.directional(listOf(0.0f, -1.0f, 0.0f), listOf(1.0f, 1.0f, 1.0f))
        // Warm-tinted bulb after the user toggles the warm-light switch.
        lamp.setColor(listOf(1.0f, 0.85f, 0.7f))
    }

    @Suppress("unused") private suspend fun _example_scene_light_set_cone_angles() {

        val torch = Light.spot(listOf(0.0f, 1.0f, 0.0f), listOf(0.0f, -1.0f, 0.0f), listOf(1.0f, 1.0f, 1.0f))
        torch.setConeAngles(0.15, 0.5)
    }

    @Suppress("unused") private suspend fun _example_scene_light_set_direction() {

        val sun = Light.directional(listOf(0.0f, -1.0f, 0.0f), listOf(1.0f, 1.0f, 1.0f))
        // Reorient to a late-afternoon angle.
        sun.setDirection(listOf(0.7f, -0.5f, -0.5f))
    }

    @Suppress("unused") private suspend fun _example_scene_light_set_intensity() {

        val lamp = Light.point(listOf(0.0f, 1.0f, 0.0f), listOf(1.0f, 0.95f, 0.8f))
        lamp.setIntensity(15.0)
    }

    @Suppress("unused") private suspend fun _example_scene_light_set_position() {

        val bulb = Light.point(listOf(0.0f, 0.0f, 0.0f), listOf(1.0f, 1.0f, 1.0f))
        bulb.setPosition(listOf(2.0f, 3.0f, -1.0f))
    }

    @Suppress("unused") private suspend fun _example_scene_light_set_range() {

        val bulb = Light.point(listOf(0.0f, 0.0f, 0.0f), listOf(1.0f, 1.0f, 1.0f))
        bulb.setRange(8.0)
    }

    @Suppress("unused") private suspend fun _example_scene_light_spot() {

        val torch = Light.spot(listOf(0.0f, 1.8f, 1.0f), listOf(0.0f, -0.3f, -1.0f), listOf(1.0f, 0.9f, 0.7f)).setIntensity(5.0).setConeAngles(0.15, 0.4)
    }

    @Suppress("unused") private suspend fun _example_scene_material_Material() {

        val renderer = Renderer()
        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.5f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 0.0f, 1.0f)).set(Vertex.UV0, listOf(0.5f, 1.0f)), )

        val material = Material.pbr()?.baseColor(listOf(0.85f, 0.2f, 0.2f, 1.0f)).metallic(0.0).roughness(0.4).emissive(listOf(0.0f, 0.0f, 0.05f))

        val model = Model(mesh, material)
    }

    @Suppress("unused") private suspend fun _example_scene_material_alpha_cutoff() {

        val renderer = Renderer()
        val foliage = Material.pbr()?.alphaCutoff(0.3)
    }

    @Suppress("unused") private suspend fun _example_scene_material_alpha_mode() {

        val renderer = Renderer()
        val foliage = Material.pbr()?.alphaMode(AlphaMode.Mask).alphaCutoff(0.3)

        val glass = Material.pbr()?.baseColor(listOf(0.9f, 0.95f, 1.0f, 0.25f)).alphaMode(AlphaMode.Blend)

        val solid = Material.pbr()?.alphaMode(AlphaMode.Opaque)
    }

    @Suppress("unused") private suspend fun _example_scene_material_base_color() {

        val renderer = Renderer()
        val red = Material.pbr()?.baseColor(listOf(1.0f, 0.2f, 0.2f, 1.0f))
    }

    @Suppress("unused") private suspend fun _example_scene_material_base_color_texture() {

        val renderer = Renderer()
        val texture = renderer.createTexture(arrayOf(255, 200, 120, 255, 255,  240, 180, 255, 230,  180, 100, 255, 255,  220, 150, 255, await))
        val mat = Material.pbr()?.baseColorTexture(texture)
    }

    @Suppress("unused") private suspend fun _example_scene_material_custom() {

        val wireframe = Shader("""
            struct MeshTransform { model: mat4x4<f32> }
            struct Camera { view_proj: mat4x4<f32>, position: vec3<f32> }
            @group(0) @binding(0) var<uniform> camera: Camera
            @group(1) @binding(0) var<uniform> mesh: MeshTransform

            @vertex
            fn vs_main(@location(0) p: vec3<f32>) -> @builtin(position) vec4<f32> {
                return camera.view_proj * mesh.model * vec4<f32>(p, 1.0)
            }
            @fragment fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(0.0, 1.0, 0.4, 1.0)
            }

        """)

        val wire_mat = Material.custom(wireframe)
    }

    @Suppress("unused") private suspend fun _example_scene_material_double_sided() {

        val renderer = Renderer()
        // Leaf cards: thin, single-quad geometry; needs both sides + alpha cut-out.
        val leaf = Material.pbr()?.doubleSided(true).alphaMode(AlphaMode.Mask).alphaCutoff(0.5)

        // Default is single-sided — back-face culling on.
        val solid_mesh = Material.pbr()?.doubleSided(false)
    }

    @Suppress("unused") private suspend fun _example_scene_material_emissive() {

        val renderer = Renderer()
        val lava = Material.pbr()?.baseColor(listOf(0.1f, 0.05f, 0.0f, 1.0f)).emissive(listOf(1.5f, 0.4f, 0.1f))
    }

    @Suppress("unused") private suspend fun _example_scene_material_emissive_texture() {

        val renderer = Renderer()
        val glow = renderer.createTexture(arrayOf(255, 0, 0, 255, 255,   0, 0, 255, 255,   0, 0, 255, 255,   0, 0, 255, await))
        val mat = Material.pbr()?.emissive(listOf(0.8f, 0.0f, 0.0f)).emissiveTexture(glow)
    }

    @Suppress("unused") private suspend fun _example_scene_material_metallic() {

        val renderer = Renderer()
        val chrome = Material.pbr()?.metallic(1.0).roughness(0.05)
    }

    @Suppress("unused") private suspend fun _example_scene_material_metallic_roughness_texture() {

        val renderer = Renderer()
        val mr_map = renderer.createTexture(arrayOf(0, 200, 50, 255, 0,   240, 80, 255, 0,   180, 30, 255, 0,   220, 60, 255, await))
        val mat = Material.pbr()?.metallicRoughnessTexture(mr_map)
    }

    @Suppress("unused") private suspend fun _example_scene_material_normal_scale() {

        val renderer = Renderer()
        val detailed = Material.pbr()?.normalScale(1.5)
    }

    @Suppress("unused") private suspend fun _example_scene_material_normal_texture() {

        val renderer = Renderer()
        val normal_map = renderer.createTexture(arrayOf(128, 128, 255, 255, 128,   128, 255, 255, 128,   128, 255, 255, 128,   128, 255, 255, await))
        val mat = Material.pbr()?.normalTexture(normal_map).normalScale(1.2)
    }

    @Suppress("unused") private suspend fun _example_scene_material_occlusion_strength() {

        val renderer = Renderer()
        val crevices = Material.pbr()?.occlusionStrength(0.8)
    }

    @Suppress("unused") private suspend fun _example_scene_material_occlusion_texture() {

        val renderer = Renderer()
        val ao = renderer.createTexture(arrayOf(220, 0, 0, 255, 180,   0, 0, 255, 200,   0, 0, 255, 160,   0, 0, 255, await))
        val mat = Material.pbr()?.occlusionTexture(ao)
    }

    @Suppress("unused") private suspend fun _example_scene_material_pbr() {

        val renderer = Renderer()
        val bronze = Material.pbr()?.baseColor(listOf(0.8f, 0.5f, 0.2f, 1.0f)).metallic(1.0).roughness(0.3)
    }

    @Suppress("unused") private suspend fun _example_scene_material_roughness() {

        val renderer = Renderer()
        val satin = Material.pbr()?.roughness(0.35)
    }

    @Suppress("unused") private suspend fun _example_scene_material_shader() {

        // Direct uniform access for a custom field that isn't covered by the
        // Material setters or by Camera / Light.
        val renderer = Renderer()
        val material = Material.pbr()
        material.shader().set("material.alphaCutoff", 0.25)
    }

    @Suppress("unused") private suspend fun _example_scene_model_material() {

        val renderer = Renderer()
        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.0f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 1.0f, 0.0f)).set(Vertex.UV0, listOf(0.0f, 0.0f)), )

        val model = Model(mesh, Material.pbr()?)
        model.material().shader().set("camera.position", floatArrayOf(0.0f, 0.0f, 5.0f))
    }

    @Suppress("unused") private suspend fun _example_scene_model_mesh() {

        val renderer = Renderer()
        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.5f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 0.0f, 1.0f)).set(Vertex.UV0, listOf(0.5f, 1.0f)), )

        val model = Model(mesh, Material.pbr()?)
        model.mesh().addVertex( Vertex.new(listOf(-0.5f, -0.5f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 0.0f, 1.0f)).set(Vertex.UV0, listOf(0.0f, 0.0f)), )
    }

    @Suppress("unused") private suspend fun _example_scene_model_new() {

        val renderer = Renderer()
        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.0f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 1.0f, 0.0f)).set(Vertex.UV0, listOf(0.0f, 0.0f)), )

        val model = Model(mesh, Material.pbr()?)
    }

    @Suppress("unused") private suspend fun _example_scene_model_rotate() {

        val renderer = Renderer()
        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.0f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 1.0f, 0.0f)).set(Vertex.UV0, listOf(0.0f, 0.0f)), )

        val model = Model(mesh, Material.pbr()?)
        model.rotate(listOf(0.0f, 1.0f, 0.0f), std.f32.consts.FRACPI2)
    }

    @Suppress("unused") private suspend fun _example_scene_model_scale() {

        val renderer = Renderer()
        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.0f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 1.0f, 0.0f)).set(Vertex.UV0, listOf(0.0f, 0.0f)), )

        val model = Model(mesh, Material.pbr()?)
        model.scale(listOf(2.0f, 2.0f, 2.0f))
    }

    @Suppress("unused") private suspend fun _example_scene_model_set_transform() {

        val renderer = Renderer()
        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.0f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 1.0f, 0.0f)).set(Vertex.UV0, listOf(0.0f, 0.0f)), )

        val model = Model(mesh, Material.pbr()?)
        model.setTransform(arrayOf(listOf(2.0f, 0.0f, 0.0f, 0.0f), listOf(0.0f, 2.0f, 0.0f, 0.0f), listOf(0.0f, 0.0f, 2.0f, 0.0f), listOf(3.0f, 0.0f, 0.0f, 1.0f),))
    }

    @Suppress("unused") private suspend fun _example_scene_model_transform() {

        val renderer = Renderer()
        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.0f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 1.0f, 0.0f)).set(Vertex.UV0, listOf(0.0f, 0.0f)), )

        val model = Model(mesh, Material.pbr()?)
        val identity = model.transform()
    }

    @Suppress("unused") private suspend fun _example_scene_model_translate() {

        val renderer = Renderer()
        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.0f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 1.0f, 0.0f)).set(Vertex.UV0, listOf(0.0f, 0.0f)), )

        val model = Model(mesh, Material.pbr()?)
        model.translate(listOf(5.0f, 0.0f, -2.0f))
    }

    @Suppress("unused") private suspend fun _example_scene_scene_add() {

        val renderer = Renderer()

        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.5f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 0.0f, 1.0f)).set(Vertex.UV0, listOf(0.5f, 1.0f)), )
        val model = Model(mesh, Material.pbr()?)

        val camera = Camera.perspective(60.0.toRadians(), 1.0, 0.1, 100.0).lookAt(listOf(0.0f, 0.0f, 3.0f), listOf(0.0f, 0.0f, 0.0f), listOf(0.0f, 1.0f, 0.0f))
        val sun = Light.directional(listOf(0.3f, -1.0f, -0.4f), listOf(1.0f, 0.95f, 0.9f))

        val scene = Scene()
        scene.add(model)?.add(camera)?.add(sun)

        // Updating the camera later is enough — every shader on the scene picks
        // the view_proj up at the next render.
        camera.lookAt(listOf(3.0f, 1.0f, 5.0f), listOf(0.0f, 0.0f, 0.0f), listOf(0.0f, 1.0f, 0.0f))
    }

    @Suppress("unused") private suspend fun _example_scene_scene_add_pass() {

        val renderer = Renderer()

        val mesh = Mesh()
        mesh.addVertex( Vertex.new(listOf(0.0f, 0.5f, 0.0f)).set(Vertex.NORMAL, floatArrayOf(0.0f, 0.0f, 1.0f)).set(Vertex.UV0, listOf(0.5f, 1.0f)), )
        val model = Model(mesh, Material.pbr()?)

        // A backdrop pass that clears to a soft blue before the scene's main draw.
        val backdrop = Pass("backdrop")
        backdrop.setClearColor(listOf(0.05f, 0.08f, 0.12f, 1.0f))

        val scene = Scene()
        scene.addPass(backdrop)
        scene.add(model)
    }

    @Suppress("unused") private suspend fun _example_scene_scene_new() {

        val scene = Scene()
        // scene is empty; add Models / Cameras / Lights with """scene.add(...)""".
    }

    @Suppress("unused") private suspend fun _example_targets_target_Target() {


        val renderer = Renderer()

        // Use your platform's windowing system to create a window.
        // HEADLESS: canvas creation not needed on Android

        val target = renderer.createTextureTarget(800u, 600u)

        // To animate, render again in your event loop...
        renderer.render(Shader(""), target)
        renderer.render(Shader(""), target)
    }

    @Suppress("unused") private suspend fun _example_targets_target_get_image() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(16u, 16u)
        renderer.render(Shader(""), target)

        val image = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_targets_target_resize() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(64u, 32u)

        target.resize(128u, 64u)
    }

    @Suppress("unused") private suspend fun _example_targets_target_size() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(64u, 32u)
        val size = target.size()
        val width = size.width
        val height = size.height
        val depth = size.depth
    }

    @Suppress("unused") private suspend fun _example_targets_texture_target_TextureTarget() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(64u, 64u)

        val shader = Shader.default()
        renderer.render(shader, target)

        val image = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_targets_texture_target_texture() {

        val renderer = Renderer()
        val target = renderer.createTextureTarget(256u, 256u)

        // Bind the offscreen target's contents as a uniform on a downstream
        // post-processing shader.
        val post = Shader("""
            @group(0) @binding(0) var input_image : texture_2d<f32>
            @group(0) @binding(1) var input_sampler : sampler

            @vertex fn vs_main(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
                let p = array<vec2<f32>, 3>(vec2f(-1.0,-1.0), vec2f(3.0,-1.0), vec2f(-1.0,3.0))
                return vec4<f32>(p[i], 0.0, 1.0)
            }
            @fragment fn fs_main(@builtin(position) pos: vec4<f32>) -> @location(0) vec4<f32> {
                return textureSample(input_image, input_sampler, vec2<f32>(0.5, 0.5))
            }

        """)
        post.set("input_image", target.texture())
    }

    @Suppress("unused") private suspend fun _example_targets_window_target_WindowTarget() {


        // Use your platform's windowing system to create a window.
        // HEADLESS: canvas creation not needed on Android

        val renderer = Renderer()
        val target = renderer.createTextureTarget(800u, 600u)

        renderer.render(Shader(""), target)
    }

    @Suppress("unused") private suspend fun _example_targets_window_target_get_image() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(16u, 16u)
        renderer.render(Shader(""), target)

        val image = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_targets_window_target_resize() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(64u, 32u)

        target.resize(128u, 64u)
    }

    @Suppress("unused") private suspend fun _example_targets_window_target_size() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(64u, 32u)
    }

    @Suppress("unused") private suspend fun _example_texture_mipmap_Mipmap() {

        // Imagine """png""" came off your asset loader on a worker thread.

        // Decode + mipmap generation. Pure CPU; run it wherever you like.
        val chain = Mipmap.build(png, TextureFormat.RGBA8_UNORM_SRGB, null)

        // Back on the renderer thread, the upload is just a GPU write.
        val renderer = Renderer()
        val texture = renderer.createTexture(TextureInputMobile.Prepared(chain), null)
    }

    @Suppress("unused") private suspend fun _example_texture_mipmap_build() {


        // Encoded path: bytes plus the format you want the chain to live in.
        // The dimensions come from the decoded image.
        val encoded_png_bytes: ByteArray = byteArrayOf()
        val chain = Mipmap.build(encoded_png_bytes, TextureFormat.RGBA8_UNORM_SRGB, null)

        // Raw path: include the size so build skips decoding.
        val raw_rgba: ByteArray = ByteArray(8 * 8 * 4)
        val chain_raw = Mipmap.build(raw_rgba, TextureFormat.RGBA8_UNORM_SRGB, Size(width=8u, height=8u, depth=null))

        // Either chain uploads the same way.
        val renderer = Renderer()
        val texture = renderer.createTexture(TextureInputMobile.Prepared(chain), null)
    }

    @Suppress("unused") private suspend fun _example_texture_mipmap_count() {

        val pixels = ByteArray(8 * 8 * 4)
        val chain = Mipmap.build(pixels, TextureFormat.RGBA8_UNORM_SRGB, Size(width=8u, height=8u, depth=null))
        val count = chain.count()
    }

    @Suppress("unused") private suspend fun _example_texture_mipmap_format() {

        val pixels = ByteArray(4 * 4 * 4)
        val chain = Mipmap.build(pixels, TextureFormat.RGBA8_UNORM_SRGB, Size(width=4u, height=4u, depth=null))
    }

    @Suppress("unused") private suspend fun _example_texture_mipmap_levels() {

        val pixels = ByteArray(8 * 8 * 4)
        val chain = Mipmap.build(pixels, TextureFormat.RGBA8_UNORM_SRGB, Size(width=8u, height=8u, depth=null))
        val level_zero_bytes = chain.level(0u)
    }

    @Suppress("unused") private suspend fun _example_texture_mipmap_size() {

        val pixels = ByteArray(16 * 16 * 4)
        val chain = Mipmap.build(pixels, TextureFormat.RGBA8_UNORM_SRGB, Size(width=16u, height=16u, depth=null))
        val tmp_size = chain.size()
        val width = tmp_size.width
        val height = tmp_size.height
    }

    @Suppress("unused") private suspend fun _example_texture_texture_Texture() {

        val renderer = Renderer()
        val shader = Shader("""
        @group(0) @binding(0) var my_texture: texture_2d<f32>
        @group(0) @binding(1) var my_sampler: sampler
        @vertex fn vs_main(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
          let p = array<vec2<f32>,3>(vec2f(-1.,-1.), vec2f(3.,-1.), vec2f(-1.,3.))
          return vec4f(p[i], 0., 1.)
        }
        @fragment fn main() -> @location(0) vec4<f32> { return vec4f(1.,1.,1.,1.); }

        """)

        // 1x1 white pixel. Passing a size tells create_texture to read the bytes
        // as raw pixels; the default format is Rgba (sRGB-aware).
        val pixels = listOf(255.0f, 255.0f, 255.0f, 255.0f)
        val texture = renderer.createTexture(TextureInputMobile.Bytes(pixels.let { ba -> ByteArray(ba.size) { i -> ba[i].toInt().and(0xFF).toByte() } }), null)

        // Bind the texture to the uniform name declared in WGSL.
        shader.set("my_texture", texture)
    }

    @Suppress("unused") private suspend fun _example_texture_texture_aspect() {


        val renderer = Renderer()
        // 1x1 RGBA (white) raw pixel bytes
        val pixels = listOf(255.0f, 255.0f, 255.0f, 255.0f)
        val tex = renderer.createTexture(TextureInputMobile.Bytes(pixels.let { ba -> ByteArray(ba.size) { i -> ba[i].toInt().and(0xFF).toByte() } }), null)
        val a = tex.aspect()
    }

    @Suppress("unused") private suspend fun _example_texture_texture_get_image() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture(Size(width=64u, height=64u, depth=null), TextureFormat.RGBA, null, null)
        texture.write(ByteArray(64 * 64 * 4))

        val bytes = texture.getImage()
    }

    @Suppress("unused") private suspend fun _example_texture_texture_id() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture(Size(width=64u, height=64u, depth=null), TextureFormat.RGBA, null, null)
        val id = texture.id()
    }

    @Suppress("unused") private suspend fun _example_texture_texture_set_sampler_options() {

        val renderer = Renderer()
        val pixels: ByteArray = byteArrayOf(255.toByte(), 255.toByte(), 255.toByte(), 255.toByte())
        val options = TextureOptions(
            size = Size(width = 1u, height = 1u, depth = null),
            format = TextureFormat.RGBA8_UNORM_SRGB,
            sampler = SamplerOptions(repeatX = false, repeatY = false, smooth = true, compare = null),
            mipmaps = false,
            usage = null,
        )
        val texture = renderer.createTexture(TextureInputMobile.Bytes(pixels), options)

        val opts = SamplerOptions(repeatX = true, repeatY = true, smooth = true, compare = null)
        texture.setSamplerOptions(opts)
    }

    @Suppress("unused") private suspend fun _example_texture_texture_size() {
        val renderer = Renderer()
        val pixels = listOf(255.0f, 255.0f, 255.0f, 255.0f)
        val tex = renderer.createTexture(TextureInputMobile.Bytes(pixels.let { ba -> ByteArray(ba.size) { i -> ba[i].toInt().and(0xFF).toByte() } }), null)
        val sz = tex.size()
    }

    @Suppress("unused") private suspend fun _example_texture_texture_write() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture(Size(width=64u, height=64u, depth=null), TextureFormat.RGBA, null, null)
        val frame_bytes = ByteArray(64 * 64 * 4)

        texture.write(frame_bytes)
    }

    @Suppress("unused") private suspend fun _example_texture_texture_write_region() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture(Size(width=64u, height=32u, depth=null), TextureFormat.RGBA, null, null)
        val bytes = ByteArray(64 * 32 * 4)

        // Simple sub-rectangle update.
        texture.writeRegion(bytes, TextureRegionMobile(0u, 0u, 0u, 64u, 32u, 0u, null, null))

        // Explicit data layout (advanced — when source rows are padded).
        val region = TextureRegionMobile(0u, 0u, 0u, 64u, 32u, 0u, 256u, 32u)
        texture.writeRegion(bytes, region)
    }

}
