package org.fragmentcolor

// AUTO-GENERATED by build.rs (scripts/website.rs). DO NOT EDIT.
//
// Compile-only aggregator for every transpiled Kotlin example under
// `platforms/kotlin/examples/`. Each function below embeds the body
// of one example so kotlinc type-checks it during
// `connectedAndroidTest`. Functions are never invoked at runtime —
// wiring up GPU-backed runtime execution is a follow-up task.
//
// A failure here means either:
//  (a) the source `docs/api/**.md` example uses a Rust API that
//      `scripts/convert.rs::to_kotlin` cannot map, or
//  (b) the example references an item that uniffi does not export
//      to Kotlin.
// Fix the source — this file is regenerated on every cargo build.

import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class GeneratedExamples {
    @Test
    fun compileGeneratedExamples() {
        // Empty body. The value of this test is that all wrappers
        // below are type-checked at compile time.
    }

    @Suppress("unused") private suspend fun _example_core_pass_Pass() {


        val renderer = Renderer()
        val canvas = document.createElement("canvas")
        val target = renderer.createTarget(canvas)
        val shader = Shader.default()

        val pass = Pass("First Pass")
        pass.addShader(shader)

        val pass2 = Pass("Second Pass")
        pass2.addShader(shader)

        // standalone
        renderer.render(pass, target)

        // vector of passes rendered in order (any iterable of Pass is renderable)
        renderer.render(arrayOf(pass, pass2), target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_add_depth_target() {

        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 64))

        // Create a depth texture usable as a per-pass attachment
        val depth = renderer.createDepthTexture(arrayOf(64, 64))

        val mesh = Mesh()
        mesh.addVertex(arrayOf(0.0, 0.0, 0.0))
        mesh.addVertex(arrayOf(1.0, 0.0, 0.0))
        mesh.addVertex(arrayOf(0.0, 1.0, 0.0))
        mesh.addVertex(arrayOf(1.0, 1.0, 0.0))
        val shader = Shader.fromMesh(mesh)
        val pass = Pass("scene"); pass.addShader(shader)

        // Attach depth texture to enable depth testing.
        // Pipeline will include a matching depth-stencil state
        pass.addDepthTarget(depth)

        // Render as usual
        renderer.render(pass, target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_add_mesh() {

        val mesh = Mesh()
        mesh.addVertex(arrayOf(0.0, 0.0))

        val shader = Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        val pass = Pass("pass"); pass.addShader(shader)

        pass.addMesh(mesh)
    }

    @Suppress("unused") private suspend fun _example_core_pass_add_mesh_to_shader() {

        val mesh = Mesh()
        mesh.addVertex(Vertex.new(arrayOf(0.0, 0.0)))
        val shader = Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        val pass = Pass("pass"); pass.addShader(shader)
        pass.addMeshToShader(mesh, shader)
    }

    @Suppress("unused") private suspend fun _example_core_pass_add_shader() {

        val shader = Shader.default()
        val pass = Pass("p")
        pass.addShader(shader)
    }

    @Suppress("unused") private suspend fun _example_core_pass_add_target() {

        val r = Renderer()
        val tex_target = r.createTextureTarget(arrayOf(512, 512))

        val p = Pass("shadow")
        p.addTarget(tex_target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_compute() {

        val cs = Shader("@compute @workgroup_size(8,8,1) fn cs_main() {}").unwrap()
        val pass = Pass("compute"); pass.addShader(cs)
    }

    @Suppress("unused") private suspend fun _example_core_pass_from_shader() {

        val shader = Shader.default()
        val pass = Pass("single"); pass.addShader(shader)
    }

    @Suppress("unused") private suspend fun _example_core_pass_get_input() {

        val pass = Pass("example")
        val input = pass.getInput()
    }

    @Suppress("unused") private suspend fun _example_core_pass_is_compute() {

        val shader = Shader("""
        @compute @workgroup_size(1)
        fn cs_main() { }

        """)
        val pass = Pass("p"); pass.addShader(shader)

        // Call the method
        val is_compute = pass.isCompute()
    }

    @Suppress("unused") private suspend fun _example_core_pass_load_previous() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 64))

        val shader = Shader.default()
        val pass = Pass("blend with previous")
        pass.addShader(shader)
        pass.loadPrevious()

        renderer.render(pass, target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_new() {

        val pass = Pass("first pass")
    }

    @Suppress("unused") private suspend fun _example_core_pass_require() {
        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(100,100))
        val color = Pass("color")
        val blurx = Pass("blur_x")
        blurx.require(color); // color before blur_x
        val blury = Pass("blur_y")
        blury.require(blurx); // blur_x before blur_y
        val compose = Pass("compose")
        compose.require(color)
        compose.require(blury); // fan-in; color and blur_y before compose
        renderer.render(compose, target); // compose renders last
    }

    @Suppress("unused") private suspend fun _example_core_pass_set_clear_color() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 64))

        val shader = Shader.default()
        val pass = Pass("solid background")
        pass.addShader(shader)

        pass.setClearColor(arrayOf(0.1, 0.2, 0.3, 1.0))

        renderer.render(pass, target)
    }

    @Suppress("unused") private suspend fun _example_core_pass_set_compute_dispatch() {
        val cs = Shader("@compute @workgroup_size(8,8,1) fn cs_main() {}").unwrap()
        val pass = Pass("compute"); pass.addShader(cs)
        pass.setComputeDispatch(64, 64, 1)
    }

    @Suppress("unused") private suspend fun _example_core_pass_set_viewport() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 64))

        val shader = Shader.default()
        val pass = Pass("clipped")
        pass.addShader(shader)

        pass.setViewport(arrayOf((0, 0), (32, 32)))

        renderer.render(pass, target)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_Renderer() {


        val renderer = Renderer()

        // Use your platform's windowing system to create a window
        val canvas = document.createElement("canvas")

        // Create a Target from it
        val target = renderer.createTarget(canvas)
        val texture_target = renderer.createTextureTarget(arrayOf(16, 16))

        // RENDERING
        renderer.render(Shader(""), texture_target)

        // That's it. Welcome to FragmentColor!
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_depth_texture() {
        val r = Renderer()
        val depth = r.createDepthTexture(arrayOf(800, 600))
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_storage_texture() {

        val r = Renderer()
        // Empty storage texture â same single create_storage_texture entry.
        val tex = r.createStorageTexture((arrayOf(64, 64), TextureFormat.Rgba))

        // Pre-seeded with bytes â same method, three-tuple form.
        val pixels = Array(64 * 64 * 4) { 0 }
        val tex2 = r.createStorageTexture((arrayOf(64, 64), TextureFormat.Rgba, pixels))
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_target() {


        val renderer = Renderer()

        // Use your platform's windowing system to create a window.
        val canvas = document.createElement("canvas")

        val target = renderer.createTarget(canvas)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_texture() {
        val renderer = Renderer()
        // Encoded image bytes (PNG / JPEG / etc.) â single tuple, no extra method.
        val image = "/healthcheck/public/favicon.png"
        val tex = renderer.createTexture(image[..])
    }

    @Suppress("unused") private suspend fun _example_core_renderer_create_texture_target() {

        val renderer = Renderer()

        // Create an offscreen texture target with a size of 64x64 pixels.
        val target = renderer.createTextureTarget(arrayOf(64, 64))

        renderer.render(Shader(""), target)

        // get the rendered image
        val image = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_core_renderer_new() {


        val renderer = Renderer()
        val texture_target = renderer.createTextureTarget(arrayOf(16, 16))
    }

    @Suppress("unused") private suspend fun _example_core_renderer_read_texture() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture((arrayOf(64, 64), TextureFormat.Rgba))
        texture.write(Array(64 * 64 * 4) { 0 })

        val bytes = renderer.readTexture(texture.id())
    }

    @Suppress("unused") private suspend fun _example_core_renderer_read_texture_async() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture((arrayOf(64, 64), TextureFormat.Rgba))
        texture.write(Array(64 * 64 * 4) { 0 })

        val bytes = renderer.readTextureAsync(texture.id())
    }

    @Suppress("unused") private suspend fun _example_core_renderer_render() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(10, 10))
        val shader = Shader.default()

        renderer.render(shader, target)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_unregister_texture() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture((arrayOf(16, 16), TextureFormat.Rgba))
        val id = texture.id()

        renderer.unregisterTexture(id)
    }

    @Suppress("unused") private suspend fun _example_core_renderer_wait_idle() {

        val r = Renderer()
        val target = r.createTextureTarget(arrayOf(8, 8))
        val shader = Shader.default()
        r.render(shader, target)
        r.waitIdle()
        val _bytes = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_core_shader_Shader() {


        val shader = Shader("""
            @vertex
            fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
                var pos = array<vec2<f32>, 3>(
                    vec2<f32>(-1.0, -1.0),
                    vec2<f32>( 3.0, -1.0),
                    vec2<f32>(-1.0,  3.0)
                )
                return vec4<f32>(pos[index], 0.0, 1.0)
            }

            @group(0) @binding(0)
            var<uniform> resolution: vec2<f32>

            @fragment
            fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
            }

        """)

        // Set the "resolution" uniform
        shader.set("resolution", arrayOf(800.0, 600.0))
        val res = shader.get("resolution")

        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(16, 16))
        renderer.render(shader, target)
    }

    @Suppress("unused") private suspend fun _example_core_shader_add_mesh() {

        val shader = Shader("""
          @vertex fn vs_main(@location(0) pos: vec3<f32>) -> @builtin(position) vec4<f32> {
            return vec4<f32>(pos, 1.0)
          }
          @fragment fn fs_main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        val mesh = Mesh()
        mesh.addVertex(arrayOf(0.0, 0.0, 0.0))

        // Attach mesh to this shader (errors if incompatible)
        shader.addMesh(mesh)

        // Renderer will draw the mesh when rendering this pass.
        // Each Shader represents a RenderPipeline or ComputePipeline
        // in the GPU. Adding multiple meshes to it will draw all meshes
        // and all its instances in the same Pipeline.
    }

    @Suppress("unused") private suspend fun _example_core_shader_clear_meshes() {

        val shader = Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        val mesh = Mesh()
        mesh.addVertex(arrayOf(0.0, 0.0))
        shader.addMesh(mesh)

        // Clear all
        shader.clearMeshes()
    }

    @Suppress("unused") private suspend fun _example_core_shader_from_mesh() {

        val mesh = Mesh()
        mesh.addVertex(arrayOf(0.0, 0.0, 0.0))
        val shader = Shader.fromMesh(mesh)
    }

    @Suppress("unused") private suspend fun _example_core_shader_from_vertex() {

        val vertex = Vertex(arrayOf(0.0, 0.0, 0.0))
        val shader = Shader.fromVertex(vertex)
    }

    @Suppress("unused") private suspend fun _example_core_shader_get() {

        val shader = Shader.default()
        shader.set("resolution", arrayOf(800.0, 600.0))
        val res = shader.get("resolution")
    }

    @Suppress("unused") private suspend fun _example_core_shader_is_compute() {

        val shader = Shader("""
        @compute @workgroup_size(1)
        fn cs_main() { }

        """)

        // Call the method
        val is_compute = shader.isCompute()
    }

    @Suppress("unused") private suspend fun _example_core_shader_list_keys() {


        val shader = Shader.default()
        val keys = shader.listKeys()
    }

    @Suppress("unused") private suspend fun _example_core_shader_list_uniforms() {

        val shader = Shader.default()
        val list = shader.listUniforms()
    }

    @Suppress("unused") private suspend fun _example_core_shader_new() {


        val shader = Shader("""
            @vertex
            fn vs_main(@builtin(vertex_index) index: u32) -> @builtin(position) vec4<f32> {
                var pos = array<vec2<f32>, 3>(
                    vec2<f32>(-1.0, -1.0),
                    vec2<f32>( 3.0, -1.0),
                    vec2<f32>(-1.0,  3.0)
                )
                return vec4<f32>(pos[index], 0.0, 1.0)
            }

            @group(0) @binding(0)
            var<uniform> resolution: vec2<f32>

            @fragment
            fn fs_main() -> @location(0) vec4<f32> {
                return vec4<f32>(1.0, 0.0, 0.0, 1.0); // Red
            }

        """)


        val main = """
            @vertex fn vs(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
                let p = array<vec2<f32>,3>(vec2f(-1.,-1.), vec2f(3.,-1.), vec2f(-1.,3.))
                return vec4<f32>(p[i], 0.0, 1.0)
            }

            @fragment fn fs(@builtin(position) pos: vec4<f32>) -> @location(0) vec4<f32> {
                let d = circle(pos.xy - vec2<f32>(400.0, 300.0), 100.0)
                let n = simplex2(pos.xy * 0.01)
                return vec4<f32>(vec3<f32>(step(0.0, d) + n * 0.1), 1.0)
            }

        """

        val shader = Shader.new([
            "sdf2d/circle",      // pure function: fn circle(p: vec2<f32>, r: f32) -> f32
            "noise/simplex2",    // pure function: fn simplex2(v: vec2<f32>) -> f32
            main,
        ])
    }

    @Suppress("unused") private suspend fun _example_core_shader_remove_mesh() {

        val shader = Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        val mesh = Mesh()
        mesh.addVertex(arrayOf(0.0, 0.0))
        shader.addMesh(mesh)

        // Detach the mesh
        shader.removeMesh(mesh)
    }

    @Suppress("unused") private suspend fun _example_core_shader_remove_meshes() {

        val shader = Shader("""
          struct VOut { @builtin(position) pos: vec4<f32> }
          @vertex
          fn vs_main(@location(0) pos: vec2<f32>) -> VOut {
            var out: VOut
            out.pos = vec4<f32>(pos, 0.0, 1.0)
            return out
          }
          @fragment
          fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.0,0.0,0.0,1.0); }

        """)

        val m1 = Mesh()
        m1.addVertex(arrayOf(0.0, 0.0))
        val m2 = Mesh()
        m2.addVertex(arrayOf(0.5, 0.0))

        shader.addMesh(m1)
        shader.addMesh(m2)

        shader.removeMeshes(arrayOf(m1, m2))
    }

    @Suppress("unused") private suspend fun _example_core_shader_set() {
        val r = Renderer()
        val shader = Shader("""
        @group(0) @binding(0) var<uniform> resolution: vec2<f32>

        struct VOut { @builtin(position) pos: vec4<f32> }
        @vertex fn vs_main(@builtin(vertex_index) i: u32) -> VOut {
          var p = array<vec2<f32>, 3>(vec2<f32>(-1.,-1.), vec2<f32>(3.,-1.), vec2<f32>(-1.,3.))
          var out: VOut
          out.pos = vec4<f32>(p[i], 0., 1.)
          return out
        }
        @fragment fn main() -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)

        // Set scalars/vectors on declared uniforms
        shader.set("resolution", arrayOf(800.0, 600.0))
    }

    @Suppress("unused") private suspend fun _example_core_shader_set_registry() {


        // Point at your own mirror of the registry
        Shader.setRegistry("https://cdn.example.com/shaders/")

        // Now the slug "sdf2d/circle" resolves to https://cdn.example.com/shaders/sdf2d/circle.wgsl
        // (Skipping the actual fetch in this doctest)
    }

    @Suppress("unused") private suspend fun _example_core_shader_validate_mesh() {

        val shader = Shader("""
        struct VOut { @builtin(position) pos: vec4<f32> }
        @vertex fn vs_main(@location(0) pos: vec3<f32>) -> VOut {
          var out: VOut
          out.pos = vec4<f32>(pos, 1.0)
          return out
        }
        @fragment fn fs_main(_v: VOut) -> @location(0) vec4<f32> { return vec4<f32>(1.,0.,0.,1.); }

        """)
        val pass = Pass("p"); pass.addShader(shader)

        val mesh = Mesh()
        mesh.addVertices([
          arrayOf(-0.5, -0.5, 0.0),
          arrayOf(0.5, -0.5, 0.0),
          arrayOf(0.0,  0.5, 0.0),
        ])

        shader.validateMesh(mesh); // Ok
        pass.addMesh(mesh)
    }

    @Suppress("unused") private suspend fun _example_core_texture_Texture() {

        val renderer = Renderer()
        val shader = Shader("""
        @group(0) @binding(0) var my_texture: texture_2d<f32>
        @group(0) @binding(1) var my_sampler: sampler
        @vertex fn vs_main(@builtin(vertex_index) i: u32) -> @builtin(position) vec4<f32> {
          let p = array<vec2<f32>,3>(vec2f(-1.,-1.), vec2f(3.,-1.), vec2f(-1.,3.))
          return vec4f(p[i], 0., 1.)
        }
        @fragment fn main() -> @location(0) vec4<f32> { return vec4f(1.,1.,1.,1.); }

        """)

        // 1x1 RGBA (white) raw pixel bytes - single create_texture entry, tuple
        // form (bytes, format, size) selects the raw-pixel path. Format is
        // the placeholder Rgba (sRGB-aware) by default.
        val pixels = arrayOf(255,255,255,255)
        val texture = renderer.createTexture((pixels, arrayOf(1, 1)))

        // insert  the texture in the shader matching the name in the shader
        shader.set("my_texture", texture)
    }

    @Suppress("unused") private suspend fun _example_core_texture_aspect() {


        val renderer = Renderer()
        // 1x1 RGBA (white) raw pixel bytes
        val pixels = arrayOf(255,255,255,255)
        val tex = renderer.createTexture((pixels, arrayOf(1, 1)))
        val a = tex.aspect()
    }

    @Suppress("unused") private suspend fun _example_core_texture_get_image() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture((arrayOf(64, 64), TextureFormat.Rgba))
        texture.write(Array(64 * 64 * 4) { 0 })

        val bytes = texture.getImage()
    }

    @Suppress("unused") private suspend fun _example_core_texture_id() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture((arrayOf(64, 64), TextureFormat.Rgba))
        val id = texture.id()
    }

    @Suppress("unused") private suspend fun _example_core_texture_set_sampler_options() {

        val renderer = Renderer()
        val pixels: ByteArray = byteArrayOf(255.toByte(), 255.toByte(), 255.toByte(), 255.toByte())
        val options = TextureOptions(
            size = Size(width = 1u, height = 1u, depth = null),
            format = TextureFormat.RGBA8_UNORM_SRGB,
            sampler = SamplerOptions(repeatX = false, repeatY = false, smooth = true, compare = null),
            mipmaps = false,
            usage = null,
        )
        val texture = renderer.createTexture(TextureInputMobile.Bytes(pixels), options)

        val opts = SamplerOptions(repeatX = true, repeatY = true, smooth = true, compare = null)
        texture.setSamplerOptions(opts)
    }

    @Suppress("unused") private suspend fun _example_core_texture_size() {
        val renderer = Renderer()
        val pixels = arrayOf(255,255,255,255)
        val tex = renderer.createTexture((pixels, arrayOf(1, 1)))
        val sz = tex.size()
    }

    @Suppress("unused") private suspend fun _example_core_texture_write() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture((arrayOf(64, 64), TextureFormat.Rgba))
        val frame_bytes = Array(64 * 64 * 4) { 0 }

        texture.write(frame_bytes)
    }

    @Suppress("unused") private suspend fun _example_core_texture_write_region() {
        val renderer = Renderer()
        val texture = renderer.createStorageTexture((arrayOf(64, 32), TextureFormat.Rgba))
        val bytes = Array(64 * 32 * 4) { 0 }

        // Simple sub-rectangle update.
        texture.writeRegion(bytes, arrayOf(0, 0, 64, 32))

        // Explicit data layout (advanced â when source rows are padded).
        val region = TextureRegion.from(arrayOf(0, 0, 64, 32)).withStride(256).withRows(32)
        texture.writeRegion(bytes, region)
    }

    @Suppress("unused") private suspend fun _example_core_texture_mip_chain_TextureMipChain() {

        val renderer = Renderer()
        // Encoded image bytes the caller has on hand (could come off a worker).
        val png = [
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A,
            // ... full PNG body ...
        ]
        val chain = TextureMipChain.prepare((png, TextureFormat.Rgba8UnormSrgb))

        // Hand the chain to the unified create_texture entry - same vocabulary as
        // every other texture path; From<TextureMipChain> selects the GPU-only
        // upload internally.
        val texture = renderer.createTexture(chain)
    }

    @Suppress("unused") private suspend fun _example_core_texture_mip_chain_base_size() {

        val pixels = Array(16 * 16 * 4) { 0 }
        val chain = TextureMipChain.prepare((
            pixels.asSlice(),
            TextureFormat.Rgba8UnormSrgb,
            arrayOf(16, 16),
        ))
        val (width, height) = chain.baseSize()
        val _ = (width, height)
    }

    @Suppress("unused") private suspend fun _example_core_texture_mip_chain_format() {

        val pixels = Array(4 * 4 * 4) { 200 }
        val chain = TextureMipChain.prepare((
            pixels.asSlice(),
            TextureFormat.Rgba8UnormSrgb,
            arrayOf(4, 4),
        ))
        val _ = chain.format()
    }

    @Suppress("unused") private suspend fun _example_core_texture_mip_chain_level_count() {

        val pixels = Array(8 * 8 * 4) { 0 }
        val chain = TextureMipChain.prepare((
            pixels.asSlice(),
            TextureFormat.Rgba8UnormSrgb,
            arrayOf(8, 8),
        ))
        val count = chain.levelCount()
        val _ = count
    }

    @Suppress("unused") private suspend fun _example_core_texture_mip_chain_levels() {

        val pixels = Array(8 * 8 * 4) { 0 }
        val chain = TextureMipChain.prepare((
            pixels.asSlice(),
            TextureFormat.Rgba8UnormSrgb,
            arrayOf(8, 8),
        ))
        val level_zero_bytes = chain.levels()[0]
        val _ = level_zero_bytes
    }

    @Suppress("unused") private suspend fun _example_core_texture_mip_chain_prepare() {

        // Encoded path â single tuple, no extra method.
        val chain = TextureMipChain.prepare((encoded_png_bytes, TextureFormat.Rgba8UnormSrgb))

        // Raw pixel path â same method, just include the size in the tuple.
        val chain_raw = TextureMipChain.prepare((
            raw_rgba.asSlice(),
            TextureFormat.Rgba8UnormSrgb,
            arrayOf(8, 8),
        ))

        // Hand the chain to the unified create_texture entry â same vocabulary.
        val renderer = Renderer()
        val texture = renderer.createTexture(chain)
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_Mesh() {

        val mesh = Mesh()
        mesh.addVertex(arrayOf(0.0, 0.5, 0.0))
        mesh.addVertex(arrayOf(-0.5, -0.5, 0.0))
        mesh.addVertex(arrayOf(0.5, -0.5, 0.0))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_add_instance() {

        val m = Mesh()
        val offset = arrayOf(0.25, 0.10)
        val tint = arrayOf(1.0, 0.0, 0.0, 1.0)
        m.addInstance(Instance.new().set("offset", offset).set("tint", tint))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_add_instances() {

        val m = Mesh()
        val red = arrayOf(1.0, 0.0, 0.0, 1.0)
        val green = arrayOf(0.0, 1.0, 0.0, 1.0)
        val blue = arrayOf(0.0, 0.0, 1.0, 1.0)
        m.addInstances([
            Instance.new().set("tint", red),
            Instance.new().set("tint", green),
            Instance.new().set("tint", blue),
        ])
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_add_vertex() {
        val m = Mesh()
        m.addVertex(arrayOf(0.0, 0.0))
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_add_vertices() {
        val m = Mesh()
        m.addVertices([
          arrayOf(0.0, 0.0),
          arrayOf(1.0, 0.0),
        ])
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_clear_instances() {

        val m = Mesh()
        val red = arrayOf(1.0, 0.0, 0.0, 1.0)
        m.addInstance(Instance.new().set("tint", red))
        m.clearInstances(); // back to a single uninstanced draw
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_from_vertices() {

        val mesh = Mesh.fromVertices([
            arrayOf(0.0, 0.0),
            arrayOf(1.0, 0.0),
            arrayOf(0.0, 1.0),
        ])
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_new() {
        val m = Mesh()
    }

    @Suppress("unused") private suspend fun _example_geometry_mesh_set_instance_count() {
        val m = Mesh()
        m.addVertices([
            arrayOf(-0.01, -0.01),
            arrayOf(0.01, -0.01),
            arrayOf(0.00,  0.01),
        ])
        // Draw one million instances, fetching per-particle data from a storage buffer.
        m.setInstanceCount(1_000_000)
    }

    @Suppress("unused") private suspend fun _example_geometry_quad_Quad() {

        val quad = Quad(arrayOf(-0.5, -0.5), arrayOf(0.5, 0.5))
    }

    @Suppress("unused") private suspend fun _example_geometry_quad_get_mesh() {

        val quad = Quad(arrayOf(-0.5, -0.5), arrayOf(0.5, 0.5))
        val mesh = quad.getMesh()
    }

    @Suppress("unused") private suspend fun _example_geometry_quad_new() {

        val quad = Quad(arrayOf(-0.5, -0.5), arrayOf(0.5, 0.5))
    }

    @Suppress("unused") private suspend fun _example_geometry_vertex_Vertex() {
        val v = Vertex(arrayOf(0.0, 0.0, 0.0)).set("uv", arrayOf(0.5, 0.5))
    }

    @Suppress("unused") private suspend fun _example_geometry_vertex_create_instance() {
        val v = Vertex(arrayOf(0.0, 0.0))
        val inst = v.createInstance()
    }

    @Suppress("unused") private suspend fun _example_geometry_vertex_new() {
        val v = Vertex(arrayOf(0.0, 0.0))
    }

    @Suppress("unused") private suspend fun _example_geometry_vertex_set() {
        val v = Vertex(arrayOf(0.0, 0.0, 0.0)).set("weight", 1.0).set("color",arrayOf(1.0, 0.0, 0.0))
    }

    @Suppress("unused") private suspend fun _example_targets_target_Target() {


        val renderer = Renderer()

        // Use your platform's windowing system to create a window.
        val canvas = document.createElement("canvas")

        val target = renderer.createTarget(canvas)

        // To animate, render again in your event loop...
        renderer.render(Shader(""), target)
        renderer.render(Shader(""), target)
    }

    @Suppress("unused") private suspend fun _example_targets_target_get_image() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(16, 16))
        renderer.render(Shader(""), target)

        val image = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_targets_target_resize() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 32))

        target.resize(arrayOf(128, 64))
    }

    @Suppress("unused") private suspend fun _example_targets_target_size() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 32))
        val size = target.size()
        val width = size.width
        val height = size.height
        val depth = size.depth
    }

    @Suppress("unused") private suspend fun _example_targets_texture_target_TextureTarget() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 64))

        val shader = Shader.default()
        renderer.render(shader, target)

        val image = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_targets_texture_target_get_image() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(16, 16))
        renderer.render(Shader(""), target)

        val image = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_targets_texture_target_resize() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 64))

        target.resize(arrayOf(128, 32))
    }

    @Suppress("unused") private suspend fun _example_targets_texture_target_size() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 64))
        val size = target.size()
        val width = size.width
        val height = size.height
        val depth = size.depth
    }

    @Suppress("unused") private suspend fun _example_targets_window_target_WindowTarget() {


        // Use your platform's windowing system to create a window.
        val canvas = document.createElement("canvas")

        val renderer = Renderer()
        val target = renderer.createTarget(canvas)

        renderer.render(Shader(""), target)
    }

    @Suppress("unused") private suspend fun _example_targets_window_target_get_image() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(16, 16))
        renderer.render(Shader(""), target)

        val image = target.getImage()
    }

    @Suppress("unused") private suspend fun _example_targets_window_target_resize() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 32))

        target.resize(arrayOf(128, 64))
    }

    @Suppress("unused") private suspend fun _example_targets_window_target_size() {


        val renderer = Renderer()
        val target = renderer.createTextureTarget(arrayOf(64, 32))
    }

}
