// Auto-generated: runs all JS examples with cargo-like output.
const GREEN='\u001b[1;32m'; const RED='\u001b[1;31m'; const RESET='\u001b[0m';
const EXAMPLES = [
  '../examples/core/pass/Pass.js',
  '../examples/core/pass/add.js',
  '../examples/core/pass/add_mesh.js',
  '../examples/core/pass/add_shader.js',
  '../examples/core/pass/compute.js',
  '../examples/core/pass/from_shader.js',
  '../examples/core/pass/get_input.js',
  '../examples/core/pass/is_compute.js',
  '../examples/core/pass/load_previous.js',
  '../examples/core/pass/new.js',
  '../examples/core/pass/require.js',
  '../examples/core/pass/set_clear_color.js',
  '../examples/core/pass/set_compute_dispatch.js',
  '../examples/core/pass/set_depth_target.js',
  '../examples/core/pass/set_target.js',
  '../examples/core/pass/set_viewport.js',
  '../examples/core/renderer/Renderer.js',
  '../examples/core/renderer/create_depth_texture.js',
  '../examples/core/renderer/create_external_texture.js',
  '../examples/core/renderer/create_storage_texture.js',
  '../examples/core/renderer/create_target.js',
  '../examples/core/renderer/create_texture.js',
  '../examples/core/renderer/create_texture_target.js',
  '../examples/core/renderer/load.js',
  '../examples/core/renderer/new.js',
  '../examples/core/renderer/read_storage.js',
  '../examples/core/renderer/read_texture.js',
  '../examples/core/renderer/render.js',
  '../examples/core/renderer/unregister_texture.js',
  '../examples/core/shader/Shader.js',
  '../examples/core/shader/add_mesh.js',
  '../examples/core/shader/clear_meshes.js',
  '../examples/core/shader/fetch.js',
  '../examples/core/shader/from_mesh.js',
  '../examples/core/shader/from_vertex.js',
  '../examples/core/shader/get.js',
  '../examples/core/shader/is_compute.js',
  '../examples/core/shader/list_keys.js',
  '../examples/core/shader/list_uniforms.js',
  '../examples/core/shader/new.js',
  '../examples/core/shader/remove_mesh.js',
  '../examples/core/shader/remove_meshes.js',
  '../examples/core/shader/set.js',
  '../examples/core/shader/set_registry.js',
  '../examples/core/shader/validate_mesh.js',
  '../examples/geometry/mesh/Mesh.js',
  '../examples/geometry/mesh/add_instance.js',
  '../examples/geometry/mesh/add_instances.js',
  '../examples/geometry/mesh/add_vertex.js',
  '../examples/geometry/mesh/add_vertices.js',
  '../examples/geometry/mesh/clear_indices.js',
  '../examples/geometry/mesh/clear_instances.js',
  '../examples/geometry/mesh/from_vertices.js',
  '../examples/geometry/mesh/new.js',
  '../examples/geometry/mesh/set_indices.js',
  '../examples/geometry/mesh/set_instance_count.js',
  '../examples/geometry/quad/Quad.js',
  '../examples/geometry/quad/get_mesh.js',
  '../examples/geometry/quad/new.js',
  '../examples/geometry/vertex/Vertex.js',
  '../examples/geometry/vertex/create_instance.js',
  '../examples/geometry/vertex/new.js',
  '../examples/geometry/vertex/pbr.js',
  '../examples/geometry/vertex/set.js',
  '../examples/scene/camera/look_at.js',
  '../examples/scene/camera/orthographic.js',
  '../examples/scene/camera/perspective.js',
  '../examples/scene/camera/position.js',
  '../examples/scene/camera/set_aspect.js',
  '../examples/scene/camera/view_proj.js',
  '../examples/scene/light/color.js',
  '../examples/scene/light/direction.js',
  '../examples/scene/light/directional.js',
  '../examples/scene/light/inner_cone_angle.js',
  '../examples/scene/light/intensity.js',
  '../examples/scene/light/kind.js',
  '../examples/scene/light/outer_cone_angle.js',
  '../examples/scene/light/point.js',
  '../examples/scene/light/position.js',
  '../examples/scene/light/range.js',
  '../examples/scene/light/set_color.js',
  '../examples/scene/light/set_cone_angles.js',
  '../examples/scene/light/set_direction.js',
  '../examples/scene/light/set_intensity.js',
  '../examples/scene/light/set_position.js',
  '../examples/scene/light/set_range.js',
  '../examples/scene/light/spot.js',
  '../examples/scene/material/Material.js',
  '../examples/scene/material/alpha_cutoff.js',
  '../examples/scene/material/alpha_mode.js',
  '../examples/scene/material/base_color.js',
  '../examples/scene/material/base_color_texture.js',
  '../examples/scene/material/custom.js',
  '../examples/scene/material/double_sided.js',
  '../examples/scene/material/emissive.js',
  '../examples/scene/material/emissive_texture.js',
  '../examples/scene/material/metallic.js',
  '../examples/scene/material/metallic_roughness_texture.js',
  '../examples/scene/material/normal_scale.js',
  '../examples/scene/material/normal_texture.js',
  '../examples/scene/material/occlusion_strength.js',
  '../examples/scene/material/occlusion_texture.js',
  '../examples/scene/material/pbr.js',
  '../examples/scene/material/roughness.js',
  '../examples/scene/material/shader.js',
  '../examples/scene/material/uv_transform.js',
  '../examples/scene/model/material.js',
  '../examples/scene/model/mesh.js',
  '../examples/scene/model/new.js',
  '../examples/scene/model/rotate.js',
  '../examples/scene/model/scale.js',
  '../examples/scene/model/set_transform.js',
  '../examples/scene/model/set_visible.js',
  '../examples/scene/model/transform.js',
  '../examples/scene/model/translate.js',
  '../examples/scene/model/visible.js',
  '../examples/scene/scene/add.js',
  '../examples/scene/scene/add_pass.js',
  '../examples/scene/scene/ambient.js',
  '../examples/scene/scene/cameras.js',
  '../examples/scene/scene/get_pass.js',
  '../examples/scene/scene/lights.js',
  '../examples/scene/scene/list_passes.js',
  '../examples/scene/scene/load.js',
  '../examples/scene/scene/models.js',
  '../examples/scene/scene/new.js',
  '../examples/scene/scene/no_default_camera.js',
  '../examples/scene/scene/no_default_light.js',
  '../examples/scene/scene/no_defaults.js',
  '../examples/scene/scene/remove_pass.js',
  '../examples/scene/scene/set_default_camera.js',
  '../examples/scene/scene/set_default_light.js',
  '../examples/scene/scene/set_passes.js',
  '../examples/targets/target/Target.js',
  '../examples/targets/target/get_image.js',
  '../examples/targets/target/resize.js',
  '../examples/targets/target/size.js',
  '../examples/targets/texture_target/TextureTarget.js',
  '../examples/targets/texture_target/texture.js',
  '../examples/targets/window_target/WindowTarget.js',
  '../examples/targets/window_target/get_image.js',
  '../examples/targets/window_target/resize.js',
  '../examples/targets/window_target/size.js',
  '../examples/texture/mipmap/Mipmap.js',
  '../examples/texture/mipmap/build.js',
  '../examples/texture/mipmap/count.js',
  '../examples/texture/mipmap/format.js',
  '../examples/texture/mipmap/levels.js',
  '../examples/texture/mipmap/size.js',
  '../examples/texture/texture/Texture.js',
  '../examples/texture/texture/aspect.js',
  '../examples/texture/texture/get_image.js',
  '../examples/texture/texture/id.js',
  '../examples/texture/texture/set_sampler_options.js',
  '../examples/texture/texture/size.js',
  '../examples/texture/texture/write.js',
  '../examples/texture/texture/write_region.js',
]

function fq(rel){ return 'platforms.web.examples.' + rel.replace('../examples/','').replace(/\\.js$/, '').replaceAll('/', '.'); }
export async function runExamples() {
  const total = EXAMPLES.length;
  let passed = 0;
  let failed = 0;
  console.log(`running ${total} tests`);
  globalThis.__HC = globalThis.__HC || { currentModule: null };
  for (const rel of EXAMPLES) {
    const name = fq(rel);
    const head = `test ${name} ... `;
    try {
      globalThis.__HC.currentModule = name;
      await import(rel);
      passed++;
      console.log(head + GREEN + 'OK' + RESET);
    } catch (e) {
      failed++;
      console.log(head + RED + 'FAILED' + RESET);
      console.error(e);
    } finally {
      globalThis.__HC.currentModule = null;
    }
  }
  return { passed, failed };
}
