mod embedded_shaders {
    use super::meta;
    use std::fs;
    use std::path::PathBuf;

    const REGISTRY_REL: &str = "docs/website/public/shaders";
    const OUTPUT_REL: &str = "generated/embedded_shaders.rs";

    /// Walk the shader registry and emit `generated/embedded_shaders.rs` —
    /// a feature-gated `match` from slugs to `include_str!` of the source.
    /// Each slug's match arm is gated on `shaders-<category>`, so enabling a
    /// category compiles its shaders into the binary; everything else stays
    /// URL-only at runtime.
    pub fn generate() {
        let root = meta::workspace_root();
        let registry = root.join(REGISTRY_REL);

        // Re-run when the registry contents change (additions, removals, edits).
        println!("cargo::rerun-if-changed={}", REGISTRY_REL);

        let entries = collect_entries(&registry);
        let source = render(&entries);

        let dest = root.join(OUTPUT_REL);
        if let Err(e) = meta::write_if_changed(&dest, &source) {
            panic!("failed to write {}: {}", dest.display(), e);
        }
    }

    /// (slug, relative_path) sorted by slug, derived from the on-disk layout.
    fn collect_entries(registry: &std::path::Path) -> Vec<(String, String)> {
        let mut entries: Vec<(String, String)> = Vec::new();

        let mut categories: Vec<PathBuf> = match fs::read_dir(registry) {
            Ok(rd) => rd
                .filter_map(|e| e.ok().map(|e| e.path()))
                .filter(|p| p.is_dir())
                .collect(),
            Err(_) => return entries,
        };
        categories.sort();

        for cat_dir in categories {
            let cat = match cat_dir.file_name().and_then(|n| n.to_str()) {
                Some(n) => n.to_string(),
                None => continue,
            };

            let mut files: Vec<PathBuf> = match fs::read_dir(&cat_dir) {
                Ok(rd) => rd
                    .filter_map(|e| e.ok().map(|e| e.path()))
                    .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("wgsl"))
                    .collect(),
                Err(_) => continue,
            };
            files.sort();

            for file in files {
                let stem = match file.file_stem().and_then(|n| n.to_str()) {
                    Some(s) => s.to_string(),
                    None => continue,
                };
                let slug = format!("{}/{}", cat, stem);
                let rel = format!("{}/{}/{}.wgsl", REGISTRY_REL, cat, stem);
                entries.push((slug, rel));
            }
        }

        entries
    }

    fn render(entries: &[(String, String)]) -> String {
        let mut s = String::new();
        s.push_str("// AUTOGENERATED — do not edit by hand.\n");
        s.push_str("// Generated by scripts/embedded_shaders.rs from the registry under\n");
        s.push_str(&format!("// `{}`. Each match arm is gated on its category feature\n", REGISTRY_REL));
        s.push_str("// (`shaders-<category>`), so only the categories you opt in to are\n");
        s.push_str("// embedded into the binary.\n\n");

        s.push_str("/// Look up a registry slug (e.g. `\"postfx/vignette\"`) in the embedded\n");
        s.push_str("/// shader map. Returns `Some(source)` only when the matching\n");
        s.push_str("/// `shaders-<category>` feature is enabled at compile time, otherwise\n");
        s.push_str("/// `None` so the resolver falls back to fetching the URL form.\n");
        s.push_str("pub(crate) fn lookup(slug: &str) -> Option<&'static str> {\n");
        s.push_str("    match slug {\n");

        let mut current_cat: Option<String> = None;
        for (slug, rel_path) in entries {
            let cat = slug.split('/').next().unwrap_or("").to_string();
            if Some(&cat) != current_cat.as_ref() {
                if current_cat.is_some() {
                    s.push('\n');
                }
                current_cat = Some(cat.clone());
                s.push_str(&format!("        // -- {} --\n", cat));
            }
            s.push_str(&format!(
                "        #[cfg(feature = \"shaders-{cat}\")]\n        {slug:?} => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel_path}\"))),\n",
                cat = cat,
                slug = slug,
                rel_path = rel_path,
            ));
        }

        if !entries.is_empty() {
            s.push('\n');
        }
        s.push_str("        _ => None,\n");
        s.push_str("    }\n");
        s.push_str("}\n");

        s
    }
}
