mod python_stubs {
    use std::{
        fs,
        io::Write,
        path::{Path, PathBuf},
    };

    fn find_object_dir(docs_root: &Path, dir_slug: &str) -> Option<PathBuf> {
        fn walk(dir: &Path, root: &Path, target: &str) -> Option<PathBuf> {
            if !dir.is_dir() {
                return None;
            }
            for entry in std::fs::read_dir(dir).ok()?.flatten() {
                let p = entry.path();
                if p.is_dir() {
                    if p.file_name().and_then(|s| s.to_str()) == Some(target) {
                        let md = p.join(format!("{}.md", target));
                        if md.exists() {
                            return Some(p);
                        }
                    }
                    if let Some(found) = walk(&p, root, target) {
                        return Some(found);
                    }
                }
            }
            None
        }
        walk(docs_root, docs_root, dir_slug)
    }

    fn doc_method_with_python(
        category_rel: &str,
        object_slug: &str,
        method_stem: &str,
    ) -> Option<String> {
        let root = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into());
        let docs_root = PathBuf::from(root).join("docs/api");
        let obj_dir = {
            let dir_slug = object_slug;
            // object dir is nested under category_rel
            // build path docs/api/<category_rel>/<dir_slug>
            let p = docs_root.join(category_rel).join(dir_slug);
            if p.join(format!("{}.md", dir_slug)).exists() {
                Some(p)
            } else {
                // fallback to recursive search
                find_object_dir(&docs_root, dir_slug)
            }
        }?;
        // Prefer Python-specific hidden docs when present
        let hidden_py = obj_dir
            .join("hidden")
            .join(format!("{}_py.md", method_stem));
        let normal = obj_dir.join(format!("{}.md", method_stem));
        if hidden_py.exists() {
            let md = fs::read_to_string(&hidden_py).ok()?;
            return Some(render_doc_with_python(&md, &hidden_py.to_string_lossy()));
        }
        if normal.exists() {
            let md = fs::read_to_string(&normal).ok()?;
            return Some(render_doc_with_python(&md, &normal.to_string_lossy()));
        }
        None
    }

    fn add_method_doc(buf: &mut String, category_rel: &str, object_slug: &str, method_stem: &str) {
        if let Some(doc) = doc_method_with_python(category_rel, object_slug, method_stem) {
            let d = sanitize_doc(&doc);
            buf.push_str("    \"\"\"\n");
            for line in d.lines() {
                buf.push_str("    ");
                buf.push_str(line);
                buf.push('\n');
            }
            buf.push_str("    \"\"\"\n");
        }
    }

    pub fn generate_pyi(out_dir: &Path) -> std::io::Result<()> {
        // Ensure we rerun if relevant inputs change
        println!("cargo::rerun-if-changed=src/renderer/platform/python/mod.rs");
        println!("cargo::rerun-if-changed=src/pass/platform/python.rs");
        println!("cargo::rerun-if-changed=src/frame/features/python.rs");
        println!("cargo::rerun-if-changed=src/shader/platform/python.rs");
        println!("cargo::rerun-if-changed=src/texture/platform/python.rs");
        println!("cargo::rerun-if-changed=src/target/platform/python.rs");
        println!("cargo::rerun-if-changed=src/mesh/platform/python.rs");
        println!("cargo::rerun-if-changed=src/region.rs");
        println!("cargo::rerun-if-changed=src/size.rs");
        println!("cargo::rerun-if-changed=docs/api");

        fs::create_dir_all(out_dir)?;

        // Compose stub content
        let mut buf = String::new();
        buf.push_str("# Autogenerated by build.rs — do not edit manually.\n");
        buf.push_str("from __future__ import annotations\n\n");
        buf.push_str("from typing import Any, Mapping, Sequence, overload\n");
        buf.push_str("import numpy\n");
        buf.push_str("import numpy.typing as npt\n\n");

        // Aliases
        buf.push_str(
            "PySize = tuple[int, int] | tuple[int, int, int] | Sequence[int] | Mapping[str, int]\n",
        );
        buf.push_str("NDArrayU8 = npt.NDArray[numpy.uint8]\n");
        buf.push_str("Renderable = 'Shader' | 'Pass' | 'Frame' | Sequence['Shader' | 'Pass']\n\n");

        // Exceptions
        buf.push_str("class FragmentColorError(Exception): ...\n\n");

        // Size (no dedicated doc; use None)
        add_class(&mut buf, "Size", None);
        buf.push_str("    width: int\n    height: int\n    depth: int | None\n\n");
        buf.push_str("    def __init__(self, width: int, height: int, depth: int | None = None) -> None: ...\n\n");

        // Region (doc may be absent; best-effort)
        add_class(&mut buf, "Region", None);
        buf.push_str(
            "    def __init__(self, origin: tuple[int, int], size: tuple[int, int]) -> None: ...\n",
        );
        buf.push_str("    @classmethod\n    def from_region(cls, x: int, y: int, width: int, height: int) -> 'Region': ...\n");
        buf.push_str(
            "    @classmethod\n    def from_tuple(cls, size: tuple[int, int]) -> 'Region': ...\n\n",
        );

        // TextureFormat placeholder
        add_class(&mut buf, "TextureFormat", None);
        buf.push_str("    ...\n\n");

        // Texture
        add_class(
            &mut buf,
            "Texture",
            doc_with_python_examples("docs/api/core/texture/texture.md"),
        );
        buf.push_str("    @property\n    def size(self) -> Size: ...\n");
        add_method_doc(&mut buf, "core/texture", "texture", "size");
        buf.push_str("    def aspect(self) -> float: ...\n");
        add_method_doc(&mut buf, "core/texture", "texture", "aspect");
        buf.push_str(
            "    def set_sampler_options(self, options: Mapping[str, Any]) -> None: ...\n",
        );
        add_method_doc(&mut buf, "core/texture", "texture", "set_sampler_options");
        buf.push_str("\n");

        // Mesh / Vertex / Instance / VertexValue factory
        add_class(
            &mut buf,
            "Vertex",
            doc_with_python_examples("docs/api/geometry/vertex/vertex.md"),
        );
        buf.push_str("    def __init__(self, position: Any) -> None: ...\n");
        buf.push_str("    def set(self, key: str, value: Any) -> 'Vertex': ...\n");
        buf.push_str("    def create_instance(self) -> 'Instance': ...\n\n");

        add_class(&mut buf, "Instance", None);
        buf.push_str("    def __init__(self) -> None: ...\n\n");

        add_class(&mut buf, "VertexValue", None);
        buf.push_str("    @staticmethod\n    def f32(x: float) -> Any: ...\n");
        buf.push_str("    @staticmethod\n    def f32x2(x: tuple[float, float] | Sequence[float]) -> Any: ...\n");
        buf.push_str("    @staticmethod\n    def f32x3(x: Sequence[float]) -> Any: ...\n");
        buf.push_str("    @staticmethod\n    def f32x4(x: Sequence[float]) -> Any: ...\n");
        buf.push_str("    @staticmethod\n    def u32(x: int) -> Any: ...\n\n");

        add_class(
            &mut buf,
            "Mesh",
            doc_with_python_examples("docs/api/geometry/mesh/mesh.md"),
        );
        buf.push_str("    def __init__(self) -> None: ...\n");
        add_method_doc(&mut buf, "geometry/mesh", "mesh", "new");
        buf.push_str(
            "    @staticmethod\n    def from_vertices(vertices: Sequence[Any]) -> 'Mesh': ...\n",
        );
        add_method_doc(&mut buf, "geometry/mesh", "mesh", "from_vertices");
        buf.push_str("    def add_vertex(self, vertex: Any) -> None: ...\n");
        add_method_doc(&mut buf, "geometry/mesh", "mesh", "add_vertex");
        buf.push_str("    def add_vertices(self, vertices: Sequence[Any]) -> None: ...\n");
        add_method_doc(&mut buf, "geometry/mesh", "mesh", "add_vertices");
        buf.push_str("    def add_instance(self, item: Any) -> None: ...\n");
        add_method_doc(&mut buf, "geometry/mesh", "mesh", "add_instance");
        buf.push_str("    def add_instances(self, items: Sequence[Any]) -> None: ...\n");
        add_method_doc(&mut buf, "geometry/mesh", "mesh", "add_instances");
        buf.push_str("    def clear_instances(self) -> None: ...\n");
        add_method_doc(&mut buf, "geometry/mesh", "mesh", "clear_instances");
        buf.push_str("    def set_instance_count(self, n: int) -> None: ...\n");
        add_method_doc(&mut buf, "geometry/mesh", "mesh", "set_instance_count");
        buf.push_str("    def clear_instance_count(self) -> None: ...\n");
        add_method_doc(&mut buf, "geometry/mesh", "mesh", "clear_instance_count");
        buf.push_str("\n");

        // Quad
        add_class(
            &mut buf,
            "Quad",
            doc_with_python_examples("docs/api/geometry/quad/quad.md"),
        );
        buf.push_str("    def __init__(self, min: tuple[float, float], max: tuple[float, float]) -> None: ...\n");
        buf.push_str("    def get_mesh(self) -> Mesh: ...\n\n");

        // Pass
        add_class(
            &mut buf,
            "Pass",
            doc_with_python_examples("docs/api/core/pass/pass.md"),
        );
        buf.push_str("    def __init__(self, name: str) -> None: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "new");
        buf.push_str("    @staticmethod\n    def compute(name: str) -> 'Pass': ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "compute");
        buf.push_str(
            "    @staticmethod\n    def from_shader(name: str, shader: 'Shader') -> 'Pass': ...\n",
        );
        add_method_doc(&mut buf, "core/pass", "pass", "from_shader");
        buf.push_str("    def passes(self) -> Sequence['Pass']: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "passes");
        buf.push_str("    def load_previous(self) -> None: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "load_previous");
        buf.push_str("    def get_input(self) -> Any: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "get_input");
        buf.push_str("    def add_shader(self, shader: 'Shader') -> None: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "add_shader");
        buf.push_str("    def add_mesh(self, mesh: 'Mesh') -> None: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "add_mesh");
        buf.push_str(
            "    def add_mesh_to_shader(self, mesh: 'Mesh', shader: 'Shader') -> None: ...\n",
        );
        add_method_doc(&mut buf, "core/pass", "pass", "add_mesh_to_shader");
        buf.push_str("    def set_clear_color(self, color: Sequence[float]) -> None: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "set_clear_color");
        buf.push_str("    def set_viewport(self, viewport: 'Region') -> None: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "set_viewport");
        buf.push_str("    def set_compute_dispatch(self, x: int, y: int, z: int) -> None: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "set_compute_dispatch");
        buf.push_str(
            "    def add_target(self, target: 'TextureTarget' | 'Texture') -> None: ...\n",
        );
        add_method_doc(&mut buf, "core/pass", "pass", "add_target");
        buf.push_str(
            "    def add_depth_target(self, target: 'TextureTarget' | 'Texture') -> None: ...\n",
        );
        add_method_doc(&mut buf, "core/pass", "pass", "add_depth_target");
        buf.push_str("    def is_compute(self) -> bool: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "is_compute");
        buf.push_str("    def require(self, deps: Renderable) -> None: ...\n");
        add_method_doc(&mut buf, "core/pass", "pass", "require");
        buf.push_str("\n");

        // Frame
        add_class(
            &mut buf,
            "Frame",
            doc_with_python_examples("docs/api/core/frame/frame.md"),
        );
        buf.push_str("    def __init__(self) -> None: ...\n");
        add_method_doc(&mut buf, "core/frame", "frame", "new");
        buf.push_str("    def passes(self) -> Sequence['Pass']: ...\n");
        add_method_doc(&mut buf, "core/frame", "frame", "passes");
        buf.push_str("    def add_pass(self, pass_: 'Pass') -> None: ...\n");
        add_method_doc(&mut buf, "core/frame", "frame", "add_pass");
        buf.push_str("\n");

        // Shader
        add_class(
            &mut buf,
            "Shader",
            doc_with_python_examples("docs/api/core/shader/shader.md"),
        );
        buf.push_str("    def __init__(self, source: str) -> None: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "new");
        buf.push_str("    def set(self, key: str, value: Any) -> None: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "set");
        buf.push_str("    def get(self, key: str) -> Any: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "get");
        buf.push_str("    def list_uniforms(self) -> list[str]: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "list_uniforms");
        buf.push_str("    def list_keys(self) -> list[str]: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "list_keys");
        buf.push_str("    def add_mesh(self, mesh: 'Mesh') -> None: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "add_mesh");
        buf.push_str("    def remove_mesh(self, mesh: 'Mesh') -> None: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "remove_mesh");
        buf.push_str("    def remove_meshes(self, list_: Sequence['Mesh']) -> None: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "remove_meshes");
        buf.push_str("    def clear_meshes(self) -> None: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "clear_meshes");
        buf.push_str("    def validate_mesh(self, mesh: 'Mesh') -> None: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "validate_mesh");
        buf.push_str("    def is_compute(self) -> bool: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "is_compute");
        buf.push_str("    def passes(self) -> Sequence['Pass']: ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "passes");
        buf.push_str("    @staticmethod\n    def default() -> 'Shader': ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "default");
        buf.push_str("    @staticmethod\n    def from_vertex(v: 'Vertex') -> 'Shader': ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "from_vertex");
        buf.push_str("    @staticmethod\n    def from_mesh(mesh: 'Mesh') -> 'Shader': ...\n");
        add_method_doc(&mut buf, "core/shader", "shader", "from_mesh");
        buf.push_str("\n");

        // Targets
        add_class(
            &mut buf,
            "TextureTarget",
            doc_with_python_examples("docs/api/targets/texture_target/texture_target.md"),
        );
        buf.push_str("    @property\n    def size(self) -> Size: ...\n");
        add_method_doc(&mut buf, "targets/texture_target", "texture_target", "size");
        buf.push_str("    def resize(self, size: PySize) -> None: ...\n");
        add_method_doc(
            &mut buf,
            "targets/texture_target",
            "texture_target",
            "resize",
        );
        buf.push_str("    def get_current_frame(self) -> 'TargetFrame': ...\n");
        add_method_doc(
            &mut buf,
            "targets/texture_target",
            "texture_target",
            "get_current_frame",
        );
        buf.push_str("    def get_image(self) -> 'npt.NDArray[numpy.uint8]': ...\n");
        add_method_doc(
            &mut buf,
            "targets/texture_target",
            "texture_target",
            "get_image",
        );
        buf.push_str("\n");

        add_class(
            &mut buf,
            "TargetFrame",
            doc_with_python_examples("docs/api/targets/target/hidden/get_current_frame.md"),
        );
        buf.push_str("    def format(self) -> str: ...\n");
        add_method_doc(
            &mut buf,
            "targets/target",
            "target",
            "hidden/get_current_frame",
        );
        buf.push_str("    def present(self) -> None: ...\n");
        // no dedicated doc for present; it's a no-op wrapper in Python
        buf.push_str("\n");

        add_class(
            &mut buf,
            "RenderCanvasTarget",
            doc_with_python_examples(
                "docs/api/hidden/platforms/python/render_canvas_target/render_canvas_target.md",
            ),
        );
        buf.push_str("    def __init__(self, canvas: Any, present_methods: Any) -> None: ...\n");
        add_method_doc(
            &mut buf,
            "hidden/platforms/python/render_canvas_target",
            "render_canvas_target",
            "new",
        );
        buf.push_str("    def is_ready(self) -> bool: ...\n");
        add_method_doc(
            &mut buf,
            "hidden/platforms/python/render_canvas_target",
            "render_canvas_target",
            "is_ready",
        );
        buf.push_str("    @property\n    def canvas(self) -> Any: ...\n");
        add_method_doc(
            &mut buf,
            "hidden/platforms/python/render_canvas_target",
            "render_canvas_target",
            "canvas",
        );
        buf.push_str("    def present(self) -> dict[str, Any]: ...\n");
        add_method_doc(
            &mut buf,
            "hidden/platforms/python/render_canvas_target",
            "render_canvas_target",
            "present",
        );
        buf.push_str("    def size(self) -> Size: ...\n");
        add_method_doc(
            &mut buf,
            "hidden/platforms/python/render_canvas_target",
            "render_canvas_target",
            "size",
        );
        buf.push_str("    def resize(self, size: PySize) -> None: ...\n");
        add_method_doc(
            &mut buf,
            "hidden/platforms/python/render_canvas_target",
            "render_canvas_target",
            "resize",
        );
        buf.push_str("\n");

        add_class(
            &mut buf,
            "RenderCanvasFrame",
            doc_with_python_examples(
                "docs/api/hidden/platforms/python/render_canvas_target/present.md",
            ),
        );
        buf.push_str("    def format(self) -> str: ...\n");
        buf.push_str("    def present(self) -> None: ...\n\n");

        // Renderer
        add_class(
            &mut buf,
            "Renderer",
            doc_with_python_examples("docs/api/core/renderer/renderer.md"),
        );
        buf.push_str("    def __init__(self) -> None: ...\n");
        add_method_doc(&mut buf, "core/renderer", "renderer", "new");
        buf.push_str("    def create_target(self, rendercanvas: Any) -> RenderCanvasTarget: ...\n");
        add_method_doc(&mut buf, "core/renderer", "renderer", "create_target");
        buf.push_str("    def create_texture_target(self, size: PySize) -> TextureTarget: ...\n");
        add_method_doc(
            &mut buf,
            "core/renderer",
            "renderer",
            "create_texture_target",
        );
        buf.push_str("\n");

        // create_texture overloads
        buf.push_str("    @overload\n    def create_texture(self, input: bytes | bytearray | Sequence[int]) -> Texture: ...\n");
        buf.push_str("    @overload\n    def create_texture(self, input: str) -> Texture: ...\n");
        buf.push_str(
            "    @overload\n    def create_texture(self, input: NDArrayU8) -> Texture: ...\n",
        );
        add_method_doc(&mut buf, "core/renderer", "renderer", "create_texture");

        buf.push_str("    @overload\n    def create_texture_with_size(self, input: bytes | bytearray | Sequence[int], size: PySize) -> Texture: ...\n");
        buf.push_str("    @overload\n    def create_texture_with_size(self, input: str, size: PySize) -> Texture: ...\n");
        buf.push_str("    @overload\n    def create_texture_with_size(self, input: NDArrayU8, size: PySize) -> Texture: ...\n");
        add_method_doc(
            &mut buf,
            "core/renderer",
            "renderer",
            "create_texture_with_size",
        );

        buf.push_str("    @overload\n    def create_texture_with_format(self, input: bytes | bytearray | Sequence[int], format: TextureFormat) -> Texture: ...\n");
        buf.push_str("    @overload\n    def create_texture_with_format(self, input: str, format: TextureFormat) -> Texture: ...\n");
        buf.push_str("    @overload\n    def create_texture_with_format(self, input: NDArrayU8, format: TextureFormat) -> Texture: ...\n");
        add_method_doc(
            &mut buf,
            "core/renderer",
            "renderer",
            "create_texture_with_format",
        );

        buf.push_str("    def create_texture_with(self, input: bytes | bytearray | Sequence[int] | str | NDArrayU8, size: PySize | None = None) -> Texture: ...\n");
        add_method_doc(&mut buf, "core/renderer", "renderer", "create_texture_with");
        buf.push_str("    def render(self, renderable: Renderable, target: RenderCanvasTarget | TextureTarget) -> None: ...\n");
        add_method_doc(&mut buf, "core/renderer", "renderer", "render");
        buf.push_str("    def create_depth_texture(self, size: PySize) -> Texture: ...\n");
        add_method_doc(
            &mut buf,
            "core/renderer",
            "renderer",
            "create_depth_texture",
        );
        buf.push_str("    def create_storage_texture(self, size: PySize, format: TextureFormat, usage_bits: int | None = None) -> Texture: ...\n");
        add_method_doc(
            &mut buf,
            "core/renderer",
            "renderer",
            "create_storage_texture",
        );
        buf.push_str("\n");

        // Top-level function
        buf.push_str("def rendercanvas_context_hook(canvas: Any, present_methods: Any) -> RenderCanvasTarget: ...\n\n");

        // Write files
        let pyi_path = out_dir.join("fragmentcolor.pyi");
        let mut f = fs::File::create(&pyi_path)?;
        f.write_all(buf.as_bytes())?;

        // Ensure py.typed exists
        let py_typed = out_dir.join("py.typed");
        if !py_typed.exists() {
            fs::File::create(py_typed)?;
        }

        Ok(())
    }

    fn add_class(buf: &mut String, name: &str, doc: Option<String>) {
        buf.push_str(&format!("class {}:\n", name));
        if let Some(d) = doc {
            let d = sanitize_doc(&d);
            buf.push_str("    \"\"\"\n");
            for line in d.lines() {
                buf.push_str("    ");
                buf.push_str(line);
                buf.push('\n');
            }
            buf.push_str("    \"\"\"\n");
        }
    }

    fn doc_with_python_examples(rel: &str) -> Option<String> {
        let root = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into());
        let path = PathBuf::from(root).join(rel);
        let md = fs::read_to_string(path).ok()?;
        Some(render_doc_with_python(&md, rel))
    }

    fn render_doc_with_python(md: &str, label: &str) -> String {
        // Extract content before '## Example' and the first Rust example code block afterward.
        let mut pre = String::new();
        let mut in_example = false;
        let mut in_code = false;
        let mut code_lang = String::new();
        let mut rust_code = String::new();
        let mut captured = false;

        for line in md.lines() {
            let t = line.trim_start();
            if !in_example {
                if t.starts_with("## Example") {
                    in_example = true;
                    continue;
                }
                pre.push_str(line);
                pre.push('\n');
                continue;
            }
            if !in_code && t.starts_with("## ") {
                // end of example section
                break;
            }
            if !in_code && t.starts_with("```") {
                in_code = true;
                // try to capture only first rust or unlabeled block
                let lang = t.trim_start_matches("```").trim().to_ascii_lowercase();
                code_lang = if lang.is_empty() { "rust".into() } else { lang };
                continue;
            }
            if in_code && t.starts_with("```") {
                in_code = false;
                if !rust_code.is_empty() {
                    captured = true;
                }
                continue;
            }
            if in_code {
                if code_lang == "rust" && !captured {
                    rust_code.push_str(line);
                    rust_code.push('\n');
                }
            }
        }

        let mut out = String::new();
        let pre = sanitize_doc(&pre);
        out.push_str(&pre);

        if !rust_code.trim().is_empty() {
            // Convert to Python using the same converter as website/README flows
            let items = lines_to_items(&rust_code);
            let py_code = crate::convert::to_py(&items, label);
            out.push_str("\n\nExample (Python):\n\n");
            out.push_str("```python\n");
            out.push_str(py_code.trim_end());
            out.push_str("\n```\n");
        }

        out
    }

    fn lines_to_items(rust: &str) -> Vec<(String, bool)> {
        let mut items: Vec<(String, bool)> = Vec::new();
        for l in rust.lines() {
            let trimmed = l.trim_start();
            let indent_len = l.len() - trimmed.len();
            if trimmed.starts_with('#') {
                let after = trimmed.trim_start_matches('#').trim_start();
                let new_text = format!("{}{}", &l[..indent_len], after);
                items.push((new_text, true));
            } else {
                items.push((l.to_string(), false));
            }
        }
        items
    }

    fn sanitize_doc(s: &str) -> String {
        // Keep it simple: include raw markdown; triple quotes are unlikely, but escape if any
        s.replace("\"\"\"", "'''")
    }
}
