[book]
title = "PLRender Documentation"
authors = ["Rafael Beckel"]
multilingual = false
language = "en"
src = "src"

[rust]
edition = "2021"

[build]
build-dir = "../public"

[output.html]
additional-css = ["tabs.css"]
additional-js = ["tabs.js"]
