[package]
name = "plrender"
description = "An unified API to render video enrichments across multiple platforms"
repository = "https://gitlab.com/pupil-labs/pupil-cloud/pl-render"
authors = ["Pupil Labs GmbH"]
license-file = "LICENCE.md"
version = "0.4.5"
edition = "2021"

[lib]
name = "plrender"
crate-type = ["cdylib", "rlib"]

[features]
default = ["window"]
window = ["raw-window-handle", "winit"]
shape = ["lyon"]

[dependencies]
# public
wgpu = "0.17"
bytemuck = { version = "1.14", features = ["derive"] }
hecs = { version = "0.10", features=["macros"] }
phf = { version = "0.11", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
bitflags = "2.4"
fxhash = "0.2"
mint = "0.5"

# We can update both of them when wgpu implements
# https://github.com/gfx-rs/wgpu/pull/4202
raw-window-handle = { version = "0.5", optional = true }
winit = { version = "0.28.7", optional = true }

# private
ddsfile = "0.5"
glam = { version = "0.24", features = ["mint"] }
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "bmp", "hdr", "dds"] }
lyon = { version = "1", optional = true }
instant = "0.1"
log = "0.4"
csscolorparser = "0.6"

[build-dependencies]
cfg_aliases = "0.1"
