[package]
name = "plrender"
description = "An unified API to render video enrichments across multiple platforms"
repository = "https://gitlab.com/pupil-labs/pupil-cloud/pl-render"
authors = ["Pupil Labs GmbH"]
license-file = "LICENCE.md"
version = "0.1.1"
edition = "2021"

[lib]
name = "plrender"
crate-type = ["cdylib", "rlib"]

[features]
default = ["window"]
window = ["raw-window-handle", "winit"]
shape = ["lyon"]

[build-dependencies]
cfg_aliases = "0.1"

[dependencies]
plr = { package="plrender-core", path = "../plrender-core" }
mint = "0.5"
bitflags = "2.4"
bytemuck = { version = "1.14", features = ["derive"] }
glam = "0.24"
gltf = { version = "1", features = ["names", "utils", "KHR_lights_punctual"], optional = true }
fxhash = "0.2"
log = "0.4"
hecs = "0.10"
obj = { version = "0.10", optional = true }
raw-window-handle = { version = "0.5", optional = true }
winit = { version = "0.28", optional = true }
wgpu = "0.17"
lyon = { version = "1", optional = true }
csscolorparser = "0.6"
instant = "0.1"

# old dependencies, reintroduce them as needed
# anyhow = "1.0"
# thiserror = "1.0"
# cfg-if = "1"
# env_logger = "0.10"
# pollster = "0.3"
# palette = "0.7"
# serde_json = "1"
# naga_oil = "0.9"
# wgpu_text = "0.8"
# serde = { version = "1", features = ["derive"] }
# smart-default = "0.7.1"
# enum_dispatch = "0.3.12"
# tobj = { version = "4", features = [
#     "async",
# ]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
image = {version = "0.24", optional = true}

[target.'cfg(target_arch = "wasm32")'.dependencies.image]
version = "0.24"
default-features = false
features = ["jpeg", "png"]
