name: "Dependencies license check"

on:
    workflow_dispatch:
    pull_request:
        paths:
            - "**/*.toml"

jobs:
    dependencies_check:
        timeout-minutes: 20
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: "recursive"

            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Check dependencies
              uses: EmbarkStudios/cargo-deny-action@v1
              with:
                  command: check licenses
                  arguments: --all-features
