name: Publish crates.io

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Pre-flight skip if version exists on crates.io
        id: preflight
        run: |
          set -euo pipefail
          VER=$(grep '^version = ' Cargo.toml | head -n1 | cut -d'"' -f2)
          echo "version=$VER" >> "$GITHUB_OUTPUT"
          if curl -s -f "https://crates.io/api/v1/crates/fragmentcolor/$VER" > /dev/null; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish to crates.io
        if: steps.preflight.outputs.skip != 'true'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p fragmentcolor --locked
